package rgrep

// File type → extension mappings, ported from ripgrep's default_types.rs.
var DefaultTypes = map[string][]string{
	"agda":          {".agda"},
	"aidl":          {".aidl"},
	"alire":         {".gpr"},
	"amake":         {".am", ".mak"},
	"asciidoc":      {".adoc", ".asc", ".asciidoc"},
	"asm":           {".asm", ".s", ".S"},
	"asp":           {".adp", ".asa", ".asp", ".asax", ".ascx", ".ashx", ".asmx", ".aspx", ".axd"},
	"ats":           {".ats", ".dats", ".hats", ".sats"},
	"awk":           {".awk"},
	"batch":         {".bat", ".cmd"},
	"bicep":         {".bicep", ".bicepparam"},
	"bitbake":       {".bb", ".bbappend", ".bbclass", ".conf", ".inc"},
	"buildstream":   {".bst"},
	"carp":          {".carp"},
	"cc":            {".c", ".h", ".cats", ".cproto", ".h.in"},
	"cfg":           {".cfg", ".conf"},
	"clojure":       {".clj", ".cljs", ".cljc", ".cljx", ".edn"},
	"cmake":         {".cmake", "CMakeLists.txt"},
	"coffeescript":  {".coffee", ".cjsx", ".iced"},
	"cpp":           {".cpp", ".cc", ".cxx", ".c++", ".hh", ".hpp", ".hxx", ".h++", ".inl", ".ipp"},
	"crystal":       {".cr"},
	"csharp":        {".cs"},
	"cshtml":        {".cshtml"},
	"css":           {".css", ".scss", ".sass", ".less"},
	"cuda":          {".cu", ".cuh"},
	"cython":        {".pyx", ".pxd", ".pxi"},
	"d":             {".d"},
	"dart":          {".dart"},
	"devicetree":    {".dts", ".dtsi"},
	"dhall":         {".dhall"},
	"diff":          {".diff", ".patch"},
	"docker":        {"Dockerfile", ".dockerignore"},
	"dot":           {".dot"},
	"dtd":           {".dtd"},
	"elixir":        {".ex", ".exs"},
	"elm":           {".elm"},
	"erlang":        {".erl", ".hrl", ".escript", ".app.src"},
	"fennel":        {".fnl"},
	"fish":          {".fish"},
	"fortran":       {".f", ".for", ".f90", ".f95", ".f03", ".f08", ".f15"},
	"fsharp":        {".fs", ".fsi", ".fsx"},
	"fvu":           {".fvu"},
	"gdscript":      {".gd", ".godot"},
	"glsl":          {".vert", ".tesc", ".tese", ".geo", ".frag", ".comp"},
	"go":            {".go"},
	"gradle":        {".gradle", "gradlew", "gradlew.bat"},
	"graphql":       {".graphql", ".gql"},
	"groovy":        {".groovy", ".gvy", ".gradle"},
	"haml":          {".haml"},
	"haskell":       {".hs", ".lhs"},
	"haxe":          {".hx", ".hxsl"},
	"hdr":           {".hdr"},
	"hcl":           {".hcl", ".tf", ".tfvars"},
	"hsail":         {".hsail"},
	"html":          {".htm", ".html", ".xhtml"},
	"idris":         {".idr", ".ipkg", ".lidr"},
	"ini":           {".ini"},
	"janet":         {".janet"},
	"java":          {".java"},
	"jinja":         {".j2", ".jinja", ".jinja2"},
	"jison":         {".jison"},
	"jl":            {".jl"},
	"json":          {".json"},
	"jupyter":       {".ipynb"},
	"jsx":           {".jsx"},
	"julia":         {".jl"},
	"kotlin":        {".kt", ".kts", ".ktm"},
	"kak":           {".kak"},
	"ledger":        {".ledger"},
	"lektor":        {".lr"},
	"less":          {".less"},
	"lhaskell":      {".lhs"},
	"license":       {"COPYING", "LICENSE", "LICENSE-*"},
	"lisp":          {".lisp", ".lsp", ".el", ".cl", ".clj", ".cljs", ".scm", ".ss"},
	"log":           {".log"},
	"lua":           {".lua"},
	"luau":          {".luau"},
	"lzma":          {".lzma"},
	"m4":            {".m4"},
	"mail":          {".eml", ".mbox"},
	"make":          {"Makefile", "GNUMakefile", "makefile", "GNUmakefile"},
	"man":           {".man", ".mdoc", ".me", ".ms", ".roff", ".tmac"},
	"mascot":        {".mscx", ".mscz"},
	"matlab":        {".m"},
	"meson":         {"meson.build", "meson.options", "meson_options.txt"},
	"minizinc":      {".mzn"},
	"mk":            {".mk"},
	"ml":            {".ml", ".mli"},
	"motoko":        {".mo"},
	"mustache":      {".mustache", ".stache"},
	"nim":           {".nim", ".nims", ".nimble"},
	"nix":           {".nix"},
	"nu":            {".nu"},
	"objc":          {".h", ".m"},
	"objcpp":        {".mm"},
	"objective-c":   {".h", ".m"},
	"objective-cpp": {".mm"},
	"ocaml":         {".ml", ".mli", ".mll", ".mly", ".eliom", ".eliomi"},
	"org":           {".org"},
	"pascal":        {".pas", ".pp", ".dpr", ".lpr"},
	"path":          {".path"},
	"perl":          {".pl", ".pm", ".t", ".pod", ".xs"},
	"php":           {".php", ".php3", ".php4", ".php5", ".phtml"},
	"po":            {".po"},
	"pofiles":       {".po"},
	"pony":          {".pony"},
	"postscript":    {".eps", ".ps"},
	"prolog":        {".pl", ".pro", ".prolog"},
	"protobuf":      {".proto"},
	"ps1":           {".ps1", ".psm1", ".psd1"},
	"pug":           {".pug"},
	"puppet":        {".pp"},
	"purs":          {".purs"},
	"py":            {".py", ".pyi"},
	"python":        {".py", ".pyi"},
	"qml":           {".qml"},
	"r":             {".R", ".r", ".Rmd", ".rmd"},
	"racket":        {".rkt", ".scrbl"},
	"rdoc":          {".rdoc"},
	"readme":        {"README*", "README.*"},
	"reason":        {".re", ".rei"},
	"rego":          {".rego"},
	"renpy":         {".rpy"},
	"rescript":      {".res", ".resi"},
	"rexx":          {".rexx", ".pprx"},
	"robot":         {".robot"},
	"rst":           {".rst"},
	"ruby":          {".rb", ".erb", ".gemspec", ".rake", ".ru"},
	"rust":          {".rs"},
	"sass":          {".sass", ".scss"},
	"scala":         {".scala", ".sbt", ".sc"},
	"sh":            {".sh", ".bash", ".zsh", ".fish", ".ksh"},
	"sml":           {".sml", ".sig"},
	"solidity":      {".sol"},
	"sql":           {".sql"},
	"stata":         {".do", ".ado", ".mata"},
	"stylus":        {".styl"},
	"svelte":        {".svelte"},
	"svg":           {".svg"},
	"swift":         {".swift"},
	"swig":          {".swig", ".swg"},
	"systemverilog": {".sv", ".svh", ".vh"},
	"tcl":           {".tcl"},
	"tea":           {".tea"},
	"templ":         {".templ"},
	"terraform":     {".tf", ".tfvars", ".hcl"},
	"tex":           {".tex", ".sty", ".cls", ".dtx", ".ins"},
	"textile":       {".textile"},
	"thrift":        {".thrift"},
	"toml":          {".toml"},
	"tsx":           {".tsx"},
	"twig":          {".twig"},
	"ts":            {".ts", ".tsx", ".mts", ".cts"},
	"typescript":    {".ts", ".mts", ".cts", ".tsx"},
	"typoscript":    {".typoscript"},
	"typst":         {".typ"},
	"usd":           {".usd", ".usda"},
	"v":             {".v", ".vh"},
	"vala":          {".vala", ".vapi"},
	"verilog":       {".v", ".vh", ".sv", ".svh"},
	"vhdl":          {".vhd", ".vhdl"},
	"vim":           {".vim"},
	"vue":           {".vue"},
	"wgsl":          {".wgsl"},
	"wiki":          {".wiki"},
	"xsl":           {".xsl"},
	"xml":           {".xml"},
	"yaml":          {".yaml", ".yml"},
	"yang":          {".yang"},
	"yul":           {".yul"},
	"zig":           {".zig"},
	"zsh":           {".zsh"},
}

// ExtensionsForType returns the file extensions for a given language type.
func ExtensionsForType(typeName string) []string {
	if exts, ok := DefaultTypes[typeName]; ok {
		return exts
	}
	return nil
}
