// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/http/pprof

package microlisp

import (
	pprof "net/http/pprof"
)

func register_net_http_pprof() {
	registerPackage(
		"net/http/pprof",
		map[string]interface{}{
			"Cmdline": pprof.Cmdline,
			"Handler": pprof.Handler,
			"Index": pprof.Index,
			"Profile": pprof.Profile,
			"Symbol": pprof.Symbol,
			"Trace": pprof.Trace,
		},
	)
}

