// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: debug/plan9obj

package microlisp

import (
	plan9obj "debug/plan9obj"
	"reflect"
)

func register_debug_plan9obj() {
	registerPackage(
		"debug/plan9obj",
		map[string]interface{}{
			"NewFile": plan9obj.NewFile,
			"Open": plan9obj.Open,
			"ErrNoSymbols": plan9obj.ErrNoSymbols,
			"Magic386": plan9obj.Magic386,
			"Magic64": plan9obj.Magic64,
			"MagicAMD64": plan9obj.MagicAMD64,
			"MagicARM": plan9obj.MagicARM,
		},
	)
	registerType("debug/plan9obj", "File", reflect.TypeOf((*plan9obj.File)(nil)).Elem())
	registerType("debug/plan9obj", "FileHeader", reflect.TypeOf((*plan9obj.FileHeader)(nil)).Elem())
	registerType("debug/plan9obj", "Section", reflect.TypeOf((*plan9obj.Section)(nil)).Elem())
	registerType("debug/plan9obj", "SectionHeader", reflect.TypeOf((*plan9obj.SectionHeader)(nil)).Elem())
	registerType("debug/plan9obj", "Sym", reflect.TypeOf((*plan9obj.Sym)(nil)).Elem())
}

