// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/dsa

package microlisp

import (
	dsa "crypto/dsa"
	"reflect"
)

func register_crypto_dsa() {
	registerPackage(
		"crypto/dsa",
		map[string]interface{}{
			"GenerateKey": dsa.GenerateKey,
			"GenerateParameters": dsa.GenerateParameters,
			"Sign": dsa.Sign,
			"Verify": dsa.Verify,
			"ErrInvalidPublicKey": dsa.ErrInvalidPublicKey,
			"L1024N160": dsa.L1024N160,
			"L2048N224": dsa.L2048N224,
			"L2048N256": dsa.L2048N256,
			"L3072N256": dsa.L3072N256,
		},
	)
	registerType("crypto/dsa", "ParameterSizes", reflect.TypeOf((*dsa.ParameterSizes)(nil)).Elem())
	registerType("crypto/dsa", "Parameters", reflect.TypeOf((*dsa.Parameters)(nil)).Elem())
	registerType("crypto/dsa", "PrivateKey", reflect.TypeOf((*dsa.PrivateKey)(nil)).Elem())
	registerType("crypto/dsa", "PublicKey", reflect.TypeOf((*dsa.PublicKey)(nil)).Elem())
}

