// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/smtp

package microlisp

import (
	smtp "net/smtp"
	"reflect"
)

func register_net_smtp() {
	registerPackage(
		"net/smtp",
		map[string]interface{}{
			"CRAMMD5Auth": smtp.CRAMMD5Auth,
			"Dial": smtp.Dial,
			"NewClient": smtp.NewClient,
			"PlainAuth": smtp.PlainAuth,
			"SendMail": smtp.SendMail,
		},
	)
	registerType("net/smtp", "Auth", reflect.TypeOf((*smtp.Auth)(nil)).Elem())
	registerType("net/smtp", "Client", reflect.TypeOf((*smtp.Client)(nil)).Elem())
	registerType("net/smtp", "ServerInfo", reflect.TypeOf((*smtp.ServerInfo)(nil)).Elem())
}

