// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: debug/dwarf

package microlisp

import (
	dwarf "debug/dwarf"
	"reflect"
)

func register_debug_dwarf() {
	registerPackage(
		"debug/dwarf",
		map[string]interface{}{
			"New": dwarf.New,
			"ErrUnknownPC": dwarf.ErrUnknownPC,
			"AttrAbstractOrigin": dwarf.AttrAbstractOrigin,
			"AttrAccessibility": dwarf.AttrAccessibility,
			"AttrAddrBase": dwarf.AttrAddrBase,
			"AttrAddrClass": dwarf.AttrAddrClass,
			"AttrAlignment": dwarf.AttrAlignment,
			"AttrAllocated": dwarf.AttrAllocated,
			"AttrArtificial": dwarf.AttrArtificial,
			"AttrAssociated": dwarf.AttrAssociated,
			"AttrBaseTypes": dwarf.AttrBaseTypes,
			"AttrBinaryScale": dwarf.AttrBinaryScale,
			"AttrBitOffset": dwarf.AttrBitOffset,
			"AttrBitSize": dwarf.AttrBitSize,
			"AttrByteSize": dwarf.AttrByteSize,
			"AttrCallAllCalls": dwarf.AttrCallAllCalls,
			"AttrCallAllSourceCalls": dwarf.AttrCallAllSourceCalls,
			"AttrCallAllTailCalls": dwarf.AttrCallAllTailCalls,
			"AttrCallColumn": dwarf.AttrCallColumn,
			"AttrCallDataLocation": dwarf.AttrCallDataLocation,
			"AttrCallDataValue": dwarf.AttrCallDataValue,
			"AttrCallFile": dwarf.AttrCallFile,
			"AttrCallLine": dwarf.AttrCallLine,
			"AttrCallOrigin": dwarf.AttrCallOrigin,
			"AttrCallPC": dwarf.AttrCallPC,
			"AttrCallParameter": dwarf.AttrCallParameter,
			"AttrCallReturnPC": dwarf.AttrCallReturnPC,
			"AttrCallTailCall": dwarf.AttrCallTailCall,
			"AttrCallTarget": dwarf.AttrCallTarget,
			"AttrCallTargetClobbered": dwarf.AttrCallTargetClobbered,
			"AttrCallValue": dwarf.AttrCallValue,
			"AttrCalling": dwarf.AttrCalling,
			"AttrCommonRef": dwarf.AttrCommonRef,
			"AttrCompDir": dwarf.AttrCompDir,
			"AttrConstExpr": dwarf.AttrConstExpr,
			"AttrConstValue": dwarf.AttrConstValue,
			"AttrContainingType": dwarf.AttrContainingType,
			"AttrCount": dwarf.AttrCount,
			"AttrDataBitOffset": dwarf.AttrDataBitOffset,
			"AttrDataLocation": dwarf.AttrDataLocation,
			"AttrDataMemberLoc": dwarf.AttrDataMemberLoc,
			"AttrDecimalScale": dwarf.AttrDecimalScale,
			"AttrDecimalSign": dwarf.AttrDecimalSign,
			"AttrDeclColumn": dwarf.AttrDeclColumn,
			"AttrDeclFile": dwarf.AttrDeclFile,
			"AttrDeclLine": dwarf.AttrDeclLine,
			"AttrDeclaration": dwarf.AttrDeclaration,
			"AttrDefaultValue": dwarf.AttrDefaultValue,
			"AttrDefaulted": dwarf.AttrDefaulted,
			"AttrDeleted": dwarf.AttrDeleted,
			"AttrDescription": dwarf.AttrDescription,
			"AttrDigitCount": dwarf.AttrDigitCount,
			"AttrDiscr": dwarf.AttrDiscr,
			"AttrDiscrList": dwarf.AttrDiscrList,
			"AttrDiscrValue": dwarf.AttrDiscrValue,
			"AttrDwoName": dwarf.AttrDwoName,
			"AttrElemental": dwarf.AttrElemental,
			"AttrEncoding": dwarf.AttrEncoding,
			"AttrEndianity": dwarf.AttrEndianity,
			"AttrEntrypc": dwarf.AttrEntrypc,
			"AttrEnumClass": dwarf.AttrEnumClass,
			"AttrExplicit": dwarf.AttrExplicit,
			"AttrExportSymbols": dwarf.AttrExportSymbols,
			"AttrExtension": dwarf.AttrExtension,
			"AttrExternal": dwarf.AttrExternal,
			"AttrFrameBase": dwarf.AttrFrameBase,
			"AttrFriend": dwarf.AttrFriend,
			"AttrHighpc": dwarf.AttrHighpc,
			"AttrIdentifierCase": dwarf.AttrIdentifierCase,
			"AttrImport": dwarf.AttrImport,
			"AttrInline": dwarf.AttrInline,
			"AttrIsOptional": dwarf.AttrIsOptional,
			"AttrLanguage": dwarf.AttrLanguage,
			"AttrLinkageName": dwarf.AttrLinkageName,
			"AttrLocation": dwarf.AttrLocation,
			"AttrLoclistsBase": dwarf.AttrLoclistsBase,
			"AttrLowerBound": dwarf.AttrLowerBound,
			"AttrLowpc": dwarf.AttrLowpc,
			"AttrMacroInfo": dwarf.AttrMacroInfo,
			"AttrMacros": dwarf.AttrMacros,
			"AttrMainSubprogram": dwarf.AttrMainSubprogram,
			"AttrMutable": dwarf.AttrMutable,
			"AttrName": dwarf.AttrName,
			"AttrNamelistItem": dwarf.AttrNamelistItem,
			"AttrNoreturn": dwarf.AttrNoreturn,
			"AttrObjectPointer": dwarf.AttrObjectPointer,
			"AttrOrdering": dwarf.AttrOrdering,
			"AttrPictureString": dwarf.AttrPictureString,
			"AttrPriority": dwarf.AttrPriority,
			"AttrProducer": dwarf.AttrProducer,
			"AttrPrototyped": dwarf.AttrPrototyped,
			"AttrPure": dwarf.AttrPure,
			"AttrRanges": dwarf.AttrRanges,
			"AttrRank": dwarf.AttrRank,
			"AttrRecursive": dwarf.AttrRecursive,
			"AttrReference": dwarf.AttrReference,
			"AttrReturnAddr": dwarf.AttrReturnAddr,
			"AttrRnglistsBase": dwarf.AttrRnglistsBase,
			"AttrRvalueReference": dwarf.AttrRvalueReference,
			"AttrSegment": dwarf.AttrSegment,
			"AttrSibling": dwarf.AttrSibling,
			"AttrSignature": dwarf.AttrSignature,
			"AttrSmall": dwarf.AttrSmall,
			"AttrSpecification": dwarf.AttrSpecification,
			"AttrStartScope": dwarf.AttrStartScope,
			"AttrStaticLink": dwarf.AttrStaticLink,
			"AttrStmtList": dwarf.AttrStmtList,
			"AttrStrOffsetsBase": dwarf.AttrStrOffsetsBase,
			"AttrStride": dwarf.AttrStride,
			"AttrStrideSize": dwarf.AttrStrideSize,
			"AttrStringLength": dwarf.AttrStringLength,
			"AttrStringLengthBitSize": dwarf.AttrStringLengthBitSize,
			"AttrStringLengthByteSize": dwarf.AttrStringLengthByteSize,
			"AttrThreadsScaled": dwarf.AttrThreadsScaled,
			"AttrTrampoline": dwarf.AttrTrampoline,
			"AttrType": dwarf.AttrType,
			"AttrUpperBound": dwarf.AttrUpperBound,
			"AttrUseLocation": dwarf.AttrUseLocation,
			"AttrUseUTF8": dwarf.AttrUseUTF8,
			"AttrVarParam": dwarf.AttrVarParam,
			"AttrVirtuality": dwarf.AttrVirtuality,
			"AttrVisibility": dwarf.AttrVisibility,
			"AttrVtableElemLoc": dwarf.AttrVtableElemLoc,
			"ClassAddrPtr": dwarf.ClassAddrPtr,
			"ClassAddress": dwarf.ClassAddress,
			"ClassBlock": dwarf.ClassBlock,
			"ClassConstant": dwarf.ClassConstant,
			"ClassExprLoc": dwarf.ClassExprLoc,
			"ClassFlag": dwarf.ClassFlag,
			"ClassLinePtr": dwarf.ClassLinePtr,
			"ClassLocList": dwarf.ClassLocList,
			"ClassLocListPtr": dwarf.ClassLocListPtr,
			"ClassMacPtr": dwarf.ClassMacPtr,
			"ClassRangeListPtr": dwarf.ClassRangeListPtr,
			"ClassReference": dwarf.ClassReference,
			"ClassReferenceAlt": dwarf.ClassReferenceAlt,
			"ClassReferenceSig": dwarf.ClassReferenceSig,
			"ClassRngList": dwarf.ClassRngList,
			"ClassRngListsPtr": dwarf.ClassRngListsPtr,
			"ClassStrOffsetsPtr": dwarf.ClassStrOffsetsPtr,
			"ClassString": dwarf.ClassString,
			"ClassStringAlt": dwarf.ClassStringAlt,
			"ClassUnknown": dwarf.ClassUnknown,
			"TagAccessDeclaration": dwarf.TagAccessDeclaration,
			"TagArrayType": dwarf.TagArrayType,
			"TagAtomicType": dwarf.TagAtomicType,
			"TagBaseType": dwarf.TagBaseType,
			"TagCallSite": dwarf.TagCallSite,
			"TagCallSiteParameter": dwarf.TagCallSiteParameter,
			"TagCatchDwarfBlock": dwarf.TagCatchDwarfBlock,
			"TagClassType": dwarf.TagClassType,
			"TagCoarrayType": dwarf.TagCoarrayType,
			"TagCommonDwarfBlock": dwarf.TagCommonDwarfBlock,
			"TagCommonInclusion": dwarf.TagCommonInclusion,
			"TagCompileUnit": dwarf.TagCompileUnit,
			"TagCondition": dwarf.TagCondition,
			"TagConstType": dwarf.TagConstType,
			"TagConstant": dwarf.TagConstant,
			"TagDwarfProcedure": dwarf.TagDwarfProcedure,
			"TagDynamicType": dwarf.TagDynamicType,
			"TagEntryPoint": dwarf.TagEntryPoint,
			"TagEnumerationType": dwarf.TagEnumerationType,
			"TagEnumerator": dwarf.TagEnumerator,
			"TagFileType": dwarf.TagFileType,
			"TagFormalParameter": dwarf.TagFormalParameter,
			"TagFriend": dwarf.TagFriend,
			"TagGenericSubrange": dwarf.TagGenericSubrange,
			"TagImmutableType": dwarf.TagImmutableType,
			"TagImportedDeclaration": dwarf.TagImportedDeclaration,
			"TagImportedModule": dwarf.TagImportedModule,
			"TagImportedUnit": dwarf.TagImportedUnit,
			"TagInheritance": dwarf.TagInheritance,
			"TagInlinedSubroutine": dwarf.TagInlinedSubroutine,
			"TagInterfaceType": dwarf.TagInterfaceType,
			"TagLabel": dwarf.TagLabel,
			"TagLexDwarfBlock": dwarf.TagLexDwarfBlock,
			"TagMember": dwarf.TagMember,
			"TagModule": dwarf.TagModule,
			"TagMutableType": dwarf.TagMutableType,
			"TagNamelist": dwarf.TagNamelist,
			"TagNamelistItem": dwarf.TagNamelistItem,
			"TagNamespace": dwarf.TagNamespace,
			"TagPackedType": dwarf.TagPackedType,
			"TagPartialUnit": dwarf.TagPartialUnit,
			"TagPointerType": dwarf.TagPointerType,
			"TagPtrToMemberType": dwarf.TagPtrToMemberType,
			"TagReferenceType": dwarf.TagReferenceType,
			"TagRestrictType": dwarf.TagRestrictType,
			"TagRvalueReferenceType": dwarf.TagRvalueReferenceType,
			"TagSetType": dwarf.TagSetType,
			"TagSharedType": dwarf.TagSharedType,
			"TagSkeletonUnit": dwarf.TagSkeletonUnit,
			"TagStringType": dwarf.TagStringType,
			"TagStructType": dwarf.TagStructType,
			"TagSubprogram": dwarf.TagSubprogram,
			"TagSubrangeType": dwarf.TagSubrangeType,
			"TagSubroutineType": dwarf.TagSubroutineType,
			"TagTemplateAlias": dwarf.TagTemplateAlias,
			"TagTemplateTypeParameter": dwarf.TagTemplateTypeParameter,
			"TagTemplateValueParameter": dwarf.TagTemplateValueParameter,
			"TagThrownType": dwarf.TagThrownType,
			"TagTryDwarfBlock": dwarf.TagTryDwarfBlock,
			"TagTypeUnit": dwarf.TagTypeUnit,
			"TagTypedef": dwarf.TagTypedef,
			"TagUnionType": dwarf.TagUnionType,
			"TagUnspecifiedParameters": dwarf.TagUnspecifiedParameters,
			"TagUnspecifiedType": dwarf.TagUnspecifiedType,
			"TagVariable": dwarf.TagVariable,
			"TagVariant": dwarf.TagVariant,
			"TagVariantPart": dwarf.TagVariantPart,
			"TagVolatileType": dwarf.TagVolatileType,
			"TagWithStmt": dwarf.TagWithStmt,
		},
	)
	registerType("debug/dwarf", "AddrType", reflect.TypeOf((*dwarf.AddrType)(nil)).Elem())
	registerType("debug/dwarf", "ArrayType", reflect.TypeOf((*dwarf.ArrayType)(nil)).Elem())
	registerType("debug/dwarf", "Attr", reflect.TypeOf((*dwarf.Attr)(nil)).Elem())
	registerType("debug/dwarf", "BasicType", reflect.TypeOf((*dwarf.BasicType)(nil)).Elem())
	registerType("debug/dwarf", "BoolType", reflect.TypeOf((*dwarf.BoolType)(nil)).Elem())
	registerType("debug/dwarf", "CharType", reflect.TypeOf((*dwarf.CharType)(nil)).Elem())
	registerType("debug/dwarf", "Class", reflect.TypeOf((*dwarf.Class)(nil)).Elem())
	registerType("debug/dwarf", "CommonType", reflect.TypeOf((*dwarf.CommonType)(nil)).Elem())
	registerType("debug/dwarf", "ComplexType", reflect.TypeOf((*dwarf.ComplexType)(nil)).Elem())
	registerType("debug/dwarf", "Data", reflect.TypeOf((*dwarf.Data)(nil)).Elem())
	registerType("debug/dwarf", "DecodeError", reflect.TypeOf((*dwarf.DecodeError)(nil)).Elem())
	registerType("debug/dwarf", "DotDotDotType", reflect.TypeOf((*dwarf.DotDotDotType)(nil)).Elem())
	registerType("debug/dwarf", "Entry", reflect.TypeOf((*dwarf.Entry)(nil)).Elem())
	registerType("debug/dwarf", "EnumType", reflect.TypeOf((*dwarf.EnumType)(nil)).Elem())
	registerType("debug/dwarf", "EnumValue", reflect.TypeOf((*dwarf.EnumValue)(nil)).Elem())
	registerType("debug/dwarf", "Field", reflect.TypeOf((*dwarf.Field)(nil)).Elem())
	registerType("debug/dwarf", "FloatType", reflect.TypeOf((*dwarf.FloatType)(nil)).Elem())
	registerType("debug/dwarf", "FuncType", reflect.TypeOf((*dwarf.FuncType)(nil)).Elem())
	registerType("debug/dwarf", "IntType", reflect.TypeOf((*dwarf.IntType)(nil)).Elem())
	registerType("debug/dwarf", "LineEntry", reflect.TypeOf((*dwarf.LineEntry)(nil)).Elem())
	registerType("debug/dwarf", "LineFile", reflect.TypeOf((*dwarf.LineFile)(nil)).Elem())
	registerType("debug/dwarf", "LineReader", reflect.TypeOf((*dwarf.LineReader)(nil)).Elem())
	registerType("debug/dwarf", "LineReaderPos", reflect.TypeOf((*dwarf.LineReaderPos)(nil)).Elem())
	registerType("debug/dwarf", "Offset", reflect.TypeOf((*dwarf.Offset)(nil)).Elem())
	registerType("debug/dwarf", "PtrType", reflect.TypeOf((*dwarf.PtrType)(nil)).Elem())
	registerType("debug/dwarf", "QualType", reflect.TypeOf((*dwarf.QualType)(nil)).Elem())
	registerType("debug/dwarf", "Reader", reflect.TypeOf((*dwarf.Reader)(nil)).Elem())
	registerType("debug/dwarf", "StructField", reflect.TypeOf((*dwarf.StructField)(nil)).Elem())
	registerType("debug/dwarf", "StructType", reflect.TypeOf((*dwarf.StructType)(nil)).Elem())
	registerType("debug/dwarf", "Tag", reflect.TypeOf((*dwarf.Tag)(nil)).Elem())
	registerType("debug/dwarf", "Type", reflect.TypeOf((*dwarf.Type)(nil)).Elem())
	registerType("debug/dwarf", "TypedefType", reflect.TypeOf((*dwarf.TypedefType)(nil)).Elem())
	registerType("debug/dwarf", "UcharType", reflect.TypeOf((*dwarf.UcharType)(nil)).Elem())
	registerType("debug/dwarf", "UintType", reflect.TypeOf((*dwarf.UintType)(nil)).Elem())
	registerType("debug/dwarf", "UnspecifiedType", reflect.TypeOf((*dwarf.UnspecifiedType)(nil)).Elem())
	registerType("debug/dwarf", "UnsupportedType", reflect.TypeOf((*dwarf.UnsupportedType)(nil)).Elem())
	registerType("debug/dwarf", "VoidType", reflect.TypeOf((*dwarf.VoidType)(nil)).Elem())
}

