// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: debug/buildinfo

package microlisp

import (
	buildinfo "debug/buildinfo"
	"reflect"
)

func register_debug_buildinfo() {
	registerPackage(
		"debug/buildinfo",
		map[string]interface{}{
			"Read": buildinfo.Read,
			"ReadFile": buildinfo.ReadFile,
		},
	)
	registerType("debug/buildinfo", "BuildInfo", reflect.TypeOf((*buildinfo.BuildInfo)(nil)).Elem())
}

