// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: runtime/coverage

package microlisp

import (
	coverage "runtime/coverage"
)

func register_runtime_coverage() {
	registerPackage(
		"runtime/coverage",
		map[string]interface{}{
			"ClearCounters": coverage.ClearCounters,
			"WriteCounters": coverage.WriteCounters,
			"WriteCountersDir": coverage.WriteCountersDir,
			"WriteMeta": coverage.WriteMeta,
			"WriteMetaDir": coverage.WriteMetaDir,
		},
	)
}

