// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: plugin

package microlisp

import (
	plugin "plugin"
	"reflect"
)

func register_plugin() {
	registerPackage(
		"plugin",
		map[string]interface{}{
			"Open": plugin.Open,
		},
	)
	registerType("plugin", "Plugin", reflect.TypeOf((*plugin.Plugin)(nil)).Elem())
	registerType("plugin", "Symbol", reflect.TypeOf((*plugin.Symbol)(nil)).Elem())
}

