// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: text/template

package microlisp

import (
	template "text/template"
	"reflect"
)

func register_text_template() {
	registerPackage(
		"text/template",
		map[string]interface{}{
			"HTMLEscape": template.HTMLEscape,
			"HTMLEscapeString": template.HTMLEscapeString,
			"HTMLEscaper": template.HTMLEscaper,
			"IsTrue": template.IsTrue,
			"JSEscape": template.JSEscape,
			"JSEscapeString": template.JSEscapeString,
			"JSEscaper": template.JSEscaper,
			"Must": template.Must,
			"New": template.New,
			"ParseFS": template.ParseFS,
			"ParseFiles": template.ParseFiles,
			"ParseGlob": template.ParseGlob,
			"URLQueryEscaper": template.URLQueryEscaper,
		},
	)
	registerType("text/template", "ExecError", reflect.TypeOf((*template.ExecError)(nil)).Elem())
	registerType("text/template", "FuncMap", reflect.TypeOf((*template.FuncMap)(nil)).Elem())
	registerType("text/template", "Template", reflect.TypeOf((*template.Template)(nil)).Elem())
}

