// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/cipher

package microlisp

import (
	cipher "crypto/cipher"
	"reflect"
)

func register_crypto_cipher() {
	registerPackage(
		"crypto/cipher",
		map[string]interface{}{
			"NewCBCDecrypter": cipher.NewCBCDecrypter,
			"NewCBCEncrypter": cipher.NewCBCEncrypter,
			"NewCFBDecrypter": cipher.NewCFBDecrypter,
			"NewCFBEncrypter": cipher.NewCFBEncrypter,
			"NewCTR": cipher.NewCTR,
			"NewGCM": cipher.NewGCM,
			"NewGCMWithNonceSize": cipher.NewGCMWithNonceSize,
			"NewGCMWithTagSize": cipher.NewGCMWithTagSize,
			"NewOFB": cipher.NewOFB,
		},
	)
	registerType("crypto/cipher", "AEAD", reflect.TypeOf((*cipher.AEAD)(nil)).Elem())
	registerType("crypto/cipher", "Block", reflect.TypeOf((*cipher.Block)(nil)).Elem())
	registerType("crypto/cipher", "BlockMode", reflect.TypeOf((*cipher.BlockMode)(nil)).Elem())
	registerType("crypto/cipher", "Stream", reflect.TypeOf((*cipher.Stream)(nil)).Elem())
	registerType("crypto/cipher", "StreamReader", reflect.TypeOf((*cipher.StreamReader)(nil)).Elem())
	registerType("crypto/cipher", "StreamWriter", reflect.TypeOf((*cipher.StreamWriter)(nil)).Elem())
}

