// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: archive/tar

package microlisp

import (
	tar "archive/tar"
	"reflect"
)

func register_archive_tar() {
	registerPackage(
		"archive/tar",
		map[string]interface{}{
			"FileInfoHeader": tar.FileInfoHeader,
			"NewReader": tar.NewReader,
			"NewWriter": tar.NewWriter,
			"ErrFieldTooLong": tar.ErrFieldTooLong,
			"ErrHeader": tar.ErrHeader,
			"ErrInsecurePath": tar.ErrInsecurePath,
			"ErrWriteAfterClose": tar.ErrWriteAfterClose,
			"ErrWriteTooLong": tar.ErrWriteTooLong,
			"TypeBlock": tar.TypeBlock,
			"TypeChar": tar.TypeChar,
			"TypeCont": tar.TypeCont,
			"TypeDir": tar.TypeDir,
			"TypeFifo": tar.TypeFifo,
			"TypeGNULongLink": tar.TypeGNULongLink,
			"TypeGNULongName": tar.TypeGNULongName,
			"TypeGNUSparse": tar.TypeGNUSparse,
			"TypeLink": tar.TypeLink,
			"TypeReg": tar.TypeReg,
			"TypeRegA": tar.TypeRegA,
			"TypeSymlink": tar.TypeSymlink,
			"TypeXGlobalHeader": tar.TypeXGlobalHeader,
			"TypeXHeader": tar.TypeXHeader,
		},
	)
	registerType("archive/tar", "Format", reflect.TypeOf((*tar.Format)(nil)).Elem())
	registerType("archive/tar", "Header", reflect.TypeOf((*tar.Header)(nil)).Elem())
	registerType("archive/tar", "Reader", reflect.TypeOf((*tar.Reader)(nil)).Elem())
	registerType("archive/tar", "Writer", reflect.TypeOf((*tar.Writer)(nil)).Elem())
}

