// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/rpc/jsonrpc

package microlisp

import (
	jsonrpc "net/rpc/jsonrpc"
)

func register_net_rpc_jsonrpc() {
	registerPackage(
		"net/rpc/jsonrpc",
		map[string]interface{}{
			"Dial": jsonrpc.Dial,
			"NewClient": jsonrpc.NewClient,
			"NewClientCodec": jsonrpc.NewClientCodec,
			"NewServerCodec": jsonrpc.NewServerCodec,
			"ServeConn": jsonrpc.ServeConn,
		},
	)
}

