// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/http/httptrace

package microlisp

import (
	httptrace "net/http/httptrace"
	"reflect"
)

func register_net_http_httptrace() {
	registerPackage(
		"net/http/httptrace",
		map[string]interface{}{
			"ContextClientTrace": httptrace.ContextClientTrace,
			"WithClientTrace": httptrace.WithClientTrace,
		},
	)
	registerType("net/http/httptrace", "ClientTrace", reflect.TypeOf((*httptrace.ClientTrace)(nil)).Elem())
	registerType("net/http/httptrace", "DNSDoneInfo", reflect.TypeOf((*httptrace.DNSDoneInfo)(nil)).Elem())
	registerType("net/http/httptrace", "DNSStartInfo", reflect.TypeOf((*httptrace.DNSStartInfo)(nil)).Elem())
	registerType("net/http/httptrace", "GotConnInfo", reflect.TypeOf((*httptrace.GotConnInfo)(nil)).Elem())
	registerType("net/http/httptrace", "WroteRequestInfo", reflect.TypeOf((*httptrace.WroteRequestInfo)(nil)).Elem())
}

