// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto

package microlisp

import (
	crypto "crypto"
	"reflect"
)

func register_crypto() {
	registerPackage(
		"crypto",
		map[string]interface{}{
			"RegisterHash": crypto.RegisterHash,
			"BLAKE2b_256": crypto.BLAKE2b_256,
			"BLAKE2b_384": crypto.BLAKE2b_384,
			"BLAKE2b_512": crypto.BLAKE2b_512,
			"BLAKE2s_256": crypto.BLAKE2s_256,
			"MD4": crypto.MD4,
			"MD5": crypto.MD5,
			"MD5SHA1": crypto.MD5SHA1,
			"RIPEMD160": crypto.RIPEMD160,
			"SHA1": crypto.SHA1,
			"SHA224": crypto.SHA224,
			"SHA256": crypto.SHA256,
			"SHA384": crypto.SHA384,
			"SHA3_224": crypto.SHA3_224,
			"SHA3_256": crypto.SHA3_256,
			"SHA3_384": crypto.SHA3_384,
			"SHA3_512": crypto.SHA3_512,
			"SHA512": crypto.SHA512,
			"SHA512_224": crypto.SHA512_224,
			"SHA512_256": crypto.SHA512_256,
		},
	)
	registerType("crypto", "Decrypter", reflect.TypeOf((*crypto.Decrypter)(nil)).Elem())
	registerType("crypto", "DecrypterOpts", reflect.TypeOf((*crypto.DecrypterOpts)(nil)).Elem())
	registerType("crypto", "Hash", reflect.TypeOf((*crypto.Hash)(nil)).Elem())
	registerType("crypto", "PrivateKey", reflect.TypeOf((*crypto.PrivateKey)(nil)).Elem())
	registerType("crypto", "PublicKey", reflect.TypeOf((*crypto.PublicKey)(nil)).Elem())
	registerType("crypto", "Signer", reflect.TypeOf((*crypto.Signer)(nil)).Elem())
	registerType("crypto", "SignerOpts", reflect.TypeOf((*crypto.SignerOpts)(nil)).Elem())
}

