// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/url

package microlisp

import (
	url "net/url"
	"reflect"
)

func register_net_url() {
	registerPackage(
		"net/url",
		map[string]interface{}{
			"JoinPath": url.JoinPath,
			"Parse": url.Parse,
			"ParseQuery": url.ParseQuery,
			"ParseRequestURI": url.ParseRequestURI,
			"PathEscape": url.PathEscape,
			"PathUnescape": url.PathUnescape,
			"QueryEscape": url.QueryEscape,
			"QueryUnescape": url.QueryUnescape,
			"User": url.User,
			"UserPassword": url.UserPassword,
		},
	)
	registerType("net/url", "Error", reflect.TypeOf((*url.Error)(nil)).Elem())
	registerType("net/url", "EscapeError", reflect.TypeOf((*url.EscapeError)(nil)).Elem())
	registerType("net/url", "InvalidHostError", reflect.TypeOf((*url.InvalidHostError)(nil)).Elem())
	registerType("net/url", "URL", reflect.TypeOf((*url.URL)(nil)).Elem())
	registerType("net/url", "Userinfo", reflect.TypeOf((*url.Userinfo)(nil)).Elem())
	registerType("net/url", "Values", reflect.TypeOf((*url.Values)(nil)).Elem())
}

