// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/subtle

package microlisp

import (
	subtle "crypto/subtle"
)

func register_crypto_subtle() {
	registerPackage(
		"crypto/subtle",
		map[string]interface{}{
			"ConstantTimeByteEq": subtle.ConstantTimeByteEq,
			"ConstantTimeCompare": subtle.ConstantTimeCompare,
			"ConstantTimeCopy": subtle.ConstantTimeCopy,
			"ConstantTimeEq": subtle.ConstantTimeEq,
			"ConstantTimeLessOrEq": subtle.ConstantTimeLessOrEq,
			"ConstantTimeSelect": subtle.ConstantTimeSelect,
			"XORBytes": subtle.XORBytes,
		},
	)
}

