// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: image/png

package microlisp

import (
	png "image/png"
	"reflect"
)

func register_image_png() {
	registerPackage(
		"image/png",
		map[string]interface{}{
			"Decode": png.Decode,
			"DecodeConfig": png.DecodeConfig,
			"Encode": png.Encode,
			"BestCompression": png.BestCompression,
			"BestSpeed": png.BestSpeed,
			"DefaultCompression": png.DefaultCompression,
			"NoCompression": png.NoCompression,
		},
	)
	registerType("image/png", "CompressionLevel", reflect.TypeOf((*png.CompressionLevel)(nil)).Elem())
	registerType("image/png", "Encoder", reflect.TypeOf((*png.Encoder)(nil)).Elem())
	registerType("image/png", "EncoderBuffer", reflect.TypeOf((*png.EncoderBuffer)(nil)).Elem())
	registerType("image/png", "EncoderBufferPool", reflect.TypeOf((*png.EncoderBufferPool)(nil)).Elem())
	registerType("image/png", "FormatError", reflect.TypeOf((*png.FormatError)(nil)).Elem())
	registerType("image/png", "UnsupportedError", reflect.TypeOf((*png.UnsupportedError)(nil)).Elem())
}

