// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/textproto

package microlisp

import (
	textproto "net/textproto"
	"reflect"
)

func register_net_textproto() {
	registerPackage(
		"net/textproto",
		map[string]interface{}{
			"CanonicalMIMEHeaderKey": textproto.CanonicalMIMEHeaderKey,
			"Dial": textproto.Dial,
			"NewConn": textproto.NewConn,
			"NewReader": textproto.NewReader,
			"NewWriter": textproto.NewWriter,
			"TrimBytes": textproto.TrimBytes,
			"TrimString": textproto.TrimString,
		},
	)
	registerType("net/textproto", "Conn", reflect.TypeOf((*textproto.Conn)(nil)).Elem())
	registerType("net/textproto", "Error", reflect.TypeOf((*textproto.Error)(nil)).Elem())
	registerType("net/textproto", "MIMEHeader", reflect.TypeOf((*textproto.MIMEHeader)(nil)).Elem())
	registerType("net/textproto", "Pipeline", reflect.TypeOf((*textproto.Pipeline)(nil)).Elem())
	registerType("net/textproto", "ProtocolError", reflect.TypeOf((*textproto.ProtocolError)(nil)).Elem())
	registerType("net/textproto", "Reader", reflect.TypeOf((*textproto.Reader)(nil)).Elem())
	registerType("net/textproto", "Writer", reflect.TypeOf((*textproto.Writer)(nil)).Elem())
}

