// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: regexp/syntax

package microlisp

import (
	syntax "regexp/syntax"
	"reflect"
)

func register_regexp_syntax() {
	registerPackage(
		"regexp/syntax",
		map[string]interface{}{
			"Compile": syntax.Compile,
			"EmptyOpContext": syntax.EmptyOpContext,
			"IsWordChar": syntax.IsWordChar,
			"Parse": syntax.Parse,
			"ClassNL": syntax.ClassNL,
			"DotNL": syntax.DotNL,
			"EmptyBeginLine": syntax.EmptyBeginLine,
			"EmptyBeginText": syntax.EmptyBeginText,
			"EmptyEndLine": syntax.EmptyEndLine,
			"EmptyEndText": syntax.EmptyEndText,
			"EmptyNoWordBoundary": syntax.EmptyNoWordBoundary,
			"EmptyWordBoundary": syntax.EmptyWordBoundary,
			"ErrInternalError": syntax.ErrInternalError,
			"ErrInvalidCharClass": syntax.ErrInvalidCharClass,
			"ErrInvalidCharRange": syntax.ErrInvalidCharRange,
			"ErrInvalidEscape": syntax.ErrInvalidEscape,
			"ErrInvalidNamedCapture": syntax.ErrInvalidNamedCapture,
			"ErrInvalidPerlOp": syntax.ErrInvalidPerlOp,
			"ErrInvalidRepeatOp": syntax.ErrInvalidRepeatOp,
			"ErrInvalidRepeatSize": syntax.ErrInvalidRepeatSize,
			"ErrInvalidUTF8": syntax.ErrInvalidUTF8,
			"ErrLarge": syntax.ErrLarge,
			"ErrMissingBracket": syntax.ErrMissingBracket,
			"ErrMissingParen": syntax.ErrMissingParen,
			"ErrMissingRepeatArgument": syntax.ErrMissingRepeatArgument,
			"ErrNestingDepth": syntax.ErrNestingDepth,
			"ErrTrailingBackslash": syntax.ErrTrailingBackslash,
			"ErrUnexpectedParen": syntax.ErrUnexpectedParen,
			"FoldCase": syntax.FoldCase,
			"InstAlt": syntax.InstAlt,
			"InstAltMatch": syntax.InstAltMatch,
			"InstCapture": syntax.InstCapture,
			"InstEmptyWidth": syntax.InstEmptyWidth,
			"InstFail": syntax.InstFail,
			"InstMatch": syntax.InstMatch,
			"InstNop": syntax.InstNop,
			"InstRune": syntax.InstRune,
			"InstRune1": syntax.InstRune1,
			"InstRuneAny": syntax.InstRuneAny,
			"InstRuneAnyNotNL": syntax.InstRuneAnyNotNL,
			"Literal": syntax.Literal,
			"MatchNL": syntax.MatchNL,
			"NonGreedy": syntax.NonGreedy,
			"OneLine": syntax.OneLine,
			"OpAlternate": syntax.OpAlternate,
			"OpAnyChar": syntax.OpAnyChar,
			"OpAnyCharNotNL": syntax.OpAnyCharNotNL,
			"OpBeginLine": syntax.OpBeginLine,
			"OpBeginText": syntax.OpBeginText,
			"OpCapture": syntax.OpCapture,
			"OpCharClass": syntax.OpCharClass,
			"OpConcat": syntax.OpConcat,
			"OpEmptyMatch": syntax.OpEmptyMatch,
			"OpEndLine": syntax.OpEndLine,
			"OpEndText": syntax.OpEndText,
			"OpLiteral": syntax.OpLiteral,
			"OpNoMatch": syntax.OpNoMatch,
			"OpNoWordBoundary": syntax.OpNoWordBoundary,
			"OpPlus": syntax.OpPlus,
			"OpQuest": syntax.OpQuest,
			"OpRepeat": syntax.OpRepeat,
			"OpStar": syntax.OpStar,
			"OpWordBoundary": syntax.OpWordBoundary,
			"POSIX": syntax.POSIX,
			"Perl": syntax.Perl,
			"PerlX": syntax.PerlX,
			"Simple": syntax.Simple,
			"UnicodeGroups": syntax.UnicodeGroups,
			"WasDollar": syntax.WasDollar,
		},
	)
	registerType("regexp/syntax", "EmptyOp", reflect.TypeOf((*syntax.EmptyOp)(nil)).Elem())
	registerType("regexp/syntax", "Error", reflect.TypeOf((*syntax.Error)(nil)).Elem())
	registerType("regexp/syntax", "ErrorCode", reflect.TypeOf((*syntax.ErrorCode)(nil)).Elem())
	registerType("regexp/syntax", "Flags", reflect.TypeOf((*syntax.Flags)(nil)).Elem())
	registerType("regexp/syntax", "Inst", reflect.TypeOf((*syntax.Inst)(nil)).Elem())
	registerType("regexp/syntax", "InstOp", reflect.TypeOf((*syntax.InstOp)(nil)).Elem())
	registerType("regexp/syntax", "Op", reflect.TypeOf((*syntax.Op)(nil)).Elem())
	registerType("regexp/syntax", "Prog", reflect.TypeOf((*syntax.Prog)(nil)).Elem())
	registerType("regexp/syntax", "Regexp", reflect.TypeOf((*syntax.Regexp)(nil)).Elem())
}

