// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/elliptic

package microlisp

import (
	elliptic "crypto/elliptic"
	"reflect"
)

func register_crypto_elliptic() {
	registerPackage(
		"crypto/elliptic",
		map[string]interface{}{
			"GenerateKey": elliptic.GenerateKey,
			"Marshal": elliptic.Marshal,
			"MarshalCompressed": elliptic.MarshalCompressed,
			"P224": elliptic.P224,
			"P256": elliptic.P256,
			"P384": elliptic.P384,
			"P521": elliptic.P521,
			"Unmarshal": elliptic.Unmarshal,
			"UnmarshalCompressed": elliptic.UnmarshalCompressed,
		},
	)
	registerType("crypto/elliptic", "Curve", reflect.TypeOf((*elliptic.Curve)(nil)).Elem())
	registerType("crypto/elliptic", "CurveParams", reflect.TypeOf((*elliptic.CurveParams)(nil)).Elem())
}

