// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/build

package microlisp

import (
	build "go/build"
	"reflect"
)

func register_go_build() {
	registerPackage(
		"go/build",
		map[string]interface{}{
			"ArchChar": build.ArchChar,
			"Import": build.Import,
			"ImportDir": build.ImportDir,
			"IsLocalImport": build.IsLocalImport,
			"Default": build.Default,
			"ToolDir": build.ToolDir,
		},
	)
	registerType("go/build", "Context", reflect.TypeOf((*build.Context)(nil)).Elem())
	registerType("go/build", "Directive", reflect.TypeOf((*build.Directive)(nil)).Elem())
	registerType("go/build", "ImportMode", reflect.TypeOf((*build.ImportMode)(nil)).Elem())
	registerType("go/build", "MultiplePackageError", reflect.TypeOf((*build.MultiplePackageError)(nil)).Elem())
	registerType("go/build", "NoGoError", reflect.TypeOf((*build.NoGoError)(nil)).Elem())
	registerType("go/build", "Package", reflect.TypeOf((*build.Package)(nil)).Elem())
}

