// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/ecdsa

package microlisp

import (
	ecdsa "crypto/ecdsa"
	"reflect"
)

func register_crypto_ecdsa() {
	registerPackage(
		"crypto/ecdsa",
		map[string]interface{}{
			"GenerateKey": ecdsa.GenerateKey,
			"Sign": ecdsa.Sign,
			"SignASN1": ecdsa.SignASN1,
			"Verify": ecdsa.Verify,
			"VerifyASN1": ecdsa.VerifyASN1,
		},
	)
	registerType("crypto/ecdsa", "PrivateKey", reflect.TypeOf((*ecdsa.PrivateKey)(nil)).Elem())
	registerType("crypto/ecdsa", "PublicKey", reflect.TypeOf((*ecdsa.PublicKey)(nil)).Elem())
}

