// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/http/httputil

package microlisp

import (
	httputil "net/http/httputil"
	"reflect"
)

func register_net_http_httputil() {
	registerPackage(
		"net/http/httputil",
		map[string]interface{}{
			"DumpRequest": httputil.DumpRequest,
			"DumpRequestOut": httputil.DumpRequestOut,
			"DumpResponse": httputil.DumpResponse,
			"NewChunkedReader": httputil.NewChunkedReader,
			"NewChunkedWriter": httputil.NewChunkedWriter,
			"NewClientConn": httputil.NewClientConn,
			"NewProxyClientConn": httputil.NewProxyClientConn,
			"NewServerConn": httputil.NewServerConn,
			"NewSingleHostReverseProxy": httputil.NewSingleHostReverseProxy,
			"ErrClosed": httputil.ErrClosed,
			"ErrLineTooLong": httputil.ErrLineTooLong,
			"ErrPersistEOF": httputil.ErrPersistEOF,
			"ErrPipeline": httputil.ErrPipeline,
		},
	)
	registerType("net/http/httputil", "BufferPool", reflect.TypeOf((*httputil.BufferPool)(nil)).Elem())
	registerType("net/http/httputil", "ClientConn", reflect.TypeOf((*httputil.ClientConn)(nil)).Elem())
	registerType("net/http/httputil", "ProxyRequest", reflect.TypeOf((*httputil.ProxyRequest)(nil)).Elem())
	registerType("net/http/httputil", "ReverseProxy", reflect.TypeOf((*httputil.ReverseProxy)(nil)).Elem())
	registerType("net/http/httputil", "ServerConn", reflect.TypeOf((*httputil.ServerConn)(nil)).Elem())
}

