// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: debug/dwarf

package microlisp

import (
	dwarf "debug/dwarf"
	"reflect"
)

func register_debug_dwarf() {
	registerPackage(
		"debug/dwarf",
		map[string]interface{}{
			"New": dwarf.New,
			"ErrUnknownPC": dwarf.ErrUnknownPC,
		},
	)
	registerType("debug/dwarf", "AddrType", reflect.TypeOf((*dwarf.AddrType)(nil)).Elem())
	registerType("debug/dwarf", "ArrayType", reflect.TypeOf((*dwarf.ArrayType)(nil)).Elem())
	registerType("debug/dwarf", "Attr", reflect.TypeOf((*dwarf.Attr)(nil)).Elem())
	registerType("debug/dwarf", "BasicType", reflect.TypeOf((*dwarf.BasicType)(nil)).Elem())
	registerType("debug/dwarf", "BoolType", reflect.TypeOf((*dwarf.BoolType)(nil)).Elem())
	registerType("debug/dwarf", "CharType", reflect.TypeOf((*dwarf.CharType)(nil)).Elem())
	registerType("debug/dwarf", "Class", reflect.TypeOf((*dwarf.Class)(nil)).Elem())
	registerType("debug/dwarf", "CommonType", reflect.TypeOf((*dwarf.CommonType)(nil)).Elem())
	registerType("debug/dwarf", "ComplexType", reflect.TypeOf((*dwarf.ComplexType)(nil)).Elem())
	registerType("debug/dwarf", "Data", reflect.TypeOf((*dwarf.Data)(nil)).Elem())
	registerType("debug/dwarf", "DecodeError", reflect.TypeOf((*dwarf.DecodeError)(nil)).Elem())
	registerType("debug/dwarf", "DotDotDotType", reflect.TypeOf((*dwarf.DotDotDotType)(nil)).Elem())
	registerType("debug/dwarf", "Entry", reflect.TypeOf((*dwarf.Entry)(nil)).Elem())
	registerType("debug/dwarf", "EnumType", reflect.TypeOf((*dwarf.EnumType)(nil)).Elem())
	registerType("debug/dwarf", "EnumValue", reflect.TypeOf((*dwarf.EnumValue)(nil)).Elem())
	registerType("debug/dwarf", "Field", reflect.TypeOf((*dwarf.Field)(nil)).Elem())
	registerType("debug/dwarf", "FloatType", reflect.TypeOf((*dwarf.FloatType)(nil)).Elem())
	registerType("debug/dwarf", "FuncType", reflect.TypeOf((*dwarf.FuncType)(nil)).Elem())
	registerType("debug/dwarf", "IntType", reflect.TypeOf((*dwarf.IntType)(nil)).Elem())
	registerType("debug/dwarf", "LineEntry", reflect.TypeOf((*dwarf.LineEntry)(nil)).Elem())
	registerType("debug/dwarf", "LineFile", reflect.TypeOf((*dwarf.LineFile)(nil)).Elem())
	registerType("debug/dwarf", "LineReader", reflect.TypeOf((*dwarf.LineReader)(nil)).Elem())
	registerType("debug/dwarf", "LineReaderPos", reflect.TypeOf((*dwarf.LineReaderPos)(nil)).Elem())
	registerType("debug/dwarf", "Offset", reflect.TypeOf((*dwarf.Offset)(nil)).Elem())
	registerType("debug/dwarf", "PtrType", reflect.TypeOf((*dwarf.PtrType)(nil)).Elem())
	registerType("debug/dwarf", "QualType", reflect.TypeOf((*dwarf.QualType)(nil)).Elem())
	registerType("debug/dwarf", "Reader", reflect.TypeOf((*dwarf.Reader)(nil)).Elem())
	registerType("debug/dwarf", "StructField", reflect.TypeOf((*dwarf.StructField)(nil)).Elem())
	registerType("debug/dwarf", "StructType", reflect.TypeOf((*dwarf.StructType)(nil)).Elem())
	registerType("debug/dwarf", "Tag", reflect.TypeOf((*dwarf.Tag)(nil)).Elem())
	registerType("debug/dwarf", "Type", reflect.TypeOf((*dwarf.Type)(nil)).Elem())
	registerType("debug/dwarf", "TypedefType", reflect.TypeOf((*dwarf.TypedefType)(nil)).Elem())
	registerType("debug/dwarf", "UcharType", reflect.TypeOf((*dwarf.UcharType)(nil)).Elem())
	registerType("debug/dwarf", "UintType", reflect.TypeOf((*dwarf.UintType)(nil)).Elem())
	registerType("debug/dwarf", "UnspecifiedType", reflect.TypeOf((*dwarf.UnspecifiedType)(nil)).Elem())
	registerType("debug/dwarf", "UnsupportedType", reflect.TypeOf((*dwarf.UnsupportedType)(nil)).Elem())
	registerType("debug/dwarf", "VoidType", reflect.TypeOf((*dwarf.VoidType)(nil)).Elem())
}

