// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: reflect

package microlisp

import (
	reflectPkg "reflect"
)

func register_reflect() {
	registerPackage(
		"reflect",
		map[string]interface{}{
			"Append": reflectPkg.Append,
			"AppendSlice": reflectPkg.AppendSlice,
			"ArrayOf": reflectPkg.ArrayOf,
			"ChanOf": reflectPkg.ChanOf,
			"Copy": reflectPkg.Copy,
			"DeepEqual": reflectPkg.DeepEqual,
			"FuncOf": reflectPkg.FuncOf,
			"Indirect": reflectPkg.Indirect,
			"MakeChan": reflectPkg.MakeChan,
			"MakeFunc": reflectPkg.MakeFunc,
			"MakeMap": reflectPkg.MakeMap,
			"MakeMapWithSize": reflectPkg.MakeMapWithSize,
			"MakeSlice": reflectPkg.MakeSlice,
			"MapOf": reflectPkg.MapOf,
			"New": reflectPkg.New,
			"NewAt": reflectPkg.NewAt,
			"PointerTo": reflectPkg.PointerTo,
			"PtrTo": reflectPkg.PtrTo,
			"Select": reflectPkg.Select,
			"SliceOf": reflectPkg.SliceOf,
			"StructOf": reflectPkg.StructOf,
			"Swapper": reflectPkg.Swapper,
			"TypeOf": reflectPkg.TypeOf,
			"ValueOf": reflectPkg.ValueOf,
			"VisibleFields": reflectPkg.VisibleFields,
			"Zero": reflectPkg.Zero,
		},
	)
}

