// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: math/big

package microlisp

import (
	big "math/big"
	"reflect"
)

func register_math_big() {
	registerPackage(
		"math/big",
		map[string]interface{}{
			"Jacobi": big.Jacobi,
			"NewFloat": big.NewFloat,
			"NewInt": big.NewInt,
			"NewRat": big.NewRat,
			"ParseFloat": big.ParseFloat,
			"Above": big.Above,
			"AwayFromZero": big.AwayFromZero,
			"Below": big.Below,
			"Exact": big.Exact,
			"MaxBase": big.MaxBase,
			"MaxExp": big.MaxExp,
			"MaxPrec": uint(big.MaxPrec),
			"MinExp": big.MinExp,
			"ToNearestAway": big.ToNearestAway,
			"ToNearestEven": big.ToNearestEven,
			"ToNegativeInf": big.ToNegativeInf,
			"ToPositiveInf": big.ToPositiveInf,
			"ToZero": big.ToZero,
		},
	)
	registerType("math/big", "Accuracy", reflect.TypeOf((*big.Accuracy)(nil)).Elem())
	registerType("math/big", "ErrNaN", reflect.TypeOf((*big.ErrNaN)(nil)).Elem())
	registerType("math/big", "Float", reflect.TypeOf((*big.Float)(nil)).Elem())
	registerType("math/big", "Int", reflect.TypeOf((*big.Int)(nil)).Elem())
	registerType("math/big", "Rat", reflect.TypeOf((*big.Rat)(nil)).Elem())
	registerType("math/big", "RoundingMode", reflect.TypeOf((*big.RoundingMode)(nil)).Elem())
	registerType("math/big", "Word", reflect.TypeOf((*big.Word)(nil)).Elem())
}

