// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: image/jpeg

package microlisp

import (
	jpeg "image/jpeg"
	"reflect"
)

func register_image_jpeg() {
	registerPackage(
		"image/jpeg",
		map[string]interface{}{
			"Decode": jpeg.Decode,
			"DecodeConfig": jpeg.DecodeConfig,
			"Encode": jpeg.Encode,
			"DefaultQuality": jpeg.DefaultQuality,
		},
	)
	registerType("image/jpeg", "FormatError", reflect.TypeOf((*jpeg.FormatError)(nil)).Elem())
	registerType("image/jpeg", "Options", reflect.TypeOf((*jpeg.Options)(nil)).Elem())
	registerType("image/jpeg", "Reader", reflect.TypeOf((*jpeg.Reader)(nil)).Elem())
	registerType("image/jpeg", "UnsupportedError", reflect.TypeOf((*jpeg.UnsupportedError)(nil)).Elem())
}

