// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: container/heap

package microlisp

import (
	heap "container/heap"
	"reflect"
)

func register_container_heap() {
	registerPackage(
		"container/heap",
		map[string]interface{}{
			"Fix": heap.Fix,
			"Init": heap.Init,
			"Pop": heap.Pop,
			"Push": heap.Push,
			"Remove": heap.Remove,
		},
	)
	registerType("container/heap", "Interface", reflect.TypeOf((*heap.Interface)(nil)).Elem())
}

