// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: text/tabwriter

package microlisp

import (
	tabwriter "text/tabwriter"
	"reflect"
)

func register_text_tabwriter() {
	registerPackage(
		"text/tabwriter",
		map[string]interface{}{
			"NewWriter": tabwriter.NewWriter,
			"AlignRight": tabwriter.AlignRight,
			"Debug": tabwriter.Debug,
			"DiscardEmptyColumns": tabwriter.DiscardEmptyColumns,
			"Escape": tabwriter.Escape,
			"FilterHTML": tabwriter.FilterHTML,
			"StripEscape": tabwriter.StripEscape,
			"TabIndent": tabwriter.TabIndent,
		},
	)
	registerType("text/tabwriter", "Writer", reflect.TypeOf((*tabwriter.Writer)(nil)).Elem())
}

