// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/http

package microlisp

import (
	http "net/http"
	"reflect"
)

func register_net_http() {
	registerPackage(
		"net/http",
		map[string]interface{}{
			"AllowQuerySemicolons": http.AllowQuerySemicolons,
			"CanonicalHeaderKey": http.CanonicalHeaderKey,
			"DetectContentType": http.DetectContentType,
			"Error": http.Error,
			"FS": http.FS,
			"FileServer": http.FileServer,
			"Get": http.Get,
			"Handle": http.Handle,
			"HandleFunc": http.HandleFunc,
			"Head": http.Head,
			"ListenAndServe": http.ListenAndServe,
			"ListenAndServeTLS": http.ListenAndServeTLS,
			"MaxBytesHandler": http.MaxBytesHandler,
			"MaxBytesReader": http.MaxBytesReader,
			"NewFileTransport": http.NewFileTransport,
			"NewRequest": http.NewRequest,
			"NewRequestWithContext": http.NewRequestWithContext,
			"NewResponseController": http.NewResponseController,
			"NewServeMux": http.NewServeMux,
			"NotFound": http.NotFound,
			"NotFoundHandler": http.NotFoundHandler,
			"ParseHTTPVersion": http.ParseHTTPVersion,
			"ParseTime": http.ParseTime,
			"Post": http.Post,
			"PostForm": http.PostForm,
			"ProxyFromEnvironment": http.ProxyFromEnvironment,
			"ProxyURL": http.ProxyURL,
			"ReadRequest": http.ReadRequest,
			"ReadResponse": http.ReadResponse,
			"Redirect": http.Redirect,
			"RedirectHandler": http.RedirectHandler,
			"Serve": http.Serve,
			"ServeContent": http.ServeContent,
			"ServeFile": http.ServeFile,
			"ServeTLS": http.ServeTLS,
			"SetCookie": http.SetCookie,
			"StatusText": http.StatusText,
			"StripPrefix": http.StripPrefix,
			"TimeoutHandler": http.TimeoutHandler,
			"DefaultClient": http.DefaultClient,
			"DefaultServeMux": http.DefaultServeMux,
			"DefaultTransport": http.DefaultTransport,
			"ErrAbortHandler": http.ErrAbortHandler,
			"ErrBodyNotAllowed": http.ErrBodyNotAllowed,
			"ErrBodyReadAfterClose": http.ErrBodyReadAfterClose,
			"ErrContentLength": http.ErrContentLength,
			"ErrHandlerTimeout": http.ErrHandlerTimeout,
			"ErrHeaderTooLong": http.ErrHeaderTooLong,
			"ErrHijacked": http.ErrHijacked,
			"ErrLineTooLong": http.ErrLineTooLong,
			"ErrMissingBoundary": http.ErrMissingBoundary,
			"ErrMissingContentLength": http.ErrMissingContentLength,
			"ErrMissingFile": http.ErrMissingFile,
			"ErrNoCookie": http.ErrNoCookie,
			"ErrNoLocation": http.ErrNoLocation,
			"ErrNotMultipart": http.ErrNotMultipart,
			"ErrNotSupported": http.ErrNotSupported,
			"ErrSchemeMismatch": http.ErrSchemeMismatch,
			"ErrServerClosed": http.ErrServerClosed,
			"ErrShortBody": http.ErrShortBody,
			"ErrSkipAltProtocol": http.ErrSkipAltProtocol,
			"ErrUnexpectedTrailer": http.ErrUnexpectedTrailer,
			"ErrUseLastResponse": http.ErrUseLastResponse,
			"ErrWriteAfterFlush": http.ErrWriteAfterFlush,
			"LocalAddrContextKey": http.LocalAddrContextKey,
			"NoBody": http.NoBody,
			"ServerContextKey": http.ServerContextKey,
			"DefaultMaxHeaderBytes": http.DefaultMaxHeaderBytes,
			"DefaultMaxIdleConnsPerHost": http.DefaultMaxIdleConnsPerHost,
			"MethodConnect": http.MethodConnect,
			"MethodDelete": http.MethodDelete,
			"MethodGet": http.MethodGet,
			"MethodHead": http.MethodHead,
			"MethodOptions": http.MethodOptions,
			"MethodPatch": http.MethodPatch,
			"MethodPost": http.MethodPost,
			"MethodPut": http.MethodPut,
			"MethodTrace": http.MethodTrace,
			"StatusAccepted": http.StatusAccepted,
			"StatusAlreadyReported": http.StatusAlreadyReported,
			"StatusBadGateway": http.StatusBadGateway,
			"StatusBadRequest": http.StatusBadRequest,
			"StatusConflict": http.StatusConflict,
			"StatusContinue": http.StatusContinue,
			"StatusCreated": http.StatusCreated,
			"StatusEarlyHints": http.StatusEarlyHints,
			"StatusExpectationFailed": http.StatusExpectationFailed,
			"StatusFailedDependency": http.StatusFailedDependency,
			"StatusForbidden": http.StatusForbidden,
			"StatusFound": http.StatusFound,
			"StatusGatewayTimeout": http.StatusGatewayTimeout,
			"StatusGone": http.StatusGone,
			"StatusHTTPVersionNotSupported": http.StatusHTTPVersionNotSupported,
			"StatusIMUsed": http.StatusIMUsed,
			"StatusInsufficientStorage": http.StatusInsufficientStorage,
			"StatusInternalServerError": http.StatusInternalServerError,
			"StatusLengthRequired": http.StatusLengthRequired,
			"StatusLocked": http.StatusLocked,
			"StatusLoopDetected": http.StatusLoopDetected,
			"StatusMethodNotAllowed": http.StatusMethodNotAllowed,
			"StatusMisdirectedRequest": http.StatusMisdirectedRequest,
			"StatusMovedPermanently": http.StatusMovedPermanently,
			"StatusMultiStatus": http.StatusMultiStatus,
			"StatusMultipleChoices": http.StatusMultipleChoices,
			"StatusNetworkAuthenticationRequired": http.StatusNetworkAuthenticationRequired,
			"StatusNoContent": http.StatusNoContent,
			"StatusNonAuthoritativeInfo": http.StatusNonAuthoritativeInfo,
			"StatusNotAcceptable": http.StatusNotAcceptable,
			"StatusNotExtended": http.StatusNotExtended,
			"StatusNotFound": http.StatusNotFound,
			"StatusNotImplemented": http.StatusNotImplemented,
			"StatusNotModified": http.StatusNotModified,
			"StatusOK": http.StatusOK,
			"StatusPartialContent": http.StatusPartialContent,
			"StatusPaymentRequired": http.StatusPaymentRequired,
			"StatusPermanentRedirect": http.StatusPermanentRedirect,
			"StatusPreconditionFailed": http.StatusPreconditionFailed,
			"StatusPreconditionRequired": http.StatusPreconditionRequired,
			"StatusProcessing": http.StatusProcessing,
			"StatusProxyAuthRequired": http.StatusProxyAuthRequired,
			"StatusRequestEntityTooLarge": http.StatusRequestEntityTooLarge,
			"StatusRequestHeaderFieldsTooLarge": http.StatusRequestHeaderFieldsTooLarge,
			"StatusRequestTimeout": http.StatusRequestTimeout,
			"StatusRequestURITooLong": http.StatusRequestURITooLong,
			"StatusRequestedRangeNotSatisfiable": http.StatusRequestedRangeNotSatisfiable,
			"StatusResetContent": http.StatusResetContent,
			"StatusSeeOther": http.StatusSeeOther,
			"StatusServiceUnavailable": http.StatusServiceUnavailable,
			"StatusSwitchingProtocols": http.StatusSwitchingProtocols,
			"StatusTeapot": http.StatusTeapot,
			"StatusTemporaryRedirect": http.StatusTemporaryRedirect,
			"StatusTooEarly": http.StatusTooEarly,
			"StatusTooManyRequests": http.StatusTooManyRequests,
			"StatusUnauthorized": http.StatusUnauthorized,
			"StatusUnavailableForLegalReasons": http.StatusUnavailableForLegalReasons,
			"StatusUnprocessableEntity": http.StatusUnprocessableEntity,
			"StatusUnsupportedMediaType": http.StatusUnsupportedMediaType,
			"StatusUpgradeRequired": http.StatusUpgradeRequired,
			"StatusUseProxy": http.StatusUseProxy,
			"StatusVariantAlsoNegotiates": http.StatusVariantAlsoNegotiates,
			"TimeFormat": http.TimeFormat,
			"TrailerPrefix": http.TrailerPrefix,
		},
	)
	registerType("net/http", "Client", reflect.TypeOf((*http.Client)(nil)).Elem())
	registerType("net/http", "CloseNotifier", reflect.TypeOf((*http.CloseNotifier)(nil)).Elem())
	registerType("net/http", "ConnState", reflect.TypeOf((*http.ConnState)(nil)).Elem())
	registerType("net/http", "Cookie", reflect.TypeOf((*http.Cookie)(nil)).Elem())
	registerType("net/http", "CookieJar", reflect.TypeOf((*http.CookieJar)(nil)).Elem())
	registerType("net/http", "Dir", reflect.TypeOf((*http.Dir)(nil)).Elem())
	registerType("net/http", "File", reflect.TypeOf((*http.File)(nil)).Elem())
	registerType("net/http", "FileSystem", reflect.TypeOf((*http.FileSystem)(nil)).Elem())
	registerType("net/http", "Flusher", reflect.TypeOf((*http.Flusher)(nil)).Elem())
	registerType("net/http", "Handler", reflect.TypeOf((*http.Handler)(nil)).Elem())
	registerType("net/http", "HandlerFunc", reflect.TypeOf((*http.HandlerFunc)(nil)).Elem())
	registerType("net/http", "Header", reflect.TypeOf((*http.Header)(nil)).Elem())
	registerType("net/http", "Hijacker", reflect.TypeOf((*http.Hijacker)(nil)).Elem())
	registerType("net/http", "MaxBytesError", reflect.TypeOf((*http.MaxBytesError)(nil)).Elem())
	registerType("net/http", "ProtocolError", reflect.TypeOf((*http.ProtocolError)(nil)).Elem())
	registerType("net/http", "PushOptions", reflect.TypeOf((*http.PushOptions)(nil)).Elem())
	registerType("net/http", "Pusher", reflect.TypeOf((*http.Pusher)(nil)).Elem())
	registerType("net/http", "Request", reflect.TypeOf((*http.Request)(nil)).Elem())
	registerType("net/http", "Response", reflect.TypeOf((*http.Response)(nil)).Elem())
	registerType("net/http", "ResponseController", reflect.TypeOf((*http.ResponseController)(nil)).Elem())
	registerType("net/http", "ResponseWriter", reflect.TypeOf((*http.ResponseWriter)(nil)).Elem())
	registerType("net/http", "RoundTripper", reflect.TypeOf((*http.RoundTripper)(nil)).Elem())
	registerType("net/http", "SameSite", reflect.TypeOf((*http.SameSite)(nil)).Elem())
	registerType("net/http", "ServeMux", reflect.TypeOf((*http.ServeMux)(nil)).Elem())
	registerType("net/http", "Server", reflect.TypeOf((*http.Server)(nil)).Elem())
	registerType("net/http", "Transport", reflect.TypeOf((*http.Transport)(nil)).Elem())
}

