// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/format

package microlisp

import (
	format "go/format"
)

func register_go_format() {
	registerPackage(
		"go/format",
		map[string]interface{}{
			"Node": format.Node,
			"Source": format.Source,
		},
	)
}

