// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: unicode/utf16

package microlisp

import (
	utf16 "unicode/utf16"
)

func register_unicode_utf16() {
	registerPackage(
		"unicode/utf16",
		map[string]interface{}{
			"AppendRune": utf16.AppendRune,
			"Decode": utf16.Decode,
			"DecodeRune": utf16.DecodeRune,
			"Encode": utf16.Encode,
			"EncodeRune": utf16.EncodeRune,
			"IsSurrogate": utf16.IsSurrogate,
		},
	)
}

