// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/hmac

package microlisp

import (
	hmac "crypto/hmac"
)

func register_crypto_hmac() {
	registerPackage(
		"crypto/hmac",
		map[string]interface{}{
			"Equal": hmac.Equal,
			"New": hmac.New,
		},
	)
}

