// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: image/color/palette

package microlisp

import (
	palette "image/color/palette"
)

func register_image_color_palette() {
	registerPackage(
		"image/color/palette",
		map[string]interface{}{
			"Plan9": palette.Plan9,
			"WebSafe": palette.WebSafe,
		},
	)
}

