// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/pem

package microlisp

import (
	pem "encoding/pem"
	"reflect"
)

func register_encoding_pem() {
	registerPackage(
		"encoding/pem",
		map[string]interface{}{
			"Decode": pem.Decode,
			"Encode": pem.Encode,
			"EncodeToMemory": pem.EncodeToMemory,
		},
	)
	registerType("encoding/pem", "Block", reflect.TypeOf((*pem.Block)(nil)).Elem())
}

