// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: runtime/debug

package microlisp

import (
	debug "runtime/debug"
	"reflect"
)

func register_runtime_debug() {
	registerPackage(
		"runtime/debug",
		map[string]interface{}{
			"FreeOSMemory": debug.FreeOSMemory,
			"ParseBuildInfo": debug.ParseBuildInfo,
			"PrintStack": debug.PrintStack,
			"ReadBuildInfo": debug.ReadBuildInfo,
			"ReadGCStats": debug.ReadGCStats,
			"SetGCPercent": debug.SetGCPercent,
			"SetMaxStack": debug.SetMaxStack,
			"SetMaxThreads": debug.SetMaxThreads,
			"SetMemoryLimit": debug.SetMemoryLimit,
			"SetPanicOnFault": debug.SetPanicOnFault,
			"SetTraceback": debug.SetTraceback,
			"Stack": debug.Stack,
			"WriteHeapDump": debug.WriteHeapDump,
		},
	)
	registerType("runtime/debug", "BuildInfo", reflect.TypeOf((*debug.BuildInfo)(nil)).Elem())
	registerType("runtime/debug", "BuildSetting", reflect.TypeOf((*debug.BuildSetting)(nil)).Elem())
	registerType("runtime/debug", "GCStats", reflect.TypeOf((*debug.GCStats)(nil)).Elem())
	registerType("runtime/debug", "Module", reflect.TypeOf((*debug.Module)(nil)).Elem())
}

