// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/base64

package microlisp

import (
	base64 "encoding/base64"
	"reflect"
)

func register_encoding_base64() {
	registerPackage(
		"encoding/base64",
		map[string]interface{}{
			"NewDecoder": base64.NewDecoder,
			"NewEncoder": base64.NewEncoder,
			"NewEncoding": base64.NewEncoding,
			"RawStdEncoding": base64.RawStdEncoding,
			"RawURLEncoding": base64.RawURLEncoding,
			"StdEncoding": base64.StdEncoding,
			"URLEncoding": base64.URLEncoding,
			"NoPadding": base64.NoPadding,
			"StdPadding": base64.StdPadding,
		},
	)
	registerType("encoding/base64", "CorruptInputError", reflect.TypeOf((*base64.CorruptInputError)(nil)).Elem())
	registerType("encoding/base64", "Encoding", reflect.TypeOf((*base64.Encoding)(nil)).Elem())
}

