// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/doc

package microlisp

import (
	doc "go/doc"
	"reflect"
)

func register_go_doc() {
	registerPackage(
		"go/doc",
		map[string]interface{}{
			"Examples": doc.Examples,
			"IsPredeclared": doc.IsPredeclared,
			"New": doc.New,
			"NewFromFiles": doc.NewFromFiles,
			"Synopsis": doc.Synopsis,
			"ToHTML": doc.ToHTML,
			"ToText": doc.ToText,
			"IllegalPrefixes": doc.IllegalPrefixes,
		},
	)
	registerType("go/doc", "Example", reflect.TypeOf((*doc.Example)(nil)).Elem())
	registerType("go/doc", "Filter", reflect.TypeOf((*doc.Filter)(nil)).Elem())
	registerType("go/doc", "Func", reflect.TypeOf((*doc.Func)(nil)).Elem())
	registerType("go/doc", "Mode", reflect.TypeOf((*doc.Mode)(nil)).Elem())
	registerType("go/doc", "Note", reflect.TypeOf((*doc.Note)(nil)).Elem())
	registerType("go/doc", "Package", reflect.TypeOf((*doc.Package)(nil)).Elem())
	registerType("go/doc", "Type", reflect.TypeOf((*doc.Type)(nil)).Elem())
	registerType("go/doc", "Value", reflect.TypeOf((*doc.Value)(nil)).Elem())
}

