// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/printer

package microlisp

import (
	printer "go/printer"
	"reflect"
)

func register_go_printer() {
	registerPackage(
		"go/printer",
		map[string]interface{}{
			"Fprint": printer.Fprint,
		},
	)
	registerType("go/printer", "CommentedNode", reflect.TypeOf((*printer.CommentedNode)(nil)).Elem())
	registerType("go/printer", "Config", reflect.TypeOf((*printer.Config)(nil)).Elem())
	registerType("go/printer", "Mode", reflect.TypeOf((*printer.Mode)(nil)).Elem())
}

