// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/netip

package microlisp

import (
	netip "net/netip"
	"reflect"
)

func register_net_netip() {
	registerPackage(
		"net/netip",
		map[string]interface{}{
			"AddrFrom16": netip.AddrFrom16,
			"AddrFrom4": netip.AddrFrom4,
			"AddrFromSlice": netip.AddrFromSlice,
			"AddrPortFrom": netip.AddrPortFrom,
			"IPv4Unspecified": netip.IPv4Unspecified,
			"IPv6LinkLocalAllNodes": netip.IPv6LinkLocalAllNodes,
			"IPv6LinkLocalAllRouters": netip.IPv6LinkLocalAllRouters,
			"IPv6Loopback": netip.IPv6Loopback,
			"IPv6Unspecified": netip.IPv6Unspecified,
			"MustParseAddr": netip.MustParseAddr,
			"MustParseAddrPort": netip.MustParseAddrPort,
			"MustParsePrefix": netip.MustParsePrefix,
			"ParseAddr": netip.ParseAddr,
			"ParseAddrPort": netip.ParseAddrPort,
			"ParsePrefix": netip.ParsePrefix,
			"PrefixFrom": netip.PrefixFrom,
		},
	)
	registerType("net/netip", "Addr", reflect.TypeOf((*netip.Addr)(nil)).Elem())
	registerType("net/netip", "AddrPort", reflect.TypeOf((*netip.AddrPort)(nil)).Elem())
	registerType("net/netip", "Prefix", reflect.TypeOf((*netip.Prefix)(nil)).Elem())
}

