// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/mail

package microlisp

import (
	mail "net/mail"
	"reflect"
)

func register_net_mail() {
	registerPackage(
		"net/mail",
		map[string]interface{}{
			"ParseAddress": mail.ParseAddress,
			"ParseAddressList": mail.ParseAddressList,
			"ParseDate": mail.ParseDate,
			"ReadMessage": mail.ReadMessage,
			"ErrHeaderNotPresent": mail.ErrHeaderNotPresent,
		},
	)
	registerType("net/mail", "Address", reflect.TypeOf((*mail.Address)(nil)).Elem())
	registerType("net/mail", "AddressParser", reflect.TypeOf((*mail.AddressParser)(nil)).Elem())
	registerType("net/mail", "Header", reflect.TypeOf((*mail.Header)(nil)).Elem())
	registerType("net/mail", "Message", reflect.TypeOf((*mail.Message)(nil)).Elem())
}

