// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/types

package microlisp

import (
	types "go/types"
	"reflect"
)

func register_go_types() {
	registerPackage(
		"go/types",
		map[string]interface{}{
			"AssertableTo": types.AssertableTo,
			"AssignableTo": types.AssignableTo,
			"CheckExpr": types.CheckExpr,
			"Comparable": types.Comparable,
			"ConvertibleTo": types.ConvertibleTo,
			"DefPredeclaredTestFuncs": types.DefPredeclaredTestFuncs,
			"Default": types.Default,
			"Eval": types.Eval,
			"ExprString": types.ExprString,
			"Id": types.Id,
			"Identical": types.Identical,
			"IdenticalIgnoreTags": types.IdenticalIgnoreTags,
			"Implements": types.Implements,
			"Instantiate": types.Instantiate,
			"IsInterface": types.IsInterface,
			"LookupFieldOrMethod": types.LookupFieldOrMethod,
			"MissingMethod": types.MissingMethod,
			"NewArray": types.NewArray,
			"NewChan": types.NewChan,
			"NewChecker": types.NewChecker,
			"NewConst": types.NewConst,
			"NewContext": types.NewContext,
			"NewField": types.NewField,
			"NewFunc": types.NewFunc,
			"NewInterface": types.NewInterface,
			"NewInterfaceType": types.NewInterfaceType,
			"NewLabel": types.NewLabel,
			"NewMap": types.NewMap,
			"NewMethodSet": types.NewMethodSet,
			"NewNamed": types.NewNamed,
			"NewPackage": types.NewPackage,
			"NewParam": types.NewParam,
			"NewPkgName": types.NewPkgName,
			"NewPointer": types.NewPointer,
			"NewScope": types.NewScope,
			"NewSignature": types.NewSignature,
			"NewSignatureType": types.NewSignatureType,
			"NewSlice": types.NewSlice,
			"NewStruct": types.NewStruct,
			"NewTerm": types.NewTerm,
			"NewTuple": types.NewTuple,
			"NewTypeName": types.NewTypeName,
			"NewTypeParam": types.NewTypeParam,
			"NewUnion": types.NewUnion,
			"NewVar": types.NewVar,
			"ObjectString": types.ObjectString,
			"RelativeTo": types.RelativeTo,
			"Satisfies": types.Satisfies,
			"SelectionString": types.SelectionString,
			"SizesFor": types.SizesFor,
			"TypeString": types.TypeString,
			"WriteExpr": types.WriteExpr,
			"WriteSignature": types.WriteSignature,
			"WriteType": types.WriteType,
			"Typ": types.Typ,
			"Universe": types.Universe,
			"Unsafe": types.Unsafe,
		},
	)
	registerType("go/types", "ArgumentError", reflect.TypeOf((*types.ArgumentError)(nil)).Elem())
	registerType("go/types", "Array", reflect.TypeOf((*types.Array)(nil)).Elem())
	registerType("go/types", "Basic", reflect.TypeOf((*types.Basic)(nil)).Elem())
	registerType("go/types", "BasicInfo", reflect.TypeOf((*types.BasicInfo)(nil)).Elem())
	registerType("go/types", "BasicKind", reflect.TypeOf((*types.BasicKind)(nil)).Elem())
	registerType("go/types", "Builtin", reflect.TypeOf((*types.Builtin)(nil)).Elem())
	registerType("go/types", "Chan", reflect.TypeOf((*types.Chan)(nil)).Elem())
	registerType("go/types", "ChanDir", reflect.TypeOf((*types.ChanDir)(nil)).Elem())
	registerType("go/types", "Checker", reflect.TypeOf((*types.Checker)(nil)).Elem())
	registerType("go/types", "Config", reflect.TypeOf((*types.Config)(nil)).Elem())
	registerType("go/types", "Const", reflect.TypeOf((*types.Const)(nil)).Elem())
	registerType("go/types", "Context", reflect.TypeOf((*types.Context)(nil)).Elem())
	registerType("go/types", "Error", reflect.TypeOf((*types.Error)(nil)).Elem())
	registerType("go/types", "Func", reflect.TypeOf((*types.Func)(nil)).Elem())
	registerType("go/types", "ImportMode", reflect.TypeOf((*types.ImportMode)(nil)).Elem())
	registerType("go/types", "Importer", reflect.TypeOf((*types.Importer)(nil)).Elem())
	registerType("go/types", "ImporterFrom", reflect.TypeOf((*types.ImporterFrom)(nil)).Elem())
	registerType("go/types", "Info", reflect.TypeOf((*types.Info)(nil)).Elem())
	registerType("go/types", "Initializer", reflect.TypeOf((*types.Initializer)(nil)).Elem())
	registerType("go/types", "Instance", reflect.TypeOf((*types.Instance)(nil)).Elem())
	registerType("go/types", "Interface", reflect.TypeOf((*types.Interface)(nil)).Elem())
	registerType("go/types", "Label", reflect.TypeOf((*types.Label)(nil)).Elem())
	registerType("go/types", "Map", reflect.TypeOf((*types.Map)(nil)).Elem())
	registerType("go/types", "MethodSet", reflect.TypeOf((*types.MethodSet)(nil)).Elem())
	registerType("go/types", "Named", reflect.TypeOf((*types.Named)(nil)).Elem())
	registerType("go/types", "Nil", reflect.TypeOf((*types.Nil)(nil)).Elem())
	registerType("go/types", "Object", reflect.TypeOf((*types.Object)(nil)).Elem())
	registerType("go/types", "Package", reflect.TypeOf((*types.Package)(nil)).Elem())
	registerType("go/types", "PkgName", reflect.TypeOf((*types.PkgName)(nil)).Elem())
	registerType("go/types", "Pointer", reflect.TypeOf((*types.Pointer)(nil)).Elem())
	registerType("go/types", "Qualifier", reflect.TypeOf((*types.Qualifier)(nil)).Elem())
	registerType("go/types", "Scope", reflect.TypeOf((*types.Scope)(nil)).Elem())
	registerType("go/types", "Selection", reflect.TypeOf((*types.Selection)(nil)).Elem())
	registerType("go/types", "SelectionKind", reflect.TypeOf((*types.SelectionKind)(nil)).Elem())
	registerType("go/types", "Signature", reflect.TypeOf((*types.Signature)(nil)).Elem())
	registerType("go/types", "Sizes", reflect.TypeOf((*types.Sizes)(nil)).Elem())
	registerType("go/types", "Slice", reflect.TypeOf((*types.Slice)(nil)).Elem())
	registerType("go/types", "StdSizes", reflect.TypeOf((*types.StdSizes)(nil)).Elem())
	registerType("go/types", "Struct", reflect.TypeOf((*types.Struct)(nil)).Elem())
	registerType("go/types", "Term", reflect.TypeOf((*types.Term)(nil)).Elem())
	registerType("go/types", "Tuple", reflect.TypeOf((*types.Tuple)(nil)).Elem())
	registerType("go/types", "Type", reflect.TypeOf((*types.Type)(nil)).Elem())
	registerType("go/types", "TypeAndValue", reflect.TypeOf((*types.TypeAndValue)(nil)).Elem())
	registerType("go/types", "TypeList", reflect.TypeOf((*types.TypeList)(nil)).Elem())
	registerType("go/types", "TypeName", reflect.TypeOf((*types.TypeName)(nil)).Elem())
	registerType("go/types", "TypeParam", reflect.TypeOf((*types.TypeParam)(nil)).Elem())
	registerType("go/types", "TypeParamList", reflect.TypeOf((*types.TypeParamList)(nil)).Elem())
	registerType("go/types", "Union", reflect.TypeOf((*types.Union)(nil)).Elem())
	registerType("go/types", "Var", reflect.TypeOf((*types.Var)(nil)).Elem())
}

