// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: compress/zlib

package microlisp

import (
	zlib "compress/zlib"
	"reflect"
)

func register_compress_zlib() {
	registerPackage(
		"compress/zlib",
		map[string]interface{}{
			"NewReader": zlib.NewReader,
			"NewReaderDict": zlib.NewReaderDict,
			"NewWriter": zlib.NewWriter,
			"NewWriterLevel": zlib.NewWriterLevel,
			"NewWriterLevelDict": zlib.NewWriterLevelDict,
			"ErrChecksum": zlib.ErrChecksum,
			"ErrDictionary": zlib.ErrDictionary,
			"ErrHeader": zlib.ErrHeader,
			"BestCompression": zlib.BestCompression,
			"BestSpeed": zlib.BestSpeed,
			"DefaultCompression": zlib.DefaultCompression,
			"HuffmanOnly": zlib.HuffmanOnly,
			"NoCompression": zlib.NoCompression,
		},
	)
	registerType("compress/zlib", "Resetter", reflect.TypeOf((*zlib.Resetter)(nil)).Elem())
	registerType("compress/zlib", "Writer", reflect.TypeOf((*zlib.Writer)(nil)).Elem())
}

