// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: time

package microlisp

import (
	time "time"
	"reflect"
)

func register_time() {
	registerPackage(
		"time",
		map[string]interface{}{
			"After": time.After,
			"AfterFunc": time.AfterFunc,
			"Date": time.Date,
			"FixedZone": time.FixedZone,
			"LoadLocation": time.LoadLocation,
			"LoadLocationFromTZData": time.LoadLocationFromTZData,
			"NewTicker": time.NewTicker,
			"NewTimer": time.NewTimer,
			"Now": time.Now,
			"Parse": time.Parse,
			"ParseDuration": time.ParseDuration,
			"ParseInLocation": time.ParseInLocation,
			"Since": time.Since,
			"Sleep": time.Sleep,
			"Tick": time.Tick,
			"Unix": time.Unix,
			"UnixMicro": time.UnixMicro,
			"UnixMilli": time.UnixMilli,
			"Until": time.Until,
			"Local": time.Local,
			"UTC": time.UTC,
			"ANSIC": time.ANSIC,
			"April": time.April,
			"August": time.August,
			"DateOnly": time.DateOnly,
			"DateTime": time.DateTime,
			"December": time.December,
			"February": time.February,
			"Friday": time.Friday,
			"Hour": time.Hour,
			"January": time.January,
			"July": time.July,
			"June": time.June,
			"Kitchen": time.Kitchen,
			"Layout": time.Layout,
			"March": time.March,
			"May": time.May,
			"Microsecond": time.Microsecond,
			"Millisecond": time.Millisecond,
			"Minute": time.Minute,
			"Monday": time.Monday,
			"Nanosecond": time.Nanosecond,
			"November": time.November,
			"October": time.October,
			"RFC1123": time.RFC1123,
			"RFC1123Z": time.RFC1123Z,
			"RFC3339": time.RFC3339,
			"RFC3339Nano": time.RFC3339Nano,
			"RFC822": time.RFC822,
			"RFC822Z": time.RFC822Z,
			"RFC850": time.RFC850,
			"RubyDate": time.RubyDate,
			"Saturday": time.Saturday,
			"Second": time.Second,
			"September": time.September,
			"Stamp": time.Stamp,
			"StampMicro": time.StampMicro,
			"StampMilli": time.StampMilli,
			"StampNano": time.StampNano,
			"Sunday": time.Sunday,
			"Thursday": time.Thursday,
			"TimeOnly": time.TimeOnly,
			"Tuesday": time.Tuesday,
			"UnixDate": time.UnixDate,
			"Wednesday": time.Wednesday,
		},
	)
	registerType("time", "Duration", reflect.TypeOf((*time.Duration)(nil)).Elem())
	registerType("time", "Location", reflect.TypeOf((*time.Location)(nil)).Elem())
	registerType("time", "Month", reflect.TypeOf((*time.Month)(nil)).Elem())
	registerType("time", "ParseError", reflect.TypeOf((*time.ParseError)(nil)).Elem())
	registerType("time", "Ticker", reflect.TypeOf((*time.Ticker)(nil)).Elem())
	registerType("time", "Time", reflect.TypeOf((*time.Time)(nil)).Elem())
	registerType("time", "Timer", reflect.TypeOf((*time.Timer)(nil)).Elem())
	registerType("time", "Weekday", reflect.TypeOf((*time.Weekday)(nil)).Elem())
}

