// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: runtime/trace

package microlisp

import (
	trace "runtime/trace"
	"reflect"
)

func register_runtime_trace() {
	registerPackage(
		"runtime/trace",
		map[string]interface{}{
			"IsEnabled": trace.IsEnabled,
			"Log": trace.Log,
			"Logf": trace.Logf,
			"NewTask": trace.NewTask,
			"Start": trace.Start,
			"StartRegion": trace.StartRegion,
			"Stop": trace.Stop,
			"WithRegion": trace.WithRegion,
		},
	)
	registerType("runtime/trace", "Region", reflect.TypeOf((*trace.Region)(nil)).Elem())
	registerType("runtime/trace", "Task", reflect.TypeOf((*trace.Task)(nil)).Elem())
}

