// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/x509

package microlisp

import (
	x509 "crypto/x509"
	"reflect"
)

func register_crypto_x509() {
	registerPackage(
		"crypto/x509",
		map[string]interface{}{
			"CreateCertificate": x509.CreateCertificate,
			"CreateCertificateRequest": x509.CreateCertificateRequest,
			"CreateRevocationList": x509.CreateRevocationList,
			"DecryptPEMBlock": x509.DecryptPEMBlock,
			"EncryptPEMBlock": x509.EncryptPEMBlock,
			"IsEncryptedPEMBlock": x509.IsEncryptedPEMBlock,
			"MarshalECPrivateKey": x509.MarshalECPrivateKey,
			"MarshalPKCS1PrivateKey": x509.MarshalPKCS1PrivateKey,
			"MarshalPKCS1PublicKey": x509.MarshalPKCS1PublicKey,
			"MarshalPKCS8PrivateKey": x509.MarshalPKCS8PrivateKey,
			"MarshalPKIXPublicKey": x509.MarshalPKIXPublicKey,
			"NewCertPool": x509.NewCertPool,
			"ParseCRL": x509.ParseCRL,
			"ParseCertificate": x509.ParseCertificate,
			"ParseCertificateRequest": x509.ParseCertificateRequest,
			"ParseCertificates": x509.ParseCertificates,
			"ParseDERCRL": x509.ParseDERCRL,
			"ParseECPrivateKey": x509.ParseECPrivateKey,
			"ParsePKCS1PrivateKey": x509.ParsePKCS1PrivateKey,
			"ParsePKCS1PublicKey": x509.ParsePKCS1PublicKey,
			"ParsePKCS8PrivateKey": x509.ParsePKCS8PrivateKey,
			"ParsePKIXPublicKey": x509.ParsePKIXPublicKey,
			"ParseRevocationList": x509.ParseRevocationList,
			"SetFallbackRoots": x509.SetFallbackRoots,
			"SystemCertPool": x509.SystemCertPool,
			"ErrUnsupportedAlgorithm": x509.ErrUnsupportedAlgorithm,
			"IncorrectPasswordError": x509.IncorrectPasswordError,
		},
	)
	registerType("crypto/x509", "CertPool", reflect.TypeOf((*x509.CertPool)(nil)).Elem())
	registerType("crypto/x509", "Certificate", reflect.TypeOf((*x509.Certificate)(nil)).Elem())
	registerType("crypto/x509", "CertificateInvalidError", reflect.TypeOf((*x509.CertificateInvalidError)(nil)).Elem())
	registerType("crypto/x509", "CertificateRequest", reflect.TypeOf((*x509.CertificateRequest)(nil)).Elem())
	registerType("crypto/x509", "ConstraintViolationError", reflect.TypeOf((*x509.ConstraintViolationError)(nil)).Elem())
	registerType("crypto/x509", "ExtKeyUsage", reflect.TypeOf((*x509.ExtKeyUsage)(nil)).Elem())
	registerType("crypto/x509", "HostnameError", reflect.TypeOf((*x509.HostnameError)(nil)).Elem())
	registerType("crypto/x509", "InsecureAlgorithmError", reflect.TypeOf((*x509.InsecureAlgorithmError)(nil)).Elem())
	registerType("crypto/x509", "InvalidReason", reflect.TypeOf((*x509.InvalidReason)(nil)).Elem())
	registerType("crypto/x509", "KeyUsage", reflect.TypeOf((*x509.KeyUsage)(nil)).Elem())
	registerType("crypto/x509", "PEMCipher", reflect.TypeOf((*x509.PEMCipher)(nil)).Elem())
	registerType("crypto/x509", "PublicKeyAlgorithm", reflect.TypeOf((*x509.PublicKeyAlgorithm)(nil)).Elem())
	registerType("crypto/x509", "RevocationList", reflect.TypeOf((*x509.RevocationList)(nil)).Elem())
	registerType("crypto/x509", "RevocationListEntry", reflect.TypeOf((*x509.RevocationListEntry)(nil)).Elem())
	registerType("crypto/x509", "SignatureAlgorithm", reflect.TypeOf((*x509.SignatureAlgorithm)(nil)).Elem())
	registerType("crypto/x509", "SystemRootsError", reflect.TypeOf((*x509.SystemRootsError)(nil)).Elem())
	registerType("crypto/x509", "UnhandledCriticalExtension", reflect.TypeOf((*x509.UnhandledCriticalExtension)(nil)).Elem())
	registerType("crypto/x509", "UnknownAuthorityError", reflect.TypeOf((*x509.UnknownAuthorityError)(nil)).Elem())
	registerType("crypto/x509", "VerifyOptions", reflect.TypeOf((*x509.VerifyOptions)(nil)).Elem())
}

