// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: log/slog

package microlisp

import (
	slog "log/slog"
	"reflect"
)

func register_log_slog() {
	registerPackage(
		"log/slog",
		map[string]interface{}{
			"Any": slog.Any,
			"AnyValue": slog.AnyValue,
			"Bool": slog.Bool,
			"BoolValue": slog.BoolValue,
			"Debug": slog.Debug,
			"DebugContext": slog.DebugContext,
			"Default": slog.Default,
			"Duration": slog.Duration,
			"DurationValue": slog.DurationValue,
			"Error": slog.Error,
			"ErrorContext": slog.ErrorContext,
			"Float64": slog.Float64,
			"Float64Value": slog.Float64Value,
			"Group": slog.Group,
			"GroupValue": slog.GroupValue,
			"Info": slog.Info,
			"InfoContext": slog.InfoContext,
			"Int": slog.Int,
			"Int64": slog.Int64,
			"Int64Value": slog.Int64Value,
			"IntValue": slog.IntValue,
			"Log": slog.Log,
			"LogAttrs": slog.LogAttrs,
			"New": slog.New,
			"NewJSONHandler": slog.NewJSONHandler,
			"NewLogLogger": slog.NewLogLogger,
			"NewRecord": slog.NewRecord,
			"NewTextHandler": slog.NewTextHandler,
			"SetDefault": slog.SetDefault,
			"String": slog.String,
			"StringValue": slog.StringValue,
			"Time": slog.Time,
			"TimeValue": slog.TimeValue,
			"Uint64": slog.Uint64,
			"Uint64Value": slog.Uint64Value,
			"Warn": slog.Warn,
			"WarnContext": slog.WarnContext,
			"With": slog.With,
			"LevelKey": slog.LevelKey,
			"MessageKey": slog.MessageKey,
			"SourceKey": slog.SourceKey,
			"TimeKey": slog.TimeKey,
		},
	)
	registerType("log/slog", "Attr", reflect.TypeOf((*slog.Attr)(nil)).Elem())
	registerType("log/slog", "Handler", reflect.TypeOf((*slog.Handler)(nil)).Elem())
	registerType("log/slog", "HandlerOptions", reflect.TypeOf((*slog.HandlerOptions)(nil)).Elem())
	registerType("log/slog", "JSONHandler", reflect.TypeOf((*slog.JSONHandler)(nil)).Elem())
	registerType("log/slog", "Kind", reflect.TypeOf((*slog.Kind)(nil)).Elem())
	registerType("log/slog", "Level", reflect.TypeOf((*slog.Level)(nil)).Elem())
	registerType("log/slog", "LevelVar", reflect.TypeOf((*slog.LevelVar)(nil)).Elem())
	registerType("log/slog", "Leveler", reflect.TypeOf((*slog.Leveler)(nil)).Elem())
	registerType("log/slog", "LogValuer", reflect.TypeOf((*slog.LogValuer)(nil)).Elem())
	registerType("log/slog", "Logger", reflect.TypeOf((*slog.Logger)(nil)).Elem())
	registerType("log/slog", "Record", reflect.TypeOf((*slog.Record)(nil)).Elem())
	registerType("log/slog", "Source", reflect.TypeOf((*slog.Source)(nil)).Elem())
	registerType("log/slog", "TextHandler", reflect.TypeOf((*slog.TextHandler)(nil)).Elem())
	registerType("log/slog", "Value", reflect.TypeOf((*slog.Value)(nil)).Elem())
}

