// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: text/scanner

package microlisp

import (
	scanner "text/scanner"
	"reflect"
)

func register_text_scanner() {
	registerPackage(
		"text/scanner",
		map[string]interface{}{
			"TokenString": scanner.TokenString,
			"Char": scanner.Char,
			"Comment": scanner.Comment,
			"EOF": scanner.EOF,
			"Float": scanner.Float,
			"GoTokens": scanner.GoTokens,
			"GoWhitespace": uint64(scanner.GoWhitespace),
			"Ident": scanner.Ident,
			"Int": scanner.Int,
			"RawString": scanner.RawString,
			"ScanChars": scanner.ScanChars,
			"ScanComments": scanner.ScanComments,
			"ScanFloats": scanner.ScanFloats,
			"ScanIdents": scanner.ScanIdents,
			"ScanInts": scanner.ScanInts,
			"ScanRawStrings": scanner.ScanRawStrings,
			"ScanStrings": scanner.ScanStrings,
			"SkipComments": scanner.SkipComments,
			"String": scanner.String,
		},
	)
	registerType("text/scanner", "Position", reflect.TypeOf((*scanner.Position)(nil)).Elem())
	registerType("text/scanner", "Scanner", reflect.TypeOf((*scanner.Scanner)(nil)).Elem())
}

