// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: image/gif

package microlisp

import (
	gif "image/gif"
	"reflect"
)

func register_image_gif() {
	registerPackage(
		"image/gif",
		map[string]interface{}{
			"Decode": gif.Decode,
			"DecodeAll": gif.DecodeAll,
			"DecodeConfig": gif.DecodeConfig,
			"Encode": gif.Encode,
			"EncodeAll": gif.EncodeAll,
			"DisposalBackground": gif.DisposalBackground,
			"DisposalNone": gif.DisposalNone,
			"DisposalPrevious": gif.DisposalPrevious,
		},
	)
	registerType("image/gif", "GIF", reflect.TypeOf((*gif.GIF)(nil)).Elem())
	registerType("image/gif", "Options", reflect.TypeOf((*gif.Options)(nil)).Elem())
}

