// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/http/fcgi

package microlisp

import (
	fcgi "net/http/fcgi"
)

func register_net_http_fcgi() {
	registerPackage(
		"net/http/fcgi",
		map[string]interface{}{
			"ProcessEnv": fcgi.ProcessEnv,
			"Serve": fcgi.Serve,
			"ErrConnClosed": fcgi.ErrConnClosed,
			"ErrRequestAborted": fcgi.ErrRequestAborted,
		},
	)
}

