// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: mime/quotedprintable

package microlisp

import (
	quotedprintable "mime/quotedprintable"
	"reflect"
)

func register_mime_quotedprintable() {
	registerPackage(
		"mime/quotedprintable",
		map[string]interface{}{
			"NewReader": quotedprintable.NewReader,
			"NewWriter": quotedprintable.NewWriter,
		},
	)
	registerType("mime/quotedprintable", "Reader", reflect.TypeOf((*quotedprintable.Reader)(nil)).Elem())
	registerType("mime/quotedprintable", "Writer", reflect.TypeOf((*quotedprintable.Writer)(nil)).Elem())
}

