// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: io/fs

package microlisp

import (
	fs "io/fs"
	"reflect"
)

func register_io_fs() {
	registerPackage(
		"io/fs",
		map[string]interface{}{
			"FileInfoToDirEntry": fs.FileInfoToDirEntry,
			"FormatDirEntry": fs.FormatDirEntry,
			"FormatFileInfo": fs.FormatFileInfo,
			"Glob": fs.Glob,
			"ReadDir": fs.ReadDir,
			"ReadFile": fs.ReadFile,
			"Stat": fs.Stat,
			"Sub": fs.Sub,
			"ValidPath": fs.ValidPath,
			"WalkDir": fs.WalkDir,
			"ErrClosed": fs.ErrClosed,
			"ErrExist": fs.ErrExist,
			"ErrInvalid": fs.ErrInvalid,
			"ErrNotExist": fs.ErrNotExist,
			"ErrPermission": fs.ErrPermission,
			"SkipAll": fs.SkipAll,
			"SkipDir": fs.SkipDir,
			"ModeAppend": fs.ModeAppend,
			"ModeCharDevice": fs.ModeCharDevice,
			"ModeDevice": fs.ModeDevice,
			"ModeDir": fs.ModeDir,
			"ModeExclusive": fs.ModeExclusive,
			"ModeIrregular": fs.ModeIrregular,
			"ModeNamedPipe": fs.ModeNamedPipe,
			"ModePerm": fs.ModePerm,
			"ModeSetgid": fs.ModeSetgid,
			"ModeSetuid": fs.ModeSetuid,
			"ModeSocket": fs.ModeSocket,
			"ModeSticky": fs.ModeSticky,
			"ModeSymlink": fs.ModeSymlink,
			"ModeTemporary": fs.ModeTemporary,
			"ModeType": fs.ModeType,
		},
	)
	registerType("io/fs", "DirEntry", reflect.TypeOf((*fs.DirEntry)(nil)).Elem())
	registerType("io/fs", "FS", reflect.TypeOf((*fs.FS)(nil)).Elem())
	registerType("io/fs", "File", reflect.TypeOf((*fs.File)(nil)).Elem())
	registerType("io/fs", "FileInfo", reflect.TypeOf((*fs.FileInfo)(nil)).Elem())
	registerType("io/fs", "FileMode", reflect.TypeOf((*fs.FileMode)(nil)).Elem())
	registerType("io/fs", "GlobFS", reflect.TypeOf((*fs.GlobFS)(nil)).Elem())
	registerType("io/fs", "PathError", reflect.TypeOf((*fs.PathError)(nil)).Elem())
	registerType("io/fs", "ReadDirFS", reflect.TypeOf((*fs.ReadDirFS)(nil)).Elem())
	registerType("io/fs", "ReadDirFile", reflect.TypeOf((*fs.ReadDirFile)(nil)).Elem())
	registerType("io/fs", "ReadFileFS", reflect.TypeOf((*fs.ReadFileFS)(nil)).Elem())
	registerType("io/fs", "StatFS", reflect.TypeOf((*fs.StatFS)(nil)).Elem())
	registerType("io/fs", "SubFS", reflect.TypeOf((*fs.SubFS)(nil)).Elem())
	registerType("io/fs", "WalkDirFunc", reflect.TypeOf((*fs.WalkDirFunc)(nil)).Elem())
}

