// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/importer

package microlisp

import (
	importer "go/importer"
	"reflect"
)

func register_go_importer() {
	registerPackage(
		"go/importer",
		map[string]interface{}{
			"Default": importer.Default,
			"For": importer.For,
			"ForCompiler": importer.ForCompiler,
		},
	)
	registerType("go/importer", "Lookup", reflect.TypeOf((*importer.Lookup)(nil)).Elem())
}

