// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/tls

package microlisp

import (
	tls "crypto/tls"
	"reflect"
)

func register_crypto_tls() {
	registerPackage(
		"crypto/tls",
		map[string]interface{}{
			"CipherSuiteName": tls.CipherSuiteName,
			"CipherSuites": tls.CipherSuites,
			"Client": tls.Client,
			"Dial": tls.Dial,
			"DialWithDialer": tls.DialWithDialer,
			"InsecureCipherSuites": tls.InsecureCipherSuites,
			"Listen": tls.Listen,
			"LoadX509KeyPair": tls.LoadX509KeyPair,
			"NewLRUClientSessionCache": tls.NewLRUClientSessionCache,
			"NewListener": tls.NewListener,
			"NewResumptionState": tls.NewResumptionState,
			"ParseSessionState": tls.ParseSessionState,
			"QUICClient": tls.QUICClient,
			"QUICServer": tls.QUICServer,
			"Server": tls.Server,
			"VersionName": tls.VersionName,
			"X509KeyPair": tls.X509KeyPair,
			"TLS_AES_128_GCM_SHA256": tls.TLS_AES_128_GCM_SHA256,
			"TLS_AES_256_GCM_SHA384": tls.TLS_AES_256_GCM_SHA384,
			"TLS_CHACHA20_POLY1305_SHA256": tls.TLS_CHACHA20_POLY1305_SHA256,
			"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA": tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
			"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256": tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,
			"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256": tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			"TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA": tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
			"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384": tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305": tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
			"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256": tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
			"TLS_ECDHE_ECDSA_WITH_RC4_128_SHA": tls.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
			"TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA": tls.TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,
			"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA": tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
			"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256": tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,
			"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256": tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
			"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA": tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
			"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384": tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
			"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305": tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
			"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256": tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
			"TLS_ECDHE_RSA_WITH_RC4_128_SHA": tls.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
			"TLS_FALLBACK_SCSV": tls.TLS_FALLBACK_SCSV,
			"TLS_RSA_WITH_3DES_EDE_CBC_SHA": tls.TLS_RSA_WITH_3DES_EDE_CBC_SHA,
			"TLS_RSA_WITH_AES_128_CBC_SHA": tls.TLS_RSA_WITH_AES_128_CBC_SHA,
			"TLS_RSA_WITH_AES_128_CBC_SHA256": tls.TLS_RSA_WITH_AES_128_CBC_SHA256,
			"TLS_RSA_WITH_AES_128_GCM_SHA256": tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
			"TLS_RSA_WITH_AES_256_CBC_SHA": tls.TLS_RSA_WITH_AES_256_CBC_SHA,
			"TLS_RSA_WITH_AES_256_GCM_SHA384": tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
			"TLS_RSA_WITH_RC4_128_SHA": tls.TLS_RSA_WITH_RC4_128_SHA,
			"VersionSSL30": tls.VersionSSL30,
			"VersionTLS10": tls.VersionTLS10,
			"VersionTLS11": tls.VersionTLS11,
			"VersionTLS12": tls.VersionTLS12,
			"VersionTLS13": tls.VersionTLS13,
		},
	)
	registerType("crypto/tls", "AlertError", reflect.TypeOf((*tls.AlertError)(nil)).Elem())
	registerType("crypto/tls", "Certificate", reflect.TypeOf((*tls.Certificate)(nil)).Elem())
	registerType("crypto/tls", "CertificateRequestInfo", reflect.TypeOf((*tls.CertificateRequestInfo)(nil)).Elem())
	registerType("crypto/tls", "CertificateVerificationError", reflect.TypeOf((*tls.CertificateVerificationError)(nil)).Elem())
	registerType("crypto/tls", "CipherSuite", reflect.TypeOf((*tls.CipherSuite)(nil)).Elem())
	registerType("crypto/tls", "ClientAuthType", reflect.TypeOf((*tls.ClientAuthType)(nil)).Elem())
	registerType("crypto/tls", "ClientHelloInfo", reflect.TypeOf((*tls.ClientHelloInfo)(nil)).Elem())
	registerType("crypto/tls", "ClientSessionCache", reflect.TypeOf((*tls.ClientSessionCache)(nil)).Elem())
	registerType("crypto/tls", "ClientSessionState", reflect.TypeOf((*tls.ClientSessionState)(nil)).Elem())
	registerType("crypto/tls", "Config", reflect.TypeOf((*tls.Config)(nil)).Elem())
	registerType("crypto/tls", "Conn", reflect.TypeOf((*tls.Conn)(nil)).Elem())
	registerType("crypto/tls", "ConnectionState", reflect.TypeOf((*tls.ConnectionState)(nil)).Elem())
	registerType("crypto/tls", "CurveID", reflect.TypeOf((*tls.CurveID)(nil)).Elem())
	registerType("crypto/tls", "Dialer", reflect.TypeOf((*tls.Dialer)(nil)).Elem())
	registerType("crypto/tls", "QUICConfig", reflect.TypeOf((*tls.QUICConfig)(nil)).Elem())
	registerType("crypto/tls", "QUICConn", reflect.TypeOf((*tls.QUICConn)(nil)).Elem())
	registerType("crypto/tls", "QUICEncryptionLevel", reflect.TypeOf((*tls.QUICEncryptionLevel)(nil)).Elem())
	registerType("crypto/tls", "QUICEvent", reflect.TypeOf((*tls.QUICEvent)(nil)).Elem())
	registerType("crypto/tls", "QUICEventKind", reflect.TypeOf((*tls.QUICEventKind)(nil)).Elem())
	registerType("crypto/tls", "QUICSessionTicketOptions", reflect.TypeOf((*tls.QUICSessionTicketOptions)(nil)).Elem())
	registerType("crypto/tls", "RecordHeaderError", reflect.TypeOf((*tls.RecordHeaderError)(nil)).Elem())
	registerType("crypto/tls", "RenegotiationSupport", reflect.TypeOf((*tls.RenegotiationSupport)(nil)).Elem())
	registerType("crypto/tls", "SessionState", reflect.TypeOf((*tls.SessionState)(nil)).Elem())
	registerType("crypto/tls", "SignatureScheme", reflect.TypeOf((*tls.SignatureScheme)(nil)).Elem())
}

