// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/scanner

package microlisp

import (
	scanner "go/scanner"
	"reflect"
)

func register_go_scanner() {
	registerPackage(
		"go/scanner",
		map[string]interface{}{
			"PrintError": scanner.PrintError,
		},
	)
	registerType("go/scanner", "Error", reflect.TypeOf((*scanner.Error)(nil)).Elem())
	registerType("go/scanner", "ErrorHandler", reflect.TypeOf((*scanner.ErrorHandler)(nil)).Elem())
	registerType("go/scanner", "ErrorList", reflect.TypeOf((*scanner.ErrorList)(nil)).Elem())
	registerType("go/scanner", "Mode", reflect.TypeOf((*scanner.Mode)(nil)).Elem())
	registerType("go/scanner", "Scanner", reflect.TypeOf((*scanner.Scanner)(nil)).Elem())
}

