// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: hash/fnv

package microlisp

import (
	fnv "hash/fnv"
)

func register_hash_fnv() {
	registerPackage(
		"hash/fnv",
		map[string]interface{}{
			"New128": fnv.New128,
			"New128a": fnv.New128a,
			"New32": fnv.New32,
			"New32a": fnv.New32a,
			"New64": fnv.New64,
			"New64a": fnv.New64a,
		},
	)
}

