// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: database/sql

package microlisp

import (
	sql "database/sql"
	"reflect"
)

func register_database_sql() {
	registerPackage(
		"database/sql",
		map[string]interface{}{
			"Drivers": sql.Drivers,
			"Named": sql.Named,
			"Open": sql.Open,
			"OpenDB": sql.OpenDB,
			"Register": sql.Register,
			"ErrConnDone": sql.ErrConnDone,
			"ErrNoRows": sql.ErrNoRows,
			"ErrTxDone": sql.ErrTxDone,
		},
	)
	registerType("database/sql", "ColumnType", reflect.TypeOf((*sql.ColumnType)(nil)).Elem())
	registerType("database/sql", "Conn", reflect.TypeOf((*sql.Conn)(nil)).Elem())
	registerType("database/sql", "DB", reflect.TypeOf((*sql.DB)(nil)).Elem())
	registerType("database/sql", "DBStats", reflect.TypeOf((*sql.DBStats)(nil)).Elem())
	registerType("database/sql", "IsolationLevel", reflect.TypeOf((*sql.IsolationLevel)(nil)).Elem())
	registerType("database/sql", "NamedArg", reflect.TypeOf((*sql.NamedArg)(nil)).Elem())
	registerType("database/sql", "NullBool", reflect.TypeOf((*sql.NullBool)(nil)).Elem())
	registerType("database/sql", "NullByte", reflect.TypeOf((*sql.NullByte)(nil)).Elem())
	registerType("database/sql", "NullFloat64", reflect.TypeOf((*sql.NullFloat64)(nil)).Elem())
	registerType("database/sql", "NullInt16", reflect.TypeOf((*sql.NullInt16)(nil)).Elem())
	registerType("database/sql", "NullInt32", reflect.TypeOf((*sql.NullInt32)(nil)).Elem())
	registerType("database/sql", "NullInt64", reflect.TypeOf((*sql.NullInt64)(nil)).Elem())
	registerType("database/sql", "NullString", reflect.TypeOf((*sql.NullString)(nil)).Elem())
	registerType("database/sql", "NullTime", reflect.TypeOf((*sql.NullTime)(nil)).Elem())
	registerType("database/sql", "Out", reflect.TypeOf((*sql.Out)(nil)).Elem())
	registerType("database/sql", "RawBytes", reflect.TypeOf((*sql.RawBytes)(nil)).Elem())
	registerType("database/sql", "Result", reflect.TypeOf((*sql.Result)(nil)).Elem())
	registerType("database/sql", "Row", reflect.TypeOf((*sql.Row)(nil)).Elem())
	registerType("database/sql", "Rows", reflect.TypeOf((*sql.Rows)(nil)).Elem())
	registerType("database/sql", "Scanner", reflect.TypeOf((*sql.Scanner)(nil)).Elem())
	registerType("database/sql", "Stmt", reflect.TypeOf((*sql.Stmt)(nil)).Elem())
	registerType("database/sql", "Tx", reflect.TypeOf((*sql.Tx)(nil)).Elem())
	registerType("database/sql", "TxOptions", reflect.TypeOf((*sql.TxOptions)(nil)).Elem())
}

