// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/base32

package microlisp

import (
	base32 "encoding/base32"
	"reflect"
)

func register_encoding_base32() {
	registerPackage(
		"encoding/base32",
		map[string]interface{}{
			"NewDecoder": base32.NewDecoder,
			"NewEncoder": base32.NewEncoder,
			"NewEncoding": base32.NewEncoding,
			"HexEncoding": base32.HexEncoding,
			"StdEncoding": base32.StdEncoding,
			"NoPadding": base32.NoPadding,
			"StdPadding": base32.StdPadding,
		},
	)
	registerType("encoding/base32", "CorruptInputError", reflect.TypeOf((*base32.CorruptInputError)(nil)).Elem())
	registerType("encoding/base32", "Encoding", reflect.TypeOf((*base32.Encoding)(nil)).Elem())
}

