// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/ascii85

package microlisp

import (
	ascii85 "encoding/ascii85"
	"reflect"
)

func register_encoding_ascii85() {
	registerPackage(
		"encoding/ascii85",
		map[string]interface{}{
			"Decode": ascii85.Decode,
			"Encode": ascii85.Encode,
			"MaxEncodedLen": ascii85.MaxEncodedLen,
			"NewDecoder": ascii85.NewDecoder,
			"NewEncoder": ascii85.NewEncoder,
		},
	)
	registerType("encoding/ascii85", "CorruptInputError", reflect.TypeOf((*ascii85.CorruptInputError)(nil)).Elem())
}

