// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/sha1

package microlisp

import (
	sha1 "crypto/sha1"
)

func register_crypto_sha1() {
	registerPackage(
		"crypto/sha1",
		map[string]interface{}{
			"New": sha1.New,
			"Sum": sha1.Sum,
			"BlockSize": sha1.BlockSize,
			"Size": sha1.Size,
		},
	)
}

