// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/build/constraint

package microlisp

import (
	constraint "go/build/constraint"
	"reflect"
)

func register_go_build_constraint() {
	registerPackage(
		"go/build/constraint",
		map[string]interface{}{
			"GoVersion": constraint.GoVersion,
			"IsGoBuild": constraint.IsGoBuild,
			"IsPlusBuild": constraint.IsPlusBuild,
			"Parse": constraint.Parse,
			"PlusBuildLines": constraint.PlusBuildLines,
		},
	)
	registerType("go/build/constraint", "AndExpr", reflect.TypeOf((*constraint.AndExpr)(nil)).Elem())
	registerType("go/build/constraint", "Expr", reflect.TypeOf((*constraint.Expr)(nil)).Elem())
	registerType("go/build/constraint", "NotExpr", reflect.TypeOf((*constraint.NotExpr)(nil)).Elem())
	registerType("go/build/constraint", "OrExpr", reflect.TypeOf((*constraint.OrExpr)(nil)).Elem())
	registerType("go/build/constraint", "SyntaxError", reflect.TypeOf((*constraint.SyntaxError)(nil)).Elem())
	registerType("go/build/constraint", "TagExpr", reflect.TypeOf((*constraint.TagExpr)(nil)).Elem())
}

