// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/sha256

package microlisp

import (
	sha256 "crypto/sha256"
)

func register_crypto_sha256() {
	registerPackage(
		"crypto/sha256",
		map[string]interface{}{
			"New": sha256.New,
			"New224": sha256.New224,
			"Sum224": sha256.Sum224,
			"Sum256": sha256.Sum256,
			"BlockSize": sha256.BlockSize,
			"Size": sha256.Size,
			"Size224": sha256.Size224,
		},
	)
}

