// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/x509

package microlisp

import (
	x509 "crypto/x509"
	"reflect"
)

func register_crypto_x509() {
	registerPackage(
		"crypto/x509",
		map[string]interface{}{
			"CreateCertificate": x509.CreateCertificate,
			"CreateCertificateRequest": x509.CreateCertificateRequest,
			"CreateRevocationList": x509.CreateRevocationList,
			"DecryptPEMBlock": x509.DecryptPEMBlock,
			"EncryptPEMBlock": x509.EncryptPEMBlock,
			"IsEncryptedPEMBlock": x509.IsEncryptedPEMBlock,
			"MarshalECPrivateKey": x509.MarshalECPrivateKey,
			"MarshalPKCS1PrivateKey": x509.MarshalPKCS1PrivateKey,
			"MarshalPKCS1PublicKey": x509.MarshalPKCS1PublicKey,
			"MarshalPKCS8PrivateKey": x509.MarshalPKCS8PrivateKey,
			"MarshalPKIXPublicKey": x509.MarshalPKIXPublicKey,
			"NewCertPool": x509.NewCertPool,
			"ParseCRL": x509.ParseCRL,
			"ParseCertificate": x509.ParseCertificate,
			"ParseCertificateRequest": x509.ParseCertificateRequest,
			"ParseCertificates": x509.ParseCertificates,
			"ParseDERCRL": x509.ParseDERCRL,
			"ParseECPrivateKey": x509.ParseECPrivateKey,
			"ParsePKCS1PrivateKey": x509.ParsePKCS1PrivateKey,
			"ParsePKCS1PublicKey": x509.ParsePKCS1PublicKey,
			"ParsePKCS8PrivateKey": x509.ParsePKCS8PrivateKey,
			"ParsePKIXPublicKey": x509.ParsePKIXPublicKey,
			"ParseRevocationList": x509.ParseRevocationList,
			"SetFallbackRoots": x509.SetFallbackRoots,
			"SystemCertPool": x509.SystemCertPool,
			"ErrUnsupportedAlgorithm": x509.ErrUnsupportedAlgorithm,
			"IncorrectPasswordError": x509.IncorrectPasswordError,
			"CANotAuthorizedForExtKeyUsage": x509.CANotAuthorizedForExtKeyUsage,
			"CANotAuthorizedForThisName": x509.CANotAuthorizedForThisName,
			"DSA": x509.DSA,
			"DSAWithSHA1": x509.DSAWithSHA1,
			"DSAWithSHA256": x509.DSAWithSHA256,
			"ECDSA": x509.ECDSA,
			"ECDSAWithSHA1": x509.ECDSAWithSHA1,
			"ECDSAWithSHA256": x509.ECDSAWithSHA256,
			"ECDSAWithSHA384": x509.ECDSAWithSHA384,
			"ECDSAWithSHA512": x509.ECDSAWithSHA512,
			"Ed25519": x509.Ed25519,
			"Expired": x509.Expired,
			"ExtKeyUsageAny": x509.ExtKeyUsageAny,
			"ExtKeyUsageClientAuth": x509.ExtKeyUsageClientAuth,
			"ExtKeyUsageCodeSigning": x509.ExtKeyUsageCodeSigning,
			"ExtKeyUsageEmailProtection": x509.ExtKeyUsageEmailProtection,
			"ExtKeyUsageIPSECEndSystem": x509.ExtKeyUsageIPSECEndSystem,
			"ExtKeyUsageIPSECTunnel": x509.ExtKeyUsageIPSECTunnel,
			"ExtKeyUsageIPSECUser": x509.ExtKeyUsageIPSECUser,
			"ExtKeyUsageMicrosoftCommercialCodeSigning": x509.ExtKeyUsageMicrosoftCommercialCodeSigning,
			"ExtKeyUsageMicrosoftKernelCodeSigning": x509.ExtKeyUsageMicrosoftKernelCodeSigning,
			"ExtKeyUsageMicrosoftServerGatedCrypto": x509.ExtKeyUsageMicrosoftServerGatedCrypto,
			"ExtKeyUsageNetscapeServerGatedCrypto": x509.ExtKeyUsageNetscapeServerGatedCrypto,
			"ExtKeyUsageOCSPSigning": x509.ExtKeyUsageOCSPSigning,
			"ExtKeyUsageServerAuth": x509.ExtKeyUsageServerAuth,
			"ExtKeyUsageTimeStamping": x509.ExtKeyUsageTimeStamping,
			"IncompatibleUsage": x509.IncompatibleUsage,
			"KeyUsageCRLSign": x509.KeyUsageCRLSign,
			"KeyUsageCertSign": x509.KeyUsageCertSign,
			"KeyUsageContentCommitment": x509.KeyUsageContentCommitment,
			"KeyUsageDataEncipherment": x509.KeyUsageDataEncipherment,
			"KeyUsageDecipherOnly": x509.KeyUsageDecipherOnly,
			"KeyUsageDigitalSignature": x509.KeyUsageDigitalSignature,
			"KeyUsageEncipherOnly": x509.KeyUsageEncipherOnly,
			"KeyUsageKeyAgreement": x509.KeyUsageKeyAgreement,
			"KeyUsageKeyEncipherment": x509.KeyUsageKeyEncipherment,
			"MD2WithRSA": x509.MD2WithRSA,
			"MD5WithRSA": x509.MD5WithRSA,
			"NameConstraintsWithoutSANs": x509.NameConstraintsWithoutSANs,
			"NameMismatch": x509.NameMismatch,
			"NotAuthorizedToSign": x509.NotAuthorizedToSign,
			"PEMCipher3DES": x509.PEMCipher3DES,
			"PEMCipherAES128": x509.PEMCipherAES128,
			"PEMCipherAES192": x509.PEMCipherAES192,
			"PEMCipherAES256": x509.PEMCipherAES256,
			"PEMCipherDES": x509.PEMCipherDES,
			"PureEd25519": x509.PureEd25519,
			"RSA": x509.RSA,
			"SHA1WithRSA": x509.SHA1WithRSA,
			"SHA256WithRSA": x509.SHA256WithRSA,
			"SHA256WithRSAPSS": x509.SHA256WithRSAPSS,
			"SHA384WithRSA": x509.SHA384WithRSA,
			"SHA384WithRSAPSS": x509.SHA384WithRSAPSS,
			"SHA512WithRSA": x509.SHA512WithRSA,
			"SHA512WithRSAPSS": x509.SHA512WithRSAPSS,
			"TooManyConstraints": x509.TooManyConstraints,
			"TooManyIntermediates": x509.TooManyIntermediates,
			"UnconstrainedName": x509.UnconstrainedName,
			"UnknownPublicKeyAlgorithm": x509.UnknownPublicKeyAlgorithm,
			"UnknownSignatureAlgorithm": x509.UnknownSignatureAlgorithm,
		},
	)
	registerType("crypto/x509", "CertPool", reflect.TypeOf((*x509.CertPool)(nil)).Elem())
	registerType("crypto/x509", "Certificate", reflect.TypeOf((*x509.Certificate)(nil)).Elem())
	registerType("crypto/x509", "CertificateInvalidError", reflect.TypeOf((*x509.CertificateInvalidError)(nil)).Elem())
	registerType("crypto/x509", "CertificateRequest", reflect.TypeOf((*x509.CertificateRequest)(nil)).Elem())
	registerType("crypto/x509", "ConstraintViolationError", reflect.TypeOf((*x509.ConstraintViolationError)(nil)).Elem())
	registerType("crypto/x509", "ExtKeyUsage", reflect.TypeOf((*x509.ExtKeyUsage)(nil)).Elem())
	registerType("crypto/x509", "HostnameError", reflect.TypeOf((*x509.HostnameError)(nil)).Elem())
	registerType("crypto/x509", "InsecureAlgorithmError", reflect.TypeOf((*x509.InsecureAlgorithmError)(nil)).Elem())
	registerType("crypto/x509", "InvalidReason", reflect.TypeOf((*x509.InvalidReason)(nil)).Elem())
	registerType("crypto/x509", "KeyUsage", reflect.TypeOf((*x509.KeyUsage)(nil)).Elem())
	registerType("crypto/x509", "PEMCipher", reflect.TypeOf((*x509.PEMCipher)(nil)).Elem())
	registerType("crypto/x509", "PublicKeyAlgorithm", reflect.TypeOf((*x509.PublicKeyAlgorithm)(nil)).Elem())
	registerType("crypto/x509", "RevocationList", reflect.TypeOf((*x509.RevocationList)(nil)).Elem())
	registerType("crypto/x509", "RevocationListEntry", reflect.TypeOf((*x509.RevocationListEntry)(nil)).Elem())
	registerType("crypto/x509", "SignatureAlgorithm", reflect.TypeOf((*x509.SignatureAlgorithm)(nil)).Elem())
	registerType("crypto/x509", "SystemRootsError", reflect.TypeOf((*x509.SystemRootsError)(nil)).Elem())
	registerType("crypto/x509", "UnhandledCriticalExtension", reflect.TypeOf((*x509.UnhandledCriticalExtension)(nil)).Elem())
	registerType("crypto/x509", "UnknownAuthorityError", reflect.TypeOf((*x509.UnknownAuthorityError)(nil)).Elem())
	registerType("crypto/x509", "VerifyOptions", reflect.TypeOf((*x509.VerifyOptions)(nil)).Elem())
}

