// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/constant

package microlisp

import (
	constant "go/constant"
	"reflect"
)

func register_go_constant() {
	registerPackage(
		"go/constant",
		map[string]interface{}{
			"BinaryOp": constant.BinaryOp,
			"BitLen": constant.BitLen,
			"BoolVal": constant.BoolVal,
			"Bytes": constant.Bytes,
			"Compare": constant.Compare,
			"Denom": constant.Denom,
			"Float32Val": constant.Float32Val,
			"Float64Val": constant.Float64Val,
			"Imag": constant.Imag,
			"Int64Val": constant.Int64Val,
			"Make": constant.Make,
			"MakeBool": constant.MakeBool,
			"MakeFloat64": constant.MakeFloat64,
			"MakeFromBytes": constant.MakeFromBytes,
			"MakeFromLiteral": constant.MakeFromLiteral,
			"MakeImag": constant.MakeImag,
			"MakeInt64": constant.MakeInt64,
			"MakeString": constant.MakeString,
			"MakeUint64": constant.MakeUint64,
			"MakeUnknown": constant.MakeUnknown,
			"Num": constant.Num,
			"Real": constant.Real,
			"Shift": constant.Shift,
			"Sign": constant.Sign,
			"StringVal": constant.StringVal,
			"ToComplex": constant.ToComplex,
			"ToFloat": constant.ToFloat,
			"ToInt": constant.ToInt,
			"Uint64Val": constant.Uint64Val,
			"UnaryOp": constant.UnaryOp,
			"Val": constant.Val,
		},
	)
	registerType("go/constant", "Kind", reflect.TypeOf((*constant.Kind)(nil)).Elem())
	registerType("go/constant", "Value", reflect.TypeOf((*constant.Value)(nil)).Elem())
}

