// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/http/cgi

package microlisp

import (
	cgi "net/http/cgi"
	"reflect"
)

func register_net_http_cgi() {
	registerPackage(
		"net/http/cgi",
		map[string]interface{}{
			"Request": cgi.Request,
			"RequestFromMap": cgi.RequestFromMap,
			"Serve": cgi.Serve,
		},
	)
	registerType("net/http/cgi", "Handler", reflect.TypeOf((*cgi.Handler)(nil)).Elem())
}

