// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: io

package microlisp

import (
	io "io"
	"reflect"
)

func register_io() {
	registerPackage(
		"io",
		map[string]interface{}{
			"Copy": io.Copy,
			"CopyBuffer": io.CopyBuffer,
			"CopyN": io.CopyN,
			"LimitReader": io.LimitReader,
			"MultiReader": io.MultiReader,
			"MultiWriter": io.MultiWriter,
			"NewOffsetWriter": io.NewOffsetWriter,
			"NewSectionReader": io.NewSectionReader,
			"NopCloser": io.NopCloser,
			"Pipe": io.Pipe,
			"ReadAll": io.ReadAll,
			"ReadAtLeast": io.ReadAtLeast,
			"ReadFull": io.ReadFull,
			"TeeReader": io.TeeReader,
			"WriteString": io.WriteString,
			"Discard": io.Discard,
			"EOF": io.EOF,
			"ErrClosedPipe": io.ErrClosedPipe,
			"ErrNoProgress": io.ErrNoProgress,
			"ErrShortBuffer": io.ErrShortBuffer,
			"ErrShortWrite": io.ErrShortWrite,
			"ErrUnexpectedEOF": io.ErrUnexpectedEOF,
			"SeekCurrent": io.SeekCurrent,
			"SeekEnd": io.SeekEnd,
			"SeekStart": io.SeekStart,
		},
	)
	registerType("io", "ByteReader", reflect.TypeOf((*io.ByteReader)(nil)).Elem())
	registerType("io", "ByteScanner", reflect.TypeOf((*io.ByteScanner)(nil)).Elem())
	registerType("io", "ByteWriter", reflect.TypeOf((*io.ByteWriter)(nil)).Elem())
	registerType("io", "Closer", reflect.TypeOf((*io.Closer)(nil)).Elem())
	registerType("io", "LimitedReader", reflect.TypeOf((*io.LimitedReader)(nil)).Elem())
	registerType("io", "OffsetWriter", reflect.TypeOf((*io.OffsetWriter)(nil)).Elem())
	registerType("io", "PipeReader", reflect.TypeOf((*io.PipeReader)(nil)).Elem())
	registerType("io", "PipeWriter", reflect.TypeOf((*io.PipeWriter)(nil)).Elem())
	registerType("io", "ReadCloser", reflect.TypeOf((*io.ReadCloser)(nil)).Elem())
	registerType("io", "ReadSeekCloser", reflect.TypeOf((*io.ReadSeekCloser)(nil)).Elem())
	registerType("io", "ReadSeeker", reflect.TypeOf((*io.ReadSeeker)(nil)).Elem())
	registerType("io", "ReadWriteCloser", reflect.TypeOf((*io.ReadWriteCloser)(nil)).Elem())
	registerType("io", "ReadWriteSeeker", reflect.TypeOf((*io.ReadWriteSeeker)(nil)).Elem())
	registerType("io", "ReadWriter", reflect.TypeOf((*io.ReadWriter)(nil)).Elem())
	registerType("io", "Reader", reflect.TypeOf((*io.Reader)(nil)).Elem())
	registerType("io", "ReaderAt", reflect.TypeOf((*io.ReaderAt)(nil)).Elem())
	registerType("io", "ReaderFrom", reflect.TypeOf((*io.ReaderFrom)(nil)).Elem())
	registerType("io", "RuneReader", reflect.TypeOf((*io.RuneReader)(nil)).Elem())
	registerType("io", "RuneScanner", reflect.TypeOf((*io.RuneScanner)(nil)).Elem())
	registerType("io", "SectionReader", reflect.TypeOf((*io.SectionReader)(nil)).Elem())
	registerType("io", "Seeker", reflect.TypeOf((*io.Seeker)(nil)).Elem())
	registerType("io", "StringWriter", reflect.TypeOf((*io.StringWriter)(nil)).Elem())
	registerType("io", "WriteCloser", reflect.TypeOf((*io.WriteCloser)(nil)).Elem())
	registerType("io", "WriteSeeker", reflect.TypeOf((*io.WriteSeeker)(nil)).Elem())
	registerType("io", "Writer", reflect.TypeOf((*io.Writer)(nil)).Elem())
	registerType("io", "WriterAt", reflect.TypeOf((*io.WriterAt)(nil)).Elem())
	registerType("io", "WriterTo", reflect.TypeOf((*io.WriterTo)(nil)).Elem())
}

