// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: image/color

package microlisp

import (
	color "image/color"
	"reflect"
)

func register_image_color() {
	registerPackage(
		"image/color",
		map[string]interface{}{
			"CMYKToRGB": color.CMYKToRGB,
			"ModelFunc": color.ModelFunc,
			"RGBToCMYK": color.RGBToCMYK,
			"RGBToYCbCr": color.RGBToYCbCr,
			"YCbCrToRGB": color.YCbCrToRGB,
			"Alpha16Model": color.Alpha16Model,
			"AlphaModel": color.AlphaModel,
			"Black": color.Black,
			"CMYKModel": color.CMYKModel,
			"Gray16Model": color.Gray16Model,
			"GrayModel": color.GrayModel,
			"NRGBA64Model": color.NRGBA64Model,
			"NRGBAModel": color.NRGBAModel,
			"NYCbCrAModel": color.NYCbCrAModel,
			"Opaque": color.Opaque,
			"RGBA64Model": color.RGBA64Model,
			"RGBAModel": color.RGBAModel,
			"Transparent": color.Transparent,
			"White": color.White,
			"YCbCrModel": color.YCbCrModel,
		},
	)
	registerType("image/color", "Alpha", reflect.TypeOf((*color.Alpha)(nil)).Elem())
	registerType("image/color", "Alpha16", reflect.TypeOf((*color.Alpha16)(nil)).Elem())
	registerType("image/color", "CMYK", reflect.TypeOf((*color.CMYK)(nil)).Elem())
	registerType("image/color", "Color", reflect.TypeOf((*color.Color)(nil)).Elem())
	registerType("image/color", "Gray", reflect.TypeOf((*color.Gray)(nil)).Elem())
	registerType("image/color", "Gray16", reflect.TypeOf((*color.Gray16)(nil)).Elem())
	registerType("image/color", "Model", reflect.TypeOf((*color.Model)(nil)).Elem())
	registerType("image/color", "NRGBA", reflect.TypeOf((*color.NRGBA)(nil)).Elem())
	registerType("image/color", "NRGBA64", reflect.TypeOf((*color.NRGBA64)(nil)).Elem())
	registerType("image/color", "NYCbCrA", reflect.TypeOf((*color.NYCbCrA)(nil)).Elem())
	registerType("image/color", "Palette", reflect.TypeOf((*color.Palette)(nil)).Elem())
	registerType("image/color", "RGBA", reflect.TypeOf((*color.RGBA)(nil)).Elem())
	registerType("image/color", "RGBA64", reflect.TypeOf((*color.RGBA64)(nil)).Elem())
	registerType("image/color", "YCbCr", reflect.TypeOf((*color.YCbCr)(nil)).Elem())
}

