// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/token

package microlisp

import (
	token "go/token"
	"reflect"
)

func register_go_token() {
	registerPackage(
		"go/token",
		map[string]interface{}{
			"IsExported": token.IsExported,
			"IsIdentifier": token.IsIdentifier,
			"IsKeyword": token.IsKeyword,
			"Lookup": token.Lookup,
			"NewFileSet": token.NewFileSet,
			"HighestPrec": token.HighestPrec,
			"LowestPrec": token.LowestPrec,
			"UnaryPrec": token.UnaryPrec,
		},
	)
	registerType("go/token", "File", reflect.TypeOf((*token.File)(nil)).Elem())
	registerType("go/token", "FileSet", reflect.TypeOf((*token.FileSet)(nil)).Elem())
	registerType("go/token", "Pos", reflect.TypeOf((*token.Pos)(nil)).Elem())
	registerType("go/token", "Position", reflect.TypeOf((*token.Position)(nil)).Elem())
	registerType("go/token", "Token", reflect.TypeOf((*token.Token)(nil)).Elem())
}

