// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: hash

package microlisp

import (
	hash "hash"
	"reflect"
)

func register_hash() {
	registerType("hash", "Hash", reflect.TypeOf((*hash.Hash)(nil)).Elem())
	registerType("hash", "Hash32", reflect.TypeOf((*hash.Hash32)(nil)).Elem())
	registerType("hash", "Hash64", reflect.TypeOf((*hash.Hash64)(nil)).Elem())
}

