// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: regexp

package microlisp

import (
	regexp "regexp"
	"reflect"
)

func register_regexp() {
	registerPackage(
		"regexp",
		map[string]interface{}{
			"Compile": regexp.Compile,
			"CompilePOSIX": regexp.CompilePOSIX,
			"Match": regexp.Match,
			"MatchReader": regexp.MatchReader,
			"MatchString": regexp.MatchString,
			"MustCompile": regexp.MustCompile,
			"MustCompilePOSIX": regexp.MustCompilePOSIX,
			"QuoteMeta": regexp.QuoteMeta,
		},
	)
	registerType("regexp", "Regexp", reflect.TypeOf((*regexp.Regexp)(nil)).Elem())
}

