// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: sync

package microlisp

import (
	sync "sync"
	"reflect"
)

func register_sync() {
	registerPackage(
		"sync",
		map[string]interface{}{
			"NewCond": sync.NewCond,
			"OnceFunc": sync.OnceFunc,
		},
	)
	registerType("sync", "Cond", reflect.TypeOf((*sync.Cond)(nil)).Elem())
	registerType("sync", "Locker", reflect.TypeOf((*sync.Locker)(nil)).Elem())
	registerType("sync", "Map", reflect.TypeOf((*sync.Map)(nil)).Elem())
	registerType("sync", "Mutex", reflect.TypeOf((*sync.Mutex)(nil)).Elem())
	registerType("sync", "Once", reflect.TypeOf((*sync.Once)(nil)).Elem())
	registerType("sync", "Pool", reflect.TypeOf((*sync.Pool)(nil)).Elem())
	registerType("sync", "RWMutex", reflect.TypeOf((*sync.RWMutex)(nil)).Elem())
	registerType("sync", "WaitGroup", reflect.TypeOf((*sync.WaitGroup)(nil)).Elem())
}

