// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/doc/comment

package microlisp

import (
	comment "go/doc/comment"
	"reflect"
)

func register_go_doc_comment() {
	registerPackage(
		"go/doc/comment",
		map[string]interface{}{
			"DefaultLookupPackage": comment.DefaultLookupPackage,
		},
	)
	registerType("go/doc/comment", "Block", reflect.TypeOf((*comment.Block)(nil)).Elem())
	registerType("go/doc/comment", "Code", reflect.TypeOf((*comment.Code)(nil)).Elem())
	registerType("go/doc/comment", "Doc", reflect.TypeOf((*comment.Doc)(nil)).Elem())
	registerType("go/doc/comment", "DocLink", reflect.TypeOf((*comment.DocLink)(nil)).Elem())
	registerType("go/doc/comment", "Heading", reflect.TypeOf((*comment.Heading)(nil)).Elem())
	registerType("go/doc/comment", "Italic", reflect.TypeOf((*comment.Italic)(nil)).Elem())
	registerType("go/doc/comment", "Link", reflect.TypeOf((*comment.Link)(nil)).Elem())
	registerType("go/doc/comment", "LinkDef", reflect.TypeOf((*comment.LinkDef)(nil)).Elem())
	registerType("go/doc/comment", "List", reflect.TypeOf((*comment.List)(nil)).Elem())
	registerType("go/doc/comment", "ListItem", reflect.TypeOf((*comment.ListItem)(nil)).Elem())
	registerType("go/doc/comment", "Paragraph", reflect.TypeOf((*comment.Paragraph)(nil)).Elem())
	registerType("go/doc/comment", "Parser", reflect.TypeOf((*comment.Parser)(nil)).Elem())
	registerType("go/doc/comment", "Plain", reflect.TypeOf((*comment.Plain)(nil)).Elem())
	registerType("go/doc/comment", "Printer", reflect.TypeOf((*comment.Printer)(nil)).Elem())
	registerType("go/doc/comment", "Text", reflect.TypeOf((*comment.Text)(nil)).Elem())
}

