package microlisp

import (
	"reflect"
)

// GoPackageRegistry maps package name -> symbol name -> reflect.Value.
// Mirrors golisp's gopkg.Packages design for complete stdlib coverage.
var GoPackageRegistry = make(map[string]map[string]reflect.Value)

// GoTypeRegistry maps package name -> type name -> reflect.Type.
// Used for go:new and type introspection.
var GoTypeRegistry = make(map[string]map[string]reflect.Type)

func init() {
	// All stdlib packages are auto-registered by ffi_*.go files.
	// Generated by microlisp/ffi_gen/main.go — see ffi_init.go for the full list.
}

// registerPackage adds all entries to GoPackageRegistry[packageName].
func registerPackage(name string, entries map[string]interface{}) {
	pkg, ok := GoPackageRegistry[name]
	if !ok {
		pkg = make(map[string]reflect.Value)
		GoPackageRegistry[name] = pkg
	}
	for sym, fn := range entries {
		pkg[sym] = reflect.ValueOf(fn)
	}
}

// registerType registers a Go type for use with go:new and type introspection.
func registerType(pkg, name string, t reflect.Type) {
	if _, ok := GoTypeRegistry[pkg]; !ok {
		GoTypeRegistry[pkg] = make(map[string]reflect.Type)
	}
	GoTypeRegistry[pkg][name] = t
}
