// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: sort

package microlisp

import (
	sort "sort"
	"reflect"
)

func register_sort() {
	registerPackage(
		"sort",
		map[string]interface{}{
			"Find": sort.Find,
			"Float64s": sort.Float64s,
			"Float64sAreSorted": sort.Float64sAreSorted,
			"Ints": sort.Ints,
			"IntsAreSorted": sort.IntsAreSorted,
			"IsSorted": sort.IsSorted,
			"Reverse": sort.Reverse,
			"Search": sort.Search,
			"SearchFloat64s": sort.SearchFloat64s,
			"SearchInts": sort.SearchInts,
			"SearchStrings": sort.SearchStrings,
			"Slice": sort.Slice,
			"SliceIsSorted": sort.SliceIsSorted,
			"SliceStable": sort.SliceStable,
			"Sort": sort.Sort,
			"Stable": sort.Stable,
			"Strings": sort.Strings,
			"StringsAreSorted": sort.StringsAreSorted,
		},
	)
	registerType("sort", "Float64Slice", reflect.TypeOf((*sort.Float64Slice)(nil)).Elem())
	registerType("sort", "IntSlice", reflect.TypeOf((*sort.IntSlice)(nil)).Elem())
	registerType("sort", "Interface", reflect.TypeOf((*sort.Interface)(nil)).Elem())
	registerType("sort", "StringSlice", reflect.TypeOf((*sort.StringSlice)(nil)).Elem())
}

