// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/rpc

package microlisp

import (
	rpc "net/rpc"
	"reflect"
)

func register_net_rpc() {
	registerPackage(
		"net/rpc",
		map[string]interface{}{
			"Accept": rpc.Accept,
			"Dial": rpc.Dial,
			"DialHTTP": rpc.DialHTTP,
			"DialHTTPPath": rpc.DialHTTPPath,
			"HandleHTTP": rpc.HandleHTTP,
			"NewClient": rpc.NewClient,
			"NewClientWithCodec": rpc.NewClientWithCodec,
			"NewServer": rpc.NewServer,
			"Register": rpc.Register,
			"RegisterName": rpc.RegisterName,
			"ServeCodec": rpc.ServeCodec,
			"ServeConn": rpc.ServeConn,
			"ServeRequest": rpc.ServeRequest,
			"DefaultServer": rpc.DefaultServer,
			"ErrShutdown": rpc.ErrShutdown,
			"DefaultDebugPath": rpc.DefaultDebugPath,
			"DefaultRPCPath": rpc.DefaultRPCPath,
		},
	)
	registerType("net/rpc", "Call", reflect.TypeOf((*rpc.Call)(nil)).Elem())
	registerType("net/rpc", "Client", reflect.TypeOf((*rpc.Client)(nil)).Elem())
	registerType("net/rpc", "ClientCodec", reflect.TypeOf((*rpc.ClientCodec)(nil)).Elem())
	registerType("net/rpc", "Request", reflect.TypeOf((*rpc.Request)(nil)).Elem())
	registerType("net/rpc", "Response", reflect.TypeOf((*rpc.Response)(nil)).Elem())
	registerType("net/rpc", "Server", reflect.TypeOf((*rpc.Server)(nil)).Elem())
	registerType("net/rpc", "ServerCodec", reflect.TypeOf((*rpc.ServerCodec)(nil)).Elem())
	registerType("net/rpc", "ServerError", reflect.TypeOf((*rpc.ServerError)(nil)).Elem())
}

