// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: runtime/metrics

package microlisp

import (
	metrics "runtime/metrics"
	"reflect"
)

func register_runtime_metrics() {
	registerPackage(
		"runtime/metrics",
		map[string]interface{}{
			"All": metrics.All,
			"Read": metrics.Read,
		},
	)
	registerType("runtime/metrics", "Description", reflect.TypeOf((*metrics.Description)(nil)).Elem())
	registerType("runtime/metrics", "Float64Histogram", reflect.TypeOf((*metrics.Float64Histogram)(nil)).Elem())
	registerType("runtime/metrics", "Sample", reflect.TypeOf((*metrics.Sample)(nil)).Elem())
	registerType("runtime/metrics", "Value", reflect.TypeOf((*metrics.Value)(nil)).Elem())
	registerType("runtime/metrics", "ValueKind", reflect.TypeOf((*metrics.ValueKind)(nil)).Elem())
}

