// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net

package microlisp

import (
	net "net"
	"reflect"
)

func register_net() {
	registerPackage(
		"net",
		map[string]interface{}{
			"CIDRMask": net.CIDRMask,
			"Dial": net.Dial,
			"DialIP": net.DialIP,
			"DialTCP": net.DialTCP,
			"DialTimeout": net.DialTimeout,
			"DialUDP": net.DialUDP,
			"DialUnix": net.DialUnix,
			"FileConn": net.FileConn,
			"FileListener": net.FileListener,
			"FilePacketConn": net.FilePacketConn,
			"IPv4": net.IPv4,
			"IPv4Mask": net.IPv4Mask,
			"InterfaceAddrs": net.InterfaceAddrs,
			"InterfaceByIndex": net.InterfaceByIndex,
			"InterfaceByName": net.InterfaceByName,
			"Interfaces": net.Interfaces,
			"JoinHostPort": net.JoinHostPort,
			"Listen": net.Listen,
			"ListenIP": net.ListenIP,
			"ListenMulticastUDP": net.ListenMulticastUDP,
			"ListenPacket": net.ListenPacket,
			"ListenTCP": net.ListenTCP,
			"ListenUDP": net.ListenUDP,
			"ListenUnix": net.ListenUnix,
			"ListenUnixgram": net.ListenUnixgram,
			"LookupAddr": net.LookupAddr,
			"LookupCNAME": net.LookupCNAME,
			"LookupHost": net.LookupHost,
			"LookupIP": net.LookupIP,
			"LookupMX": net.LookupMX,
			"LookupNS": net.LookupNS,
			"LookupPort": net.LookupPort,
			"LookupSRV": net.LookupSRV,
			"LookupTXT": net.LookupTXT,
			"ParseCIDR": net.ParseCIDR,
			"ParseIP": net.ParseIP,
			"ParseMAC": net.ParseMAC,
			"Pipe": net.Pipe,
			"ResolveIPAddr": net.ResolveIPAddr,
			"ResolveTCPAddr": net.ResolveTCPAddr,
			"ResolveUDPAddr": net.ResolveUDPAddr,
			"ResolveUnixAddr": net.ResolveUnixAddr,
			"SplitHostPort": net.SplitHostPort,
			"TCPAddrFromAddrPort": net.TCPAddrFromAddrPort,
			"UDPAddrFromAddrPort": net.UDPAddrFromAddrPort,
			"DefaultResolver": net.DefaultResolver,
			"ErrClosed": net.ErrClosed,
			"ErrWriteToConnected": net.ErrWriteToConnected,
			"IPv4allrouter": net.IPv4allrouter,
			"IPv4allsys": net.IPv4allsys,
			"IPv4bcast": net.IPv4bcast,
			"IPv4zero": net.IPv4zero,
			"IPv6interfacelocalallnodes": net.IPv6interfacelocalallnodes,
			"IPv6linklocalallnodes": net.IPv6linklocalallnodes,
			"IPv6linklocalallrouters": net.IPv6linklocalallrouters,
			"IPv6loopback": net.IPv6loopback,
			"IPv6unspecified": net.IPv6unspecified,
			"IPv6zero": net.IPv6zero,
			"FlagBroadcast": net.FlagBroadcast,
			"FlagLoopback": net.FlagLoopback,
			"FlagMulticast": net.FlagMulticast,
			"FlagPointToPoint": net.FlagPointToPoint,
			"FlagRunning": net.FlagRunning,
			"FlagUp": net.FlagUp,
			"IPv4len": net.IPv4len,
			"IPv6len": net.IPv6len,
		},
	)
	registerType("net", "Addr", reflect.TypeOf((*net.Addr)(nil)).Elem())
	registerType("net", "AddrError", reflect.TypeOf((*net.AddrError)(nil)).Elem())
	registerType("net", "Buffers", reflect.TypeOf((*net.Buffers)(nil)).Elem())
	registerType("net", "Conn", reflect.TypeOf((*net.Conn)(nil)).Elem())
	registerType("net", "DNSConfigError", reflect.TypeOf((*net.DNSConfigError)(nil)).Elem())
	registerType("net", "DNSError", reflect.TypeOf((*net.DNSError)(nil)).Elem())
	registerType("net", "Dialer", reflect.TypeOf((*net.Dialer)(nil)).Elem())
	registerType("net", "Error", reflect.TypeOf((*net.Error)(nil)).Elem())
	registerType("net", "Flags", reflect.TypeOf((*net.Flags)(nil)).Elem())
	registerType("net", "HardwareAddr", reflect.TypeOf((*net.HardwareAddr)(nil)).Elem())
	registerType("net", "IP", reflect.TypeOf((*net.IP)(nil)).Elem())
	registerType("net", "IPAddr", reflect.TypeOf((*net.IPAddr)(nil)).Elem())
	registerType("net", "IPConn", reflect.TypeOf((*net.IPConn)(nil)).Elem())
	registerType("net", "IPMask", reflect.TypeOf((*net.IPMask)(nil)).Elem())
	registerType("net", "IPNet", reflect.TypeOf((*net.IPNet)(nil)).Elem())
	registerType("net", "Interface", reflect.TypeOf((*net.Interface)(nil)).Elem())
	registerType("net", "InvalidAddrError", reflect.TypeOf((*net.InvalidAddrError)(nil)).Elem())
	registerType("net", "ListenConfig", reflect.TypeOf((*net.ListenConfig)(nil)).Elem())
	registerType("net", "Listener", reflect.TypeOf((*net.Listener)(nil)).Elem())
	registerType("net", "MX", reflect.TypeOf((*net.MX)(nil)).Elem())
	registerType("net", "NS", reflect.TypeOf((*net.NS)(nil)).Elem())
	registerType("net", "OpError", reflect.TypeOf((*net.OpError)(nil)).Elem())
	registerType("net", "PacketConn", reflect.TypeOf((*net.PacketConn)(nil)).Elem())
	registerType("net", "ParseError", reflect.TypeOf((*net.ParseError)(nil)).Elem())
	registerType("net", "Resolver", reflect.TypeOf((*net.Resolver)(nil)).Elem())
	registerType("net", "SRV", reflect.TypeOf((*net.SRV)(nil)).Elem())
	registerType("net", "TCPAddr", reflect.TypeOf((*net.TCPAddr)(nil)).Elem())
	registerType("net", "TCPConn", reflect.TypeOf((*net.TCPConn)(nil)).Elem())
	registerType("net", "TCPListener", reflect.TypeOf((*net.TCPListener)(nil)).Elem())
	registerType("net", "UDPAddr", reflect.TypeOf((*net.UDPAddr)(nil)).Elem())
	registerType("net", "UDPConn", reflect.TypeOf((*net.UDPConn)(nil)).Elem())
	registerType("net", "UnixAddr", reflect.TypeOf((*net.UnixAddr)(nil)).Elem())
	registerType("net", "UnixConn", reflect.TypeOf((*net.UnixConn)(nil)).Elem())
	registerType("net", "UnixListener", reflect.TypeOf((*net.UnixListener)(nil)).Elem())
	registerType("net", "UnknownNetworkError", reflect.TypeOf((*net.UnknownNetworkError)(nil)).Elem())
}

