// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: runtime/pprof

package microlisp

import (
	pprof "runtime/pprof"
	"reflect"
)

func register_runtime_pprof() {
	registerPackage(
		"runtime/pprof",
		map[string]interface{}{
			"Do": pprof.Do,
			"ForLabels": pprof.ForLabels,
			"Label": pprof.Label,
			"Labels": pprof.Labels,
			"Lookup": pprof.Lookup,
			"NewProfile": pprof.NewProfile,
			"Profiles": pprof.Profiles,
			"SetGoroutineLabels": pprof.SetGoroutineLabels,
			"StartCPUProfile": pprof.StartCPUProfile,
			"StopCPUProfile": pprof.StopCPUProfile,
			"WithLabels": pprof.WithLabels,
			"WriteHeapProfile": pprof.WriteHeapProfile,
		},
	)
	registerType("runtime/pprof", "LabelSet", reflect.TypeOf((*pprof.LabelSet)(nil)).Elem())
	registerType("runtime/pprof", "Profile", reflect.TypeOf((*pprof.Profile)(nil)).Elem())
}

