// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: hash/crc32

package microlisp

import (
	crc32 "hash/crc32"
	"reflect"
)

func register_hash_crc32() {
	registerPackage(
		"hash/crc32",
		map[string]interface{}{
			"Checksum": crc32.Checksum,
			"ChecksumIEEE": crc32.ChecksumIEEE,
			"MakeTable": crc32.MakeTable,
			"New": crc32.New,
			"NewIEEE": crc32.NewIEEE,
			"Update": crc32.Update,
			"IEEETable": crc32.IEEETable,
			"Castagnoli": crc32.Castagnoli,
			"IEEE": crc32.IEEE,
			"Koopman": crc32.Koopman,
			"Size": crc32.Size,
		},
	)
	registerType("hash/crc32", "Table", reflect.TypeOf((*crc32.Table)(nil)).Elem())
}

