// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: database/sql/driver

package microlisp

import (
	driver "database/sql/driver"
	"reflect"
)

func register_database_sql_driver() {
	registerPackage(
		"database/sql/driver",
		map[string]interface{}{
			"IsScanValue": driver.IsScanValue,
			"IsValue": driver.IsValue,
			"Bool": driver.Bool,
			"DefaultParameterConverter": driver.DefaultParameterConverter,
			"ErrBadConn": driver.ErrBadConn,
			"ErrRemoveArgument": driver.ErrRemoveArgument,
			"ErrSkip": driver.ErrSkip,
			"Int32": driver.Int32,
			"ResultNoRows": driver.ResultNoRows,
			"String": driver.String,
		},
	)
	registerType("database/sql/driver", "ColumnConverter", reflect.TypeOf((*driver.ColumnConverter)(nil)).Elem())
	registerType("database/sql/driver", "Conn", reflect.TypeOf((*driver.Conn)(nil)).Elem())
	registerType("database/sql/driver", "ConnBeginTx", reflect.TypeOf((*driver.ConnBeginTx)(nil)).Elem())
	registerType("database/sql/driver", "ConnPrepareContext", reflect.TypeOf((*driver.ConnPrepareContext)(nil)).Elem())
	registerType("database/sql/driver", "Connector", reflect.TypeOf((*driver.Connector)(nil)).Elem())
	registerType("database/sql/driver", "Driver", reflect.TypeOf((*driver.Driver)(nil)).Elem())
	registerType("database/sql/driver", "DriverContext", reflect.TypeOf((*driver.DriverContext)(nil)).Elem())
	registerType("database/sql/driver", "Execer", reflect.TypeOf((*driver.Execer)(nil)).Elem())
	registerType("database/sql/driver", "ExecerContext", reflect.TypeOf((*driver.ExecerContext)(nil)).Elem())
	registerType("database/sql/driver", "IsolationLevel", reflect.TypeOf((*driver.IsolationLevel)(nil)).Elem())
	registerType("database/sql/driver", "NamedValue", reflect.TypeOf((*driver.NamedValue)(nil)).Elem())
	registerType("database/sql/driver", "NamedValueChecker", reflect.TypeOf((*driver.NamedValueChecker)(nil)).Elem())
	registerType("database/sql/driver", "NotNull", reflect.TypeOf((*driver.NotNull)(nil)).Elem())
	registerType("database/sql/driver", "Null", reflect.TypeOf((*driver.Null)(nil)).Elem())
	registerType("database/sql/driver", "Pinger", reflect.TypeOf((*driver.Pinger)(nil)).Elem())
	registerType("database/sql/driver", "Queryer", reflect.TypeOf((*driver.Queryer)(nil)).Elem())
	registerType("database/sql/driver", "QueryerContext", reflect.TypeOf((*driver.QueryerContext)(nil)).Elem())
	registerType("database/sql/driver", "Result", reflect.TypeOf((*driver.Result)(nil)).Elem())
	registerType("database/sql/driver", "Rows", reflect.TypeOf((*driver.Rows)(nil)).Elem())
	registerType("database/sql/driver", "RowsAffected", reflect.TypeOf((*driver.RowsAffected)(nil)).Elem())
	registerType("database/sql/driver", "RowsColumnTypeDatabaseTypeName", reflect.TypeOf((*driver.RowsColumnTypeDatabaseTypeName)(nil)).Elem())
	registerType("database/sql/driver", "RowsColumnTypeLength", reflect.TypeOf((*driver.RowsColumnTypeLength)(nil)).Elem())
	registerType("database/sql/driver", "RowsColumnTypeNullable", reflect.TypeOf((*driver.RowsColumnTypeNullable)(nil)).Elem())
	registerType("database/sql/driver", "RowsColumnTypePrecisionScale", reflect.TypeOf((*driver.RowsColumnTypePrecisionScale)(nil)).Elem())
	registerType("database/sql/driver", "RowsColumnTypeScanType", reflect.TypeOf((*driver.RowsColumnTypeScanType)(nil)).Elem())
	registerType("database/sql/driver", "RowsNextResultSet", reflect.TypeOf((*driver.RowsNextResultSet)(nil)).Elem())
	registerType("database/sql/driver", "SessionResetter", reflect.TypeOf((*driver.SessionResetter)(nil)).Elem())
	registerType("database/sql/driver", "Stmt", reflect.TypeOf((*driver.Stmt)(nil)).Elem())
	registerType("database/sql/driver", "StmtExecContext", reflect.TypeOf((*driver.StmtExecContext)(nil)).Elem())
	registerType("database/sql/driver", "StmtQueryContext", reflect.TypeOf((*driver.StmtQueryContext)(nil)).Elem())
	registerType("database/sql/driver", "Tx", reflect.TypeOf((*driver.Tx)(nil)).Elem())
	registerType("database/sql/driver", "TxOptions", reflect.TypeOf((*driver.TxOptions)(nil)).Elem())
	registerType("database/sql/driver", "Validator", reflect.TypeOf((*driver.Validator)(nil)).Elem())
	registerType("database/sql/driver", "Value", reflect.TypeOf((*driver.Value)(nil)).Elem())
	registerType("database/sql/driver", "ValueConverter", reflect.TypeOf((*driver.ValueConverter)(nil)).Elem())
	registerType("database/sql/driver", "Valuer", reflect.TypeOf((*driver.Valuer)(nil)).Elem())
}

