// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/asn1

package microlisp

import (
	asn1 "encoding/asn1"
	"reflect"
)

func register_encoding_asn1() {
	registerPackage(
		"encoding/asn1",
		map[string]interface{}{
			"Marshal": asn1.Marshal,
			"MarshalWithParams": asn1.MarshalWithParams,
			"Unmarshal": asn1.Unmarshal,
			"UnmarshalWithParams": asn1.UnmarshalWithParams,
			"NullBytes": asn1.NullBytes,
			"NullRawValue": asn1.NullRawValue,
			"ClassApplication": asn1.ClassApplication,
			"ClassContextSpecific": asn1.ClassContextSpecific,
			"ClassPrivate": asn1.ClassPrivate,
			"ClassUniversal": asn1.ClassUniversal,
			"TagBMPString": asn1.TagBMPString,
			"TagBitString": asn1.TagBitString,
			"TagBoolean": asn1.TagBoolean,
			"TagEnum": asn1.TagEnum,
			"TagGeneralString": asn1.TagGeneralString,
			"TagGeneralizedTime": asn1.TagGeneralizedTime,
			"TagIA5String": asn1.TagIA5String,
			"TagInteger": asn1.TagInteger,
			"TagNull": asn1.TagNull,
			"TagNumericString": asn1.TagNumericString,
			"TagOID": asn1.TagOID,
			"TagOctetString": asn1.TagOctetString,
			"TagPrintableString": asn1.TagPrintableString,
			"TagSequence": asn1.TagSequence,
			"TagSet": asn1.TagSet,
			"TagT61String": asn1.TagT61String,
			"TagUTCTime": asn1.TagUTCTime,
			"TagUTF8String": asn1.TagUTF8String,
		},
	)
	registerType("encoding/asn1", "BitString", reflect.TypeOf((*asn1.BitString)(nil)).Elem())
	registerType("encoding/asn1", "Enumerated", reflect.TypeOf((*asn1.Enumerated)(nil)).Elem())
	registerType("encoding/asn1", "Flag", reflect.TypeOf((*asn1.Flag)(nil)).Elem())
	registerType("encoding/asn1", "ObjectIdentifier", reflect.TypeOf((*asn1.ObjectIdentifier)(nil)).Elem())
	registerType("encoding/asn1", "RawContent", reflect.TypeOf((*asn1.RawContent)(nil)).Elem())
	registerType("encoding/asn1", "RawValue", reflect.TypeOf((*asn1.RawValue)(nil)).Elem())
	registerType("encoding/asn1", "StructuralError", reflect.TypeOf((*asn1.StructuralError)(nil)).Elem())
	registerType("encoding/asn1", "SyntaxError", reflect.TypeOf((*asn1.SyntaxError)(nil)).Elem())
}

