// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: debug/gosym

package microlisp

import (
	gosym "debug/gosym"
	"reflect"
)

func register_debug_gosym() {
	registerPackage(
		"debug/gosym",
		map[string]interface{}{
			"NewLineTable": gosym.NewLineTable,
			"NewTable": gosym.NewTable,
		},
	)
	registerType("debug/gosym", "DecodingError", reflect.TypeOf((*gosym.DecodingError)(nil)).Elem())
	registerType("debug/gosym", "Func", reflect.TypeOf((*gosym.Func)(nil)).Elem())
	registerType("debug/gosym", "LineTable", reflect.TypeOf((*gosym.LineTable)(nil)).Elem())
	registerType("debug/gosym", "Obj", reflect.TypeOf((*gosym.Obj)(nil)).Elem())
	registerType("debug/gosym", "Sym", reflect.TypeOf((*gosym.Sym)(nil)).Elem())
	registerType("debug/gosym", "Table", reflect.TypeOf((*gosym.Table)(nil)).Elem())
	registerType("debug/gosym", "UnknownFileError", reflect.TypeOf((*gosym.UnknownFileError)(nil)).Elem())
	registerType("debug/gosym", "UnknownLineError", reflect.TypeOf((*gosym.UnknownLineError)(nil)).Elem())
}

