// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: context

package microlisp

import (
	context "context"
	"reflect"
)

func register_context() {
	registerPackage(
		"context",
		map[string]interface{}{
			"AfterFunc": context.AfterFunc,
			"Background": context.Background,
			"Cause": context.Cause,
			"TODO": context.TODO,
			"WithCancel": context.WithCancel,
			"WithCancelCause": context.WithCancelCause,
			"WithDeadline": context.WithDeadline,
			"WithDeadlineCause": context.WithDeadlineCause,
			"WithTimeout": context.WithTimeout,
			"WithTimeoutCause": context.WithTimeoutCause,
			"WithValue": context.WithValue,
			"WithoutCancel": context.WithoutCancel,
			"Canceled": context.Canceled,
			"DeadlineExceeded": context.DeadlineExceeded,
		},
	)
	registerType("context", "CancelCauseFunc", reflect.TypeOf((*context.CancelCauseFunc)(nil)).Elem())
	registerType("context", "CancelFunc", reflect.TypeOf((*context.CancelFunc)(nil)).Elem())
	registerType("context", "Context", reflect.TypeOf((*context.Context)(nil)).Elem())
}

