// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: embed

package microlisp

import (
	embed "embed"
	"reflect"
)

func register_embed() {
	registerType("embed", "FS", reflect.TypeOf((*embed.FS)(nil)).Elem())
}

