// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: runtime

package microlisp

import (
	runtime "runtime"
	"reflect"
)

func register_runtime() {
	registerPackage(
		"runtime",
		map[string]interface{}{
			"BlockProfile": runtime.BlockProfile,
			"Breakpoint": runtime.Breakpoint,
			"CPUProfile": runtime.CPUProfile,
			"Caller": runtime.Caller,
			"Callers": runtime.Callers,
			"CallersFrames": runtime.CallersFrames,
			"FuncForPC": runtime.FuncForPC,
			"GC": runtime.GC,
			"GOMAXPROCS": runtime.GOMAXPROCS,
			"GOROOT": runtime.GOROOT,
			"Goexit": runtime.Goexit,
			"GoroutineProfile": runtime.GoroutineProfile,
			"Gosched": runtime.Gosched,
			"KeepAlive": runtime.KeepAlive,
			"LockOSThread": runtime.LockOSThread,
			"MemProfile": runtime.MemProfile,
			"MutexProfile": runtime.MutexProfile,
			"NumCPU": runtime.NumCPU,
			"NumCgoCall": runtime.NumCgoCall,
			"NumGoroutine": runtime.NumGoroutine,
			"ReadMemStats": runtime.ReadMemStats,
			"ReadTrace": runtime.ReadTrace,
			"SetBlockProfileRate": runtime.SetBlockProfileRate,
			"SetCPUProfileRate": runtime.SetCPUProfileRate,
			"SetCgoTraceback": runtime.SetCgoTraceback,
			"SetFinalizer": runtime.SetFinalizer,
			"SetMutexProfileFraction": runtime.SetMutexProfileFraction,
			"Stack": runtime.Stack,
			"StartTrace": runtime.StartTrace,
			"StopTrace": runtime.StopTrace,
			"ThreadCreateProfile": runtime.ThreadCreateProfile,
			"UnlockOSThread": runtime.UnlockOSThread,
			"Version": runtime.Version,
			"MemProfileRate": runtime.MemProfileRate,
			"Compiler": runtime.Compiler,
			"GOARCH": runtime.GOARCH,
			"GOOS": runtime.GOOS,
		},
	)
	registerType("runtime", "BlockProfileRecord", reflect.TypeOf((*runtime.BlockProfileRecord)(nil)).Elem())
	registerType("runtime", "Error", reflect.TypeOf((*runtime.Error)(nil)).Elem())
	registerType("runtime", "Frame", reflect.TypeOf((*runtime.Frame)(nil)).Elem())
	registerType("runtime", "Frames", reflect.TypeOf((*runtime.Frames)(nil)).Elem())
	registerType("runtime", "Func", reflect.TypeOf((*runtime.Func)(nil)).Elem())
	registerType("runtime", "MemProfileRecord", reflect.TypeOf((*runtime.MemProfileRecord)(nil)).Elem())
	registerType("runtime", "MemStats", reflect.TypeOf((*runtime.MemStats)(nil)).Elem())
	registerType("runtime", "PanicNilError", reflect.TypeOf((*runtime.PanicNilError)(nil)).Elem())
	registerType("runtime", "Pinner", reflect.TypeOf((*runtime.Pinner)(nil)).Elem())
	registerType("runtime", "StackRecord", reflect.TypeOf((*runtime.StackRecord)(nil)).Elem())
	registerType("runtime", "TypeAssertionError", reflect.TypeOf((*runtime.TypeAssertionError)(nil)).Elem())
}

