// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: hash/adler32

package microlisp

import (
	adler32 "hash/adler32"
)

func register_hash_adler32() {
	registerPackage(
		"hash/adler32",
		map[string]interface{}{
			"Checksum": adler32.Checksum,
			"New": adler32.New,
			"Size": adler32.Size,
		},
	)
}

