// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: testing

package microlisp

import (
	testing "testing"
	"reflect"
)

func register_testing() {
	registerPackage(
		"testing",
		map[string]interface{}{
			"AllocsPerRun": testing.AllocsPerRun,
			"Benchmark": testing.Benchmark,
			"CoverMode": testing.CoverMode,
			"Coverage": testing.Coverage,
			"Init": testing.Init,
			"Main": testing.Main,
			"MainStart": testing.MainStart,
			"RegisterCover": testing.RegisterCover,
			"RunBenchmarks": testing.RunBenchmarks,
			"RunExamples": testing.RunExamples,
			"RunTests": testing.RunTests,
			"Short": testing.Short,
			"Testing": testing.Testing,
			"Verbose": testing.Verbose,
		},
	)
	registerType("testing", "B", reflect.TypeOf((*testing.B)(nil)).Elem())
	registerType("testing", "BenchmarkResult", reflect.TypeOf((*testing.BenchmarkResult)(nil)).Elem())
	registerType("testing", "Cover", reflect.TypeOf((*testing.Cover)(nil)).Elem())
	registerType("testing", "CoverBlock", reflect.TypeOf((*testing.CoverBlock)(nil)).Elem())
	registerType("testing", "F", reflect.TypeOf((*testing.F)(nil)).Elem())
	registerType("testing", "InternalBenchmark", reflect.TypeOf((*testing.InternalBenchmark)(nil)).Elem())
	registerType("testing", "InternalExample", reflect.TypeOf((*testing.InternalExample)(nil)).Elem())
	registerType("testing", "InternalFuzzTarget", reflect.TypeOf((*testing.InternalFuzzTarget)(nil)).Elem())
	registerType("testing", "InternalTest", reflect.TypeOf((*testing.InternalTest)(nil)).Elem())
	registerType("testing", "M", reflect.TypeOf((*testing.M)(nil)).Elem())
	registerType("testing", "PB", reflect.TypeOf((*testing.PB)(nil)).Elem())
	registerType("testing", "T", reflect.TypeOf((*testing.T)(nil)).Elem())
	registerType("testing", "TB", reflect.TypeOf((*testing.TB)(nil)).Elem())
}

