// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: reflect

package microlisp

import (
	reflectPkg "reflect"
)

func register_reflect() {
	registerPackage(
		"reflect",
		map[string]interface{}{
			"Append": reflectPkg.Append,
			"AppendSlice": reflectPkg.AppendSlice,
			"ArrayOf": reflectPkg.ArrayOf,
			"ChanOf": reflectPkg.ChanOf,
			"Copy": reflectPkg.Copy,
			"DeepEqual": reflectPkg.DeepEqual,
			"FuncOf": reflectPkg.FuncOf,
			"Indirect": reflectPkg.Indirect,
			"MakeChan": reflectPkg.MakeChan,
			"MakeFunc": reflectPkg.MakeFunc,
			"MakeMap": reflectPkg.MakeMap,
			"MakeMapWithSize": reflectPkg.MakeMapWithSize,
			"MakeSlice": reflectPkg.MakeSlice,
			"MapOf": reflectPkg.MapOf,
			"New": reflectPkg.New,
			"NewAt": reflectPkg.NewAt,
			"PointerTo": reflectPkg.PointerTo,
			"PtrTo": reflectPkg.PtrTo,
			"Select": reflectPkg.Select,
			"SliceOf": reflectPkg.SliceOf,
			"StructOf": reflectPkg.StructOf,
			"Swapper": reflectPkg.Swapper,
			"TypeOf": reflectPkg.TypeOf,
			"ValueOf": reflectPkg.ValueOf,
			"VisibleFields": reflectPkg.VisibleFields,
			"Zero": reflectPkg.Zero,
			"Array": reflectPkg.Array,
			"Bool": reflectPkg.Bool,
			"BothDir": reflectPkg.BothDir,
			"Chan": reflectPkg.Chan,
			"Complex128": reflectPkg.Complex128,
			"Complex64": reflectPkg.Complex64,
			"Float32": reflectPkg.Float32,
			"Float64": reflectPkg.Float64,
			"Func": reflectPkg.Func,
			"Int": reflectPkg.Int,
			"Int16": reflectPkg.Int16,
			"Int32": reflectPkg.Int32,
			"Int64": reflectPkg.Int64,
			"Int8": reflectPkg.Int8,
			"Interface": reflectPkg.Interface,
			"Invalid": reflectPkg.Invalid,
			"Map": reflectPkg.Map,
			"Pointer": reflectPkg.Pointer,
			"Ptr": reflectPkg.Ptr,
			"RecvDir": reflectPkg.RecvDir,
			"SelectDefault": reflectPkg.SelectDefault,
			"SelectRecv": reflectPkg.SelectRecv,
			"SelectSend": reflectPkg.SelectSend,
			"SendDir": reflectPkg.SendDir,
			"Slice": reflectPkg.Slice,
			"String": reflectPkg.String,
			"Struct": reflectPkg.Struct,
			"Uint": reflectPkg.Uint,
			"Uint16": reflectPkg.Uint16,
			"Uint32": reflectPkg.Uint32,
			"Uint64": reflectPkg.Uint64,
			"Uint8": reflectPkg.Uint8,
			"Uintptr": reflectPkg.Uintptr,
			"UnsafePointer": reflectPkg.UnsafePointer,
		},
	)
}

