// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: log

package microlisp

import (
	log "log"
	"reflect"
)

func register_log() {
	registerPackage(
		"log",
		map[string]interface{}{
			"Default": log.Default,
			"Fatal": log.Fatal,
			"Fatalf": log.Fatalf,
			"Fatalln": log.Fatalln,
			"Flags": log.Flags,
			"New": log.New,
			"Output": log.Output,
			"Panic": log.Panic,
			"Panicf": log.Panicf,
			"Panicln": log.Panicln,
			"Prefix": log.Prefix,
			"Print": log.Print,
			"Printf": log.Printf,
			"Println": log.Println,
			"SetFlags": log.SetFlags,
			"SetOutput": log.SetOutput,
			"SetPrefix": log.SetPrefix,
			"Writer": log.Writer,
			"LUTC": log.LUTC,
			"Ldate": log.Ldate,
			"Llongfile": log.Llongfile,
			"Lmicroseconds": log.Lmicroseconds,
			"Lmsgprefix": log.Lmsgprefix,
			"Lshortfile": log.Lshortfile,
			"LstdFlags": log.LstdFlags,
			"Ltime": log.Ltime,
		},
	)
	registerType("log", "Logger", reflect.TypeOf((*log.Logger)(nil)).Elem())
}

