// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/ed25519

package microlisp

import (
	ed25519 "crypto/ed25519"
	"reflect"
)

func register_crypto_ed25519() {
	registerPackage(
		"crypto/ed25519",
		map[string]interface{}{
			"GenerateKey": ed25519.GenerateKey,
			"NewKeyFromSeed": ed25519.NewKeyFromSeed,
			"Sign": ed25519.Sign,
			"Verify": ed25519.Verify,
			"VerifyWithOptions": ed25519.VerifyWithOptions,
			"PrivateKeySize": ed25519.PrivateKeySize,
			"PublicKeySize": ed25519.PublicKeySize,
			"SeedSize": ed25519.SeedSize,
			"SignatureSize": ed25519.SignatureSize,
		},
	)
	registerType("crypto/ed25519", "Options", reflect.TypeOf((*ed25519.Options)(nil)).Elem())
	registerType("crypto/ed25519", "PrivateKey", reflect.TypeOf((*ed25519.PrivateKey)(nil)).Elem())
	registerType("crypto/ed25519", "PublicKey", reflect.TypeOf((*ed25519.PublicKey)(nil)).Elem())
}

