// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/ecdh

package microlisp

import (
	ecdh "crypto/ecdh"
	"reflect"
)

func register_crypto_ecdh() {
	registerPackage(
		"crypto/ecdh",
		map[string]interface{}{
			"P256": ecdh.P256,
			"P384": ecdh.P384,
			"P521": ecdh.P521,
			"X25519": ecdh.X25519,
		},
	)
	registerType("crypto/ecdh", "Curve", reflect.TypeOf((*ecdh.Curve)(nil)).Elem())
	registerType("crypto/ecdh", "PrivateKey", reflect.TypeOf((*ecdh.PrivateKey)(nil)).Elem())
	registerType("crypto/ecdh", "PublicKey", reflect.TypeOf((*ecdh.PublicKey)(nil)).Elem())
}

