// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: text/template/parse

package microlisp

import (
	parse "text/template/parse"
	"reflect"
)

func register_text_template_parse() {
	registerPackage(
		"text/template/parse",
		map[string]interface{}{
			"IsEmptyTree": parse.IsEmptyTree,
			"New": parse.New,
			"NewIdentifier": parse.NewIdentifier,
			"Parse": parse.Parse,
		},
	)
	registerType("text/template/parse", "ActionNode", reflect.TypeOf((*parse.ActionNode)(nil)).Elem())
	registerType("text/template/parse", "BoolNode", reflect.TypeOf((*parse.BoolNode)(nil)).Elem())
	registerType("text/template/parse", "BranchNode", reflect.TypeOf((*parse.BranchNode)(nil)).Elem())
	registerType("text/template/parse", "BreakNode", reflect.TypeOf((*parse.BreakNode)(nil)).Elem())
	registerType("text/template/parse", "ChainNode", reflect.TypeOf((*parse.ChainNode)(nil)).Elem())
	registerType("text/template/parse", "CommandNode", reflect.TypeOf((*parse.CommandNode)(nil)).Elem())
	registerType("text/template/parse", "CommentNode", reflect.TypeOf((*parse.CommentNode)(nil)).Elem())
	registerType("text/template/parse", "ContinueNode", reflect.TypeOf((*parse.ContinueNode)(nil)).Elem())
	registerType("text/template/parse", "DotNode", reflect.TypeOf((*parse.DotNode)(nil)).Elem())
	registerType("text/template/parse", "FieldNode", reflect.TypeOf((*parse.FieldNode)(nil)).Elem())
	registerType("text/template/parse", "IdentifierNode", reflect.TypeOf((*parse.IdentifierNode)(nil)).Elem())
	registerType("text/template/parse", "IfNode", reflect.TypeOf((*parse.IfNode)(nil)).Elem())
	registerType("text/template/parse", "ListNode", reflect.TypeOf((*parse.ListNode)(nil)).Elem())
	registerType("text/template/parse", "Mode", reflect.TypeOf((*parse.Mode)(nil)).Elem())
	registerType("text/template/parse", "NilNode", reflect.TypeOf((*parse.NilNode)(nil)).Elem())
	registerType("text/template/parse", "Node", reflect.TypeOf((*parse.Node)(nil)).Elem())
	registerType("text/template/parse", "NodeType", reflect.TypeOf((*parse.NodeType)(nil)).Elem())
	registerType("text/template/parse", "NumberNode", reflect.TypeOf((*parse.NumberNode)(nil)).Elem())
	registerType("text/template/parse", "PipeNode", reflect.TypeOf((*parse.PipeNode)(nil)).Elem())
	registerType("text/template/parse", "Pos", reflect.TypeOf((*parse.Pos)(nil)).Elem())
	registerType("text/template/parse", "RangeNode", reflect.TypeOf((*parse.RangeNode)(nil)).Elem())
	registerType("text/template/parse", "StringNode", reflect.TypeOf((*parse.StringNode)(nil)).Elem())
	registerType("text/template/parse", "TemplateNode", reflect.TypeOf((*parse.TemplateNode)(nil)).Elem())
	registerType("text/template/parse", "TextNode", reflect.TypeOf((*parse.TextNode)(nil)).Elem())
	registerType("text/template/parse", "Tree", reflect.TypeOf((*parse.Tree)(nil)).Elem())
	registerType("text/template/parse", "VariableNode", reflect.TypeOf((*parse.VariableNode)(nil)).Elem())
	registerType("text/template/parse", "WithNode", reflect.TypeOf((*parse.WithNode)(nil)).Elem())
}

