// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: testing/slogtest

package microlisp

import (
	slogtest "testing/slogtest"
)

func register_testing_slogtest() {
	registerPackage(
		"testing/slogtest",
		map[string]interface{}{
			"TestHandler": slogtest.TestHandler,
		},
	)
}

