// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: os

package microlisp

import (
	os "os"
	"reflect"
)

func register_os() {
	registerPackage(
		"os",
		map[string]interface{}{
			"Chdir": os.Chdir,
			"Chmod": os.Chmod,
			"Chown": os.Chown,
			"Chtimes": os.Chtimes,
			"Clearenv": os.Clearenv,
			"Create": os.Create,
			"CreateTemp": os.CreateTemp,
			"DirFS": os.DirFS,
			"Environ": os.Environ,
			"Executable": os.Executable,
			"Exit": os.Exit,
			"Expand": os.Expand,
			"ExpandEnv": os.ExpandEnv,
			"FindProcess": os.FindProcess,
			"Getegid": os.Getegid,
			"Getenv": os.Getenv,
			"Geteuid": os.Geteuid,
			"Getgid": os.Getgid,
			"Getgroups": os.Getgroups,
			"Getpagesize": os.Getpagesize,
			"Getpid": os.Getpid,
			"Getppid": os.Getppid,
			"Getuid": os.Getuid,
			"Getwd": os.Getwd,
			"Hostname": os.Hostname,
			"IsExist": os.IsExist,
			"IsNotExist": os.IsNotExist,
			"IsPathSeparator": os.IsPathSeparator,
			"IsPermission": os.IsPermission,
			"IsTimeout": os.IsTimeout,
			"Lchown": os.Lchown,
			"Link": os.Link,
			"LookupEnv": os.LookupEnv,
			"Lstat": os.Lstat,
			"Mkdir": os.Mkdir,
			"MkdirAll": os.MkdirAll,
			"MkdirTemp": os.MkdirTemp,
			"NewFile": os.NewFile,
			"NewSyscallError": os.NewSyscallError,
			"Open": os.Open,
			"OpenFile": os.OpenFile,
			"Pipe": os.Pipe,
			"ReadDir": os.ReadDir,
			"ReadFile": os.ReadFile,
			"Readlink": os.Readlink,
			"Remove": os.Remove,
			"RemoveAll": os.RemoveAll,
			"Rename": os.Rename,
			"SameFile": os.SameFile,
			"Setenv": os.Setenv,
			"StartProcess": os.StartProcess,
			"Stat": os.Stat,
			"Symlink": os.Symlink,
			"TempDir": os.TempDir,
			"Truncate": os.Truncate,
			"Unsetenv": os.Unsetenv,
			"UserCacheDir": os.UserCacheDir,
			"UserConfigDir": os.UserConfigDir,
			"UserHomeDir": os.UserHomeDir,
			"WriteFile": os.WriteFile,
			"Args": os.Args,
			"ErrClosed": os.ErrClosed,
			"ErrDeadlineExceeded": os.ErrDeadlineExceeded,
			"ErrExist": os.ErrExist,
			"ErrInvalid": os.ErrInvalid,
			"ErrNoDeadline": os.ErrNoDeadline,
			"ErrNotExist": os.ErrNotExist,
			"ErrPermission": os.ErrPermission,
			"ErrProcessDone": os.ErrProcessDone,
			"Interrupt": os.Interrupt,
			"Kill": os.Kill,
			"Stderr": os.Stderr,
			"Stdin": os.Stdin,
			"Stdout": os.Stdout,
			"DevNull": os.DevNull,
			"ModeAppend": os.ModeAppend,
			"ModeCharDevice": os.ModeCharDevice,
			"ModeDevice": os.ModeDevice,
			"ModeDir": os.ModeDir,
			"ModeExclusive": os.ModeExclusive,
			"ModeIrregular": os.ModeIrregular,
			"ModeNamedPipe": os.ModeNamedPipe,
			"ModePerm": os.ModePerm,
			"ModeSetgid": os.ModeSetgid,
			"ModeSetuid": os.ModeSetuid,
			"ModeSocket": os.ModeSocket,
			"ModeSticky": os.ModeSticky,
			"ModeSymlink": os.ModeSymlink,
			"ModeTemporary": os.ModeTemporary,
			"ModeType": os.ModeType,
			"O_APPEND": os.O_APPEND,
			"O_CREATE": os.O_CREATE,
			"O_EXCL": os.O_EXCL,
			"O_RDONLY": os.O_RDONLY,
			"O_RDWR": os.O_RDWR,
			"O_SYNC": os.O_SYNC,
			"O_TRUNC": os.O_TRUNC,
			"O_WRONLY": os.O_WRONLY,
			"PathListSeparator": os.PathListSeparator,
			"PathSeparator": os.PathSeparator,
			"SEEK_CUR": os.SEEK_CUR,
			"SEEK_END": os.SEEK_END,
			"SEEK_SET": os.SEEK_SET,
		},
	)
	registerType("os", "DirEntry", reflect.TypeOf((*os.DirEntry)(nil)).Elem())
	registerType("os", "File", reflect.TypeOf((*os.File)(nil)).Elem())
	registerType("os", "FileInfo", reflect.TypeOf((*os.FileInfo)(nil)).Elem())
	registerType("os", "FileMode", reflect.TypeOf((*os.FileMode)(nil)).Elem())
	registerType("os", "LinkError", reflect.TypeOf((*os.LinkError)(nil)).Elem())
	registerType("os", "PathError", reflect.TypeOf((*os.PathError)(nil)).Elem())
	registerType("os", "ProcAttr", reflect.TypeOf((*os.ProcAttr)(nil)).Elem())
	registerType("os", "Process", reflect.TypeOf((*os.Process)(nil)).Elem())
	registerType("os", "ProcessState", reflect.TypeOf((*os.ProcessState)(nil)).Elem())
	registerType("os", "Signal", reflect.TypeOf((*os.Signal)(nil)).Elem())
	registerType("os", "SyscallError", reflect.TypeOf((*os.SyscallError)(nil)).Elem())
}

