// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: compress/bzip2

package microlisp

import (
	bzip2 "compress/bzip2"
	"reflect"
)

func register_compress_bzip2() {
	registerPackage(
		"compress/bzip2",
		map[string]interface{}{
			"NewReader": bzip2.NewReader,
		},
	)
	registerType("compress/bzip2", "StructuralError", reflect.TypeOf((*bzip2.StructuralError)(nil)).Elem())
}

