// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: compress/lzw

package microlisp

import (
	lzw "compress/lzw"
	"reflect"
)

func register_compress_lzw() {
	registerPackage(
		"compress/lzw",
		map[string]interface{}{
			"NewReader": lzw.NewReader,
			"NewWriter": lzw.NewWriter,
		},
	)
	registerType("compress/lzw", "Order", reflect.TypeOf((*lzw.Order)(nil)).Elem())
	registerType("compress/lzw", "Reader", reflect.TypeOf((*lzw.Reader)(nil)).Elem())
	registerType("compress/lzw", "Writer", reflect.TypeOf((*lzw.Writer)(nil)).Elem())
}

