// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: debug/macho

package microlisp

import (
	macho "debug/macho"
	"reflect"
)

func register_debug_macho() {
	registerPackage(
		"debug/macho",
		map[string]interface{}{
			"NewFatFile": macho.NewFatFile,
			"NewFile": macho.NewFile,
			"Open": macho.Open,
			"OpenFat": macho.OpenFat,
			"ErrNotFat": macho.ErrNotFat,
			"ARM64_RELOC_ADDEND": macho.ARM64_RELOC_ADDEND,
			"ARM64_RELOC_BRANCH26": macho.ARM64_RELOC_BRANCH26,
			"ARM64_RELOC_GOT_LOAD_PAGE21": macho.ARM64_RELOC_GOT_LOAD_PAGE21,
			"ARM64_RELOC_GOT_LOAD_PAGEOFF12": macho.ARM64_RELOC_GOT_LOAD_PAGEOFF12,
			"ARM64_RELOC_PAGE21": macho.ARM64_RELOC_PAGE21,
			"ARM64_RELOC_PAGEOFF12": macho.ARM64_RELOC_PAGEOFF12,
			"ARM64_RELOC_POINTER_TO_GOT": macho.ARM64_RELOC_POINTER_TO_GOT,
			"ARM64_RELOC_SUBTRACTOR": macho.ARM64_RELOC_SUBTRACTOR,
			"ARM64_RELOC_TLVP_LOAD_PAGE21": macho.ARM64_RELOC_TLVP_LOAD_PAGE21,
			"ARM64_RELOC_TLVP_LOAD_PAGEOFF12": macho.ARM64_RELOC_TLVP_LOAD_PAGEOFF12,
			"ARM64_RELOC_UNSIGNED": macho.ARM64_RELOC_UNSIGNED,
			"ARM_RELOC_BR24": macho.ARM_RELOC_BR24,
			"ARM_RELOC_HALF": macho.ARM_RELOC_HALF,
			"ARM_RELOC_HALF_SECTDIFF": macho.ARM_RELOC_HALF_SECTDIFF,
			"ARM_RELOC_LOCAL_SECTDIFF": macho.ARM_RELOC_LOCAL_SECTDIFF,
			"ARM_RELOC_PAIR": macho.ARM_RELOC_PAIR,
			"ARM_RELOC_PB_LA_PTR": macho.ARM_RELOC_PB_LA_PTR,
			"ARM_RELOC_SECTDIFF": macho.ARM_RELOC_SECTDIFF,
			"ARM_RELOC_VANILLA": macho.ARM_RELOC_VANILLA,
			"ARM_THUMB_32BIT_BRANCH": macho.ARM_THUMB_32BIT_BRANCH,
			"ARM_THUMB_RELOC_BR22": macho.ARM_THUMB_RELOC_BR22,
			"Cpu386": macho.Cpu386,
			"CpuAmd64": macho.CpuAmd64,
			"CpuArm": macho.CpuArm,
			"CpuArm64": macho.CpuArm64,
			"CpuPpc": macho.CpuPpc,
			"CpuPpc64": macho.CpuPpc64,
			"FlagAllModsBound": macho.FlagAllModsBound,
			"FlagAllowStackExecution": macho.FlagAllowStackExecution,
			"FlagAppExtensionSafe": macho.FlagAppExtensionSafe,
			"FlagBindAtLoad": macho.FlagBindAtLoad,
			"FlagBindsToWeak": macho.FlagBindsToWeak,
			"FlagCanonical": macho.FlagCanonical,
			"FlagDeadStrippableDylib": macho.FlagDeadStrippableDylib,
			"FlagDyldLink": macho.FlagDyldLink,
			"FlagForceFlat": macho.FlagForceFlat,
			"FlagHasTLVDescriptors": macho.FlagHasTLVDescriptors,
			"FlagIncrLink": macho.FlagIncrLink,
			"FlagLazyInit": macho.FlagLazyInit,
			"FlagNoFixPrebinding": macho.FlagNoFixPrebinding,
			"FlagNoHeapExecution": macho.FlagNoHeapExecution,
			"FlagNoMultiDefs": macho.FlagNoMultiDefs,
			"FlagNoReexportedDylibs": macho.FlagNoReexportedDylibs,
			"FlagNoUndefs": macho.FlagNoUndefs,
			"FlagPIE": macho.FlagPIE,
			"FlagPrebindable": macho.FlagPrebindable,
			"FlagPrebound": macho.FlagPrebound,
			"FlagRootSafe": macho.FlagRootSafe,
			"FlagSetuidSafe": macho.FlagSetuidSafe,
			"FlagSplitSegs": macho.FlagSplitSegs,
			"FlagSubsectionsViaSymbols": macho.FlagSubsectionsViaSymbols,
			"FlagTwoLevel": macho.FlagTwoLevel,
			"FlagWeakDefines": macho.FlagWeakDefines,
			"GENERIC_RELOC_LOCAL_SECTDIFF": macho.GENERIC_RELOC_LOCAL_SECTDIFF,
			"GENERIC_RELOC_PAIR": macho.GENERIC_RELOC_PAIR,
			"GENERIC_RELOC_PB_LA_PTR": macho.GENERIC_RELOC_PB_LA_PTR,
			"GENERIC_RELOC_SECTDIFF": macho.GENERIC_RELOC_SECTDIFF,
			"GENERIC_RELOC_TLV": macho.GENERIC_RELOC_TLV,
			"GENERIC_RELOC_VANILLA": macho.GENERIC_RELOC_VANILLA,
			"LoadCmdDylib": macho.LoadCmdDylib,
			"LoadCmdDylinker": macho.LoadCmdDylinker,
			"LoadCmdDysymtab": macho.LoadCmdDysymtab,
			"LoadCmdRpath": macho.LoadCmdRpath,
			"LoadCmdSegment": macho.LoadCmdSegment,
			"LoadCmdSegment64": macho.LoadCmdSegment64,
			"LoadCmdSymtab": macho.LoadCmdSymtab,
			"LoadCmdThread": macho.LoadCmdThread,
			"LoadCmdUnixThread": macho.LoadCmdUnixThread,
			"Magic32": macho.Magic32,
			"Magic64": macho.Magic64,
			"MagicFat": macho.MagicFat,
			"TypeBundle": macho.TypeBundle,
			"TypeDylib": macho.TypeDylib,
			"TypeExec": macho.TypeExec,
			"TypeObj": macho.TypeObj,
			"X86_64_RELOC_BRANCH": macho.X86_64_RELOC_BRANCH,
			"X86_64_RELOC_GOT": macho.X86_64_RELOC_GOT,
			"X86_64_RELOC_GOT_LOAD": macho.X86_64_RELOC_GOT_LOAD,
			"X86_64_RELOC_SIGNED": macho.X86_64_RELOC_SIGNED,
			"X86_64_RELOC_SIGNED_1": macho.X86_64_RELOC_SIGNED_1,
			"X86_64_RELOC_SIGNED_2": macho.X86_64_RELOC_SIGNED_2,
			"X86_64_RELOC_SIGNED_4": macho.X86_64_RELOC_SIGNED_4,
			"X86_64_RELOC_SUBTRACTOR": macho.X86_64_RELOC_SUBTRACTOR,
			"X86_64_RELOC_TLV": macho.X86_64_RELOC_TLV,
			"X86_64_RELOC_UNSIGNED": macho.X86_64_RELOC_UNSIGNED,
		},
	)
	registerType("debug/macho", "Cpu", reflect.TypeOf((*macho.Cpu)(nil)).Elem())
	registerType("debug/macho", "Dylib", reflect.TypeOf((*macho.Dylib)(nil)).Elem())
	registerType("debug/macho", "DylibCmd", reflect.TypeOf((*macho.DylibCmd)(nil)).Elem())
	registerType("debug/macho", "Dysymtab", reflect.TypeOf((*macho.Dysymtab)(nil)).Elem())
	registerType("debug/macho", "DysymtabCmd", reflect.TypeOf((*macho.DysymtabCmd)(nil)).Elem())
	registerType("debug/macho", "FatArch", reflect.TypeOf((*macho.FatArch)(nil)).Elem())
	registerType("debug/macho", "FatArchHeader", reflect.TypeOf((*macho.FatArchHeader)(nil)).Elem())
	registerType("debug/macho", "FatFile", reflect.TypeOf((*macho.FatFile)(nil)).Elem())
	registerType("debug/macho", "File", reflect.TypeOf((*macho.File)(nil)).Elem())
	registerType("debug/macho", "FileHeader", reflect.TypeOf((*macho.FileHeader)(nil)).Elem())
	registerType("debug/macho", "FormatError", reflect.TypeOf((*macho.FormatError)(nil)).Elem())
	registerType("debug/macho", "Load", reflect.TypeOf((*macho.Load)(nil)).Elem())
	registerType("debug/macho", "LoadBytes", reflect.TypeOf((*macho.LoadBytes)(nil)).Elem())
	registerType("debug/macho", "LoadCmd", reflect.TypeOf((*macho.LoadCmd)(nil)).Elem())
	registerType("debug/macho", "Nlist32", reflect.TypeOf((*macho.Nlist32)(nil)).Elem())
	registerType("debug/macho", "Nlist64", reflect.TypeOf((*macho.Nlist64)(nil)).Elem())
	registerType("debug/macho", "Regs386", reflect.TypeOf((*macho.Regs386)(nil)).Elem())
	registerType("debug/macho", "RegsAMD64", reflect.TypeOf((*macho.RegsAMD64)(nil)).Elem())
	registerType("debug/macho", "Reloc", reflect.TypeOf((*macho.Reloc)(nil)).Elem())
	registerType("debug/macho", "RelocTypeARM", reflect.TypeOf((*macho.RelocTypeARM)(nil)).Elem())
	registerType("debug/macho", "RelocTypeARM64", reflect.TypeOf((*macho.RelocTypeARM64)(nil)).Elem())
	registerType("debug/macho", "RelocTypeGeneric", reflect.TypeOf((*macho.RelocTypeGeneric)(nil)).Elem())
	registerType("debug/macho", "RelocTypeX86_64", reflect.TypeOf((*macho.RelocTypeX86_64)(nil)).Elem())
	registerType("debug/macho", "Rpath", reflect.TypeOf((*macho.Rpath)(nil)).Elem())
	registerType("debug/macho", "RpathCmd", reflect.TypeOf((*macho.RpathCmd)(nil)).Elem())
	registerType("debug/macho", "Section", reflect.TypeOf((*macho.Section)(nil)).Elem())
	registerType("debug/macho", "Section32", reflect.TypeOf((*macho.Section32)(nil)).Elem())
	registerType("debug/macho", "Section64", reflect.TypeOf((*macho.Section64)(nil)).Elem())
	registerType("debug/macho", "SectionHeader", reflect.TypeOf((*macho.SectionHeader)(nil)).Elem())
	registerType("debug/macho", "Segment", reflect.TypeOf((*macho.Segment)(nil)).Elem())
	registerType("debug/macho", "Segment32", reflect.TypeOf((*macho.Segment32)(nil)).Elem())
	registerType("debug/macho", "Segment64", reflect.TypeOf((*macho.Segment64)(nil)).Elem())
	registerType("debug/macho", "SegmentHeader", reflect.TypeOf((*macho.SegmentHeader)(nil)).Elem())
	registerType("debug/macho", "Symbol", reflect.TypeOf((*macho.Symbol)(nil)).Elem())
	registerType("debug/macho", "Symtab", reflect.TypeOf((*macho.Symtab)(nil)).Elem())
	registerType("debug/macho", "SymtabCmd", reflect.TypeOf((*macho.SymtabCmd)(nil)).Elem())
	registerType("debug/macho", "Thread", reflect.TypeOf((*macho.Thread)(nil)).Elem())
	registerType("debug/macho", "Type", reflect.TypeOf((*macho.Type)(nil)).Elem())
}

