// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: os/user

package microlisp

import (
	user "os/user"
	"reflect"
)

func register_os_user() {
	registerPackage(
		"os/user",
		map[string]interface{}{
			"Current": user.Current,
			"Lookup": user.Lookup,
			"LookupGroup": user.LookupGroup,
			"LookupGroupId": user.LookupGroupId,
			"LookupId": user.LookupId,
		},
	)
	registerType("os/user", "Group", reflect.TypeOf((*user.Group)(nil)).Elem())
	registerType("os/user", "UnknownGroupError", reflect.TypeOf((*user.UnknownGroupError)(nil)).Elem())
	registerType("os/user", "UnknownGroupIdError", reflect.TypeOf((*user.UnknownGroupIdError)(nil)).Elem())
	registerType("os/user", "UnknownUserError", reflect.TypeOf((*user.UnknownUserError)(nil)).Elem())
	registerType("os/user", "UnknownUserIdError", reflect.TypeOf((*user.UnknownUserIdError)(nil)).Elem())
	registerType("os/user", "User", reflect.TypeOf((*user.User)(nil)).Elem())
}

