// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: compress/flate

package microlisp

import (
	flate "compress/flate"
	"reflect"
)

func register_compress_flate() {
	registerPackage(
		"compress/flate",
		map[string]interface{}{
			"NewReader": flate.NewReader,
			"NewReaderDict": flate.NewReaderDict,
			"NewWriter": flate.NewWriter,
			"NewWriterDict": flate.NewWriterDict,
			"BestCompression": flate.BestCompression,
			"BestSpeed": flate.BestSpeed,
			"DefaultCompression": flate.DefaultCompression,
			"HuffmanOnly": flate.HuffmanOnly,
			"NoCompression": flate.NoCompression,
		},
	)
	registerType("compress/flate", "CorruptInputError", reflect.TypeOf((*flate.CorruptInputError)(nil)).Elem())
	registerType("compress/flate", "InternalError", reflect.TypeOf((*flate.InternalError)(nil)).Elem())
	registerType("compress/flate", "ReadError", reflect.TypeOf((*flate.ReadError)(nil)).Elem())
	registerType("compress/flate", "Reader", reflect.TypeOf((*flate.Reader)(nil)).Elem())
	registerType("compress/flate", "Resetter", reflect.TypeOf((*flate.Resetter)(nil)).Elem())
	registerType("compress/flate", "WriteError", reflect.TypeOf((*flate.WriteError)(nil)).Elem())
	registerType("compress/flate", "Writer", reflect.TypeOf((*flate.Writer)(nil)).Elem())
}

