// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/sha512

package microlisp

import (
	sha512 "crypto/sha512"
)

func register_crypto_sha512() {
	registerPackage(
		"crypto/sha512",
		map[string]interface{}{
			"New": sha512.New,
			"New384": sha512.New384,
			"New512_224": sha512.New512_224,
			"New512_256": sha512.New512_256,
			"Sum384": sha512.Sum384,
			"Sum512": sha512.Sum512,
			"Sum512_224": sha512.Sum512_224,
			"Sum512_256": sha512.Sum512_256,
			"BlockSize": sha512.BlockSize,
			"Size": sha512.Size,
			"Size224": sha512.Size224,
			"Size256": sha512.Size256,
			"Size384": sha512.Size384,
		},
	)
}

