// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/rc4

package microlisp

import (
	rc4 "crypto/rc4"
	"reflect"
)

func register_crypto_rc4() {
	registerPackage(
		"crypto/rc4",
		map[string]interface{}{
			"NewCipher": rc4.NewCipher,
		},
	)
	registerType("crypto/rc4", "Cipher", reflect.TypeOf((*rc4.Cipher)(nil)).Elem())
	registerType("crypto/rc4", "KeySizeError", reflect.TypeOf((*rc4.KeySizeError)(nil)).Elem())
}

