// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: strconv

package microlisp

import (
	strconv "strconv"
	"reflect"
)

func register_strconv() {
	registerPackage(
		"strconv",
		map[string]interface{}{
			"AppendBool": strconv.AppendBool,
			"AppendFloat": strconv.AppendFloat,
			"AppendInt": strconv.AppendInt,
			"AppendQuote": strconv.AppendQuote,
			"AppendQuoteRune": strconv.AppendQuoteRune,
			"AppendQuoteRuneToASCII": strconv.AppendQuoteRuneToASCII,
			"AppendQuoteRuneToGraphic": strconv.AppendQuoteRuneToGraphic,
			"AppendQuoteToASCII": strconv.AppendQuoteToASCII,
			"AppendQuoteToGraphic": strconv.AppendQuoteToGraphic,
			"AppendUint": strconv.AppendUint,
			"Atoi": strconv.Atoi,
			"CanBackquote": strconv.CanBackquote,
			"FormatBool": strconv.FormatBool,
			"FormatComplex": strconv.FormatComplex,
			"FormatFloat": strconv.FormatFloat,
			"FormatInt": strconv.FormatInt,
			"FormatUint": strconv.FormatUint,
			"IsGraphic": strconv.IsGraphic,
			"IsPrint": strconv.IsPrint,
			"Itoa": strconv.Itoa,
			"ParseBool": strconv.ParseBool,
			"ParseComplex": strconv.ParseComplex,
			"ParseFloat": strconv.ParseFloat,
			"ParseInt": strconv.ParseInt,
			"ParseUint": strconv.ParseUint,
			"Quote": strconv.Quote,
			"QuoteRune": strconv.QuoteRune,
			"QuoteRuneToASCII": strconv.QuoteRuneToASCII,
			"QuoteRuneToGraphic": strconv.QuoteRuneToGraphic,
			"QuoteToASCII": strconv.QuoteToASCII,
			"QuoteToGraphic": strconv.QuoteToGraphic,
			"QuotedPrefix": strconv.QuotedPrefix,
			"Unquote": strconv.Unquote,
			"UnquoteChar": strconv.UnquoteChar,
			"ErrRange": strconv.ErrRange,
			"ErrSyntax": strconv.ErrSyntax,
			"IntSize": strconv.IntSize,
		},
	)
	registerType("strconv", "NumError", reflect.TypeOf((*strconv.NumError)(nil)).Elem())
}

