// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/http/httptest

package microlisp

import (
	httptest "net/http/httptest"
	"reflect"
)

func register_net_http_httptest() {
	registerPackage(
		"net/http/httptest",
		map[string]interface{}{
			"NewRecorder": httptest.NewRecorder,
			"NewRequest": httptest.NewRequest,
			"NewServer": httptest.NewServer,
			"NewTLSServer": httptest.NewTLSServer,
			"NewUnstartedServer": httptest.NewUnstartedServer,
			"DefaultRemoteAddr": httptest.DefaultRemoteAddr,
		},
	)
	registerType("net/http/httptest", "ResponseRecorder", reflect.TypeOf((*httptest.ResponseRecorder)(nil)).Elem())
	registerType("net/http/httptest", "Server", reflect.TypeOf((*httptest.Server)(nil)).Elem())
}

