// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: mime/multipart

package microlisp

import (
	multipart "mime/multipart"
	"reflect"
)

func register_mime_multipart() {
	registerPackage(
		"mime/multipart",
		map[string]interface{}{
			"NewReader": multipart.NewReader,
			"NewWriter": multipart.NewWriter,
			"ErrMessageTooLarge": multipart.ErrMessageTooLarge,
		},
	)
	registerType("mime/multipart", "File", reflect.TypeOf((*multipart.File)(nil)).Elem())
	registerType("mime/multipart", "FileHeader", reflect.TypeOf((*multipart.FileHeader)(nil)).Elem())
	registerType("mime/multipart", "Form", reflect.TypeOf((*multipart.Form)(nil)).Elem())
	registerType("mime/multipart", "Part", reflect.TypeOf((*multipart.Part)(nil)).Elem())
	registerType("mime/multipart", "Reader", reflect.TypeOf((*multipart.Reader)(nil)).Elem())
	registerType("mime/multipart", "Writer", reflect.TypeOf((*multipart.Writer)(nil)).Elem())
}

