// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/hex

package microlisp

import (
	hex "encoding/hex"
	"reflect"
)

func register_encoding_hex() {
	registerPackage(
		"encoding/hex",
		map[string]interface{}{
			"Decode": hex.Decode,
			"DecodeString": hex.DecodeString,
			"DecodedLen": hex.DecodedLen,
			"Dump": hex.Dump,
			"Dumper": hex.Dumper,
			"Encode": hex.Encode,
			"EncodeToString": hex.EncodeToString,
			"EncodedLen": hex.EncodedLen,
			"NewDecoder": hex.NewDecoder,
			"NewEncoder": hex.NewEncoder,
			"ErrLength": hex.ErrLength,
		},
	)
	registerType("encoding/hex", "InvalidByteError", reflect.TypeOf((*hex.InvalidByteError)(nil)).Elem())
}

