// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/md5

package microlisp

import (
	md5 "crypto/md5"
)

func register_crypto_md5() {
	registerPackage(
		"crypto/md5",
		map[string]interface{}{
			"New": md5.New,
			"Sum": md5.Sum,
			"BlockSize": md5.BlockSize,
			"Size": md5.Size,
		},
	)
}

