// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: bytes

package microlisp

import (
	bytes "bytes"
	"reflect"
)

func register_bytes() {
	registerPackage(
		"bytes",
		map[string]interface{}{
			"Clone": bytes.Clone,
			"Compare": bytes.Compare,
			"Contains": bytes.Contains,
			"ContainsAny": bytes.ContainsAny,
			"ContainsFunc": bytes.ContainsFunc,
			"ContainsRune": bytes.ContainsRune,
			"Count": bytes.Count,
			"Cut": bytes.Cut,
			"CutPrefix": bytes.CutPrefix,
			"CutSuffix": bytes.CutSuffix,
			"Equal": bytes.Equal,
			"EqualFold": bytes.EqualFold,
			"Fields": bytes.Fields,
			"FieldsFunc": bytes.FieldsFunc,
			"HasPrefix": bytes.HasPrefix,
			"HasSuffix": bytes.HasSuffix,
			"Index": bytes.Index,
			"IndexAny": bytes.IndexAny,
			"IndexByte": bytes.IndexByte,
			"IndexFunc": bytes.IndexFunc,
			"IndexRune": bytes.IndexRune,
			"Join": bytes.Join,
			"LastIndex": bytes.LastIndex,
			"LastIndexAny": bytes.LastIndexAny,
			"LastIndexByte": bytes.LastIndexByte,
			"LastIndexFunc": bytes.LastIndexFunc,
			"Map": bytes.Map,
			"NewBuffer": bytes.NewBuffer,
			"NewBufferString": bytes.NewBufferString,
			"NewReader": bytes.NewReader,
			"Repeat": bytes.Repeat,
			"Replace": bytes.Replace,
			"ReplaceAll": bytes.ReplaceAll,
			"Runes": bytes.Runes,
			"Split": bytes.Split,
			"SplitAfter": bytes.SplitAfter,
			"SplitAfterN": bytes.SplitAfterN,
			"SplitN": bytes.SplitN,
			"Title": bytes.Title,
			"ToLower": bytes.ToLower,
			"ToLowerSpecial": bytes.ToLowerSpecial,
			"ToTitle": bytes.ToTitle,
			"ToTitleSpecial": bytes.ToTitleSpecial,
			"ToUpper": bytes.ToUpper,
			"ToUpperSpecial": bytes.ToUpperSpecial,
			"ToValidUTF8": bytes.ToValidUTF8,
			"Trim": bytes.Trim,
			"TrimFunc": bytes.TrimFunc,
			"TrimLeft": bytes.TrimLeft,
			"TrimLeftFunc": bytes.TrimLeftFunc,
			"TrimPrefix": bytes.TrimPrefix,
			"TrimRight": bytes.TrimRight,
			"TrimRightFunc": bytes.TrimRightFunc,
			"TrimSpace": bytes.TrimSpace,
			"TrimSuffix": bytes.TrimSuffix,
			"ErrTooLarge": bytes.ErrTooLarge,
			"MinRead": bytes.MinRead,
		},
	)
	registerType("bytes", "Buffer", reflect.TypeOf((*bytes.Buffer)(nil)).Elem())
	registerType("bytes", "Reader", reflect.TypeOf((*bytes.Reader)(nil)).Elem())
}

