// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: sync/atomic

package microlisp

import (
	atomicPkg "sync/atomic"
)

func register_sync_atomic() {
	registerPackage(
		"sync/atomic",
		map[string]interface{}{
			"AddInt32": atomicPkg.AddInt32,
			"AddInt64": atomicPkg.AddInt64,
			"AddUint32": atomicPkg.AddUint32,
			"AddUint64": atomicPkg.AddUint64,
			"AddUintptr": atomicPkg.AddUintptr,
			"CompareAndSwapInt32": atomicPkg.CompareAndSwapInt32,
			"CompareAndSwapInt64": atomicPkg.CompareAndSwapInt64,
			"CompareAndSwapPointer": atomicPkg.CompareAndSwapPointer,
			"CompareAndSwapUint32": atomicPkg.CompareAndSwapUint32,
			"CompareAndSwapUint64": atomicPkg.CompareAndSwapUint64,
			"CompareAndSwapUintptr": atomicPkg.CompareAndSwapUintptr,
			"LoadInt32": atomicPkg.LoadInt32,
			"LoadInt64": atomicPkg.LoadInt64,
			"LoadPointer": atomicPkg.LoadPointer,
			"LoadUint32": atomicPkg.LoadUint32,
			"LoadUint64": atomicPkg.LoadUint64,
			"LoadUintptr": atomicPkg.LoadUintptr,
			"StoreInt32": atomicPkg.StoreInt32,
			"StoreInt64": atomicPkg.StoreInt64,
			"StorePointer": atomicPkg.StorePointer,
			"StoreUint32": atomicPkg.StoreUint32,
			"StoreUint64": atomicPkg.StoreUint64,
			"StoreUintptr": atomicPkg.StoreUintptr,
			"SwapInt32": atomicPkg.SwapInt32,
			"SwapInt64": atomicPkg.SwapInt64,
			"SwapPointer": atomicPkg.SwapPointer,
			"SwapUint32": atomicPkg.SwapUint32,
			"SwapUint64": atomicPkg.SwapUint64,
			"SwapUintptr": atomicPkg.SwapUintptr,
		},
	)
}

