// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: debug/elf

package microlisp

import (
	elf "debug/elf"
	"reflect"
)

func register_debug_elf() {
	registerPackage(
		"debug/elf",
		map[string]interface{}{
			"NewFile": elf.NewFile,
			"Open": elf.Open,
			"R_INFO": elf.R_INFO,
			"R_INFO32": elf.R_INFO32,
			"R_SYM32": elf.R_SYM32,
			"R_SYM64": elf.R_SYM64,
			"R_TYPE32": elf.R_TYPE32,
			"R_TYPE64": elf.R_TYPE64,
			"ST_BIND": elf.ST_BIND,
			"ST_INFO": elf.ST_INFO,
			"ST_TYPE": elf.ST_TYPE,
			"ST_VISIBILITY": elf.ST_VISIBILITY,
			"ErrNoSymbols": elf.ErrNoSymbols,
			"ARM_MAGIC_TRAMP_NUMBER": elf.ARM_MAGIC_TRAMP_NUMBER,
			"EI_ABIVERSION": elf.EI_ABIVERSION,
			"EI_CLASS": elf.EI_CLASS,
			"EI_DATA": elf.EI_DATA,
			"EI_NIDENT": elf.EI_NIDENT,
			"EI_OSABI": elf.EI_OSABI,
			"EI_PAD": elf.EI_PAD,
			"EI_VERSION": elf.EI_VERSION,
			"ELFMAG": elf.ELFMAG,
			"Sym32Size": elf.Sym32Size,
			"Sym64Size": elf.Sym64Size,
		},
	)
	registerType("debug/elf", "Chdr32", reflect.TypeOf((*elf.Chdr32)(nil)).Elem())
	registerType("debug/elf", "Chdr64", reflect.TypeOf((*elf.Chdr64)(nil)).Elem())
	registerType("debug/elf", "Class", reflect.TypeOf((*elf.Class)(nil)).Elem())
	registerType("debug/elf", "CompressionType", reflect.TypeOf((*elf.CompressionType)(nil)).Elem())
	registerType("debug/elf", "Data", reflect.TypeOf((*elf.Data)(nil)).Elem())
	registerType("debug/elf", "Dyn32", reflect.TypeOf((*elf.Dyn32)(nil)).Elem())
	registerType("debug/elf", "Dyn64", reflect.TypeOf((*elf.Dyn64)(nil)).Elem())
	registerType("debug/elf", "DynFlag", reflect.TypeOf((*elf.DynFlag)(nil)).Elem())
	registerType("debug/elf", "DynFlag1", reflect.TypeOf((*elf.DynFlag1)(nil)).Elem())
	registerType("debug/elf", "DynTag", reflect.TypeOf((*elf.DynTag)(nil)).Elem())
	registerType("debug/elf", "File", reflect.TypeOf((*elf.File)(nil)).Elem())
	registerType("debug/elf", "FileHeader", reflect.TypeOf((*elf.FileHeader)(nil)).Elem())
	registerType("debug/elf", "FormatError", reflect.TypeOf((*elf.FormatError)(nil)).Elem())
	registerType("debug/elf", "Header32", reflect.TypeOf((*elf.Header32)(nil)).Elem())
	registerType("debug/elf", "Header64", reflect.TypeOf((*elf.Header64)(nil)).Elem())
	registerType("debug/elf", "ImportedSymbol", reflect.TypeOf((*elf.ImportedSymbol)(nil)).Elem())
	registerType("debug/elf", "Machine", reflect.TypeOf((*elf.Machine)(nil)).Elem())
	registerType("debug/elf", "NType", reflect.TypeOf((*elf.NType)(nil)).Elem())
	registerType("debug/elf", "OSABI", reflect.TypeOf((*elf.OSABI)(nil)).Elem())
	registerType("debug/elf", "Prog", reflect.TypeOf((*elf.Prog)(nil)).Elem())
	registerType("debug/elf", "Prog32", reflect.TypeOf((*elf.Prog32)(nil)).Elem())
	registerType("debug/elf", "Prog64", reflect.TypeOf((*elf.Prog64)(nil)).Elem())
	registerType("debug/elf", "ProgFlag", reflect.TypeOf((*elf.ProgFlag)(nil)).Elem())
	registerType("debug/elf", "ProgHeader", reflect.TypeOf((*elf.ProgHeader)(nil)).Elem())
	registerType("debug/elf", "ProgType", reflect.TypeOf((*elf.ProgType)(nil)).Elem())
	registerType("debug/elf", "R_386", reflect.TypeOf((*elf.R_386)(nil)).Elem())
	registerType("debug/elf", "R_390", reflect.TypeOf((*elf.R_390)(nil)).Elem())
	registerType("debug/elf", "R_AARCH64", reflect.TypeOf((*elf.R_AARCH64)(nil)).Elem())
	registerType("debug/elf", "R_ALPHA", reflect.TypeOf((*elf.R_ALPHA)(nil)).Elem())
	registerType("debug/elf", "R_ARM", reflect.TypeOf((*elf.R_ARM)(nil)).Elem())
	registerType("debug/elf", "R_LARCH", reflect.TypeOf((*elf.R_LARCH)(nil)).Elem())
	registerType("debug/elf", "R_MIPS", reflect.TypeOf((*elf.R_MIPS)(nil)).Elem())
	registerType("debug/elf", "R_PPC", reflect.TypeOf((*elf.R_PPC)(nil)).Elem())
	registerType("debug/elf", "R_PPC64", reflect.TypeOf((*elf.R_PPC64)(nil)).Elem())
	registerType("debug/elf", "R_RISCV", reflect.TypeOf((*elf.R_RISCV)(nil)).Elem())
	registerType("debug/elf", "R_SPARC", reflect.TypeOf((*elf.R_SPARC)(nil)).Elem())
	registerType("debug/elf", "R_X86_64", reflect.TypeOf((*elf.R_X86_64)(nil)).Elem())
	registerType("debug/elf", "Rel32", reflect.TypeOf((*elf.Rel32)(nil)).Elem())
	registerType("debug/elf", "Rel64", reflect.TypeOf((*elf.Rel64)(nil)).Elem())
	registerType("debug/elf", "Rela32", reflect.TypeOf((*elf.Rela32)(nil)).Elem())
	registerType("debug/elf", "Rela64", reflect.TypeOf((*elf.Rela64)(nil)).Elem())
	registerType("debug/elf", "Section", reflect.TypeOf((*elf.Section)(nil)).Elem())
	registerType("debug/elf", "Section32", reflect.TypeOf((*elf.Section32)(nil)).Elem())
	registerType("debug/elf", "Section64", reflect.TypeOf((*elf.Section64)(nil)).Elem())
	registerType("debug/elf", "SectionFlag", reflect.TypeOf((*elf.SectionFlag)(nil)).Elem())
	registerType("debug/elf", "SectionHeader", reflect.TypeOf((*elf.SectionHeader)(nil)).Elem())
	registerType("debug/elf", "SectionIndex", reflect.TypeOf((*elf.SectionIndex)(nil)).Elem())
	registerType("debug/elf", "SectionType", reflect.TypeOf((*elf.SectionType)(nil)).Elem())
	registerType("debug/elf", "Sym32", reflect.TypeOf((*elf.Sym32)(nil)).Elem())
	registerType("debug/elf", "Sym64", reflect.TypeOf((*elf.Sym64)(nil)).Elem())
	registerType("debug/elf", "SymBind", reflect.TypeOf((*elf.SymBind)(nil)).Elem())
	registerType("debug/elf", "SymType", reflect.TypeOf((*elf.SymType)(nil)).Elem())
	registerType("debug/elf", "SymVis", reflect.TypeOf((*elf.SymVis)(nil)).Elem())
	registerType("debug/elf", "Symbol", reflect.TypeOf((*elf.Symbol)(nil)).Elem())
	registerType("debug/elf", "Type", reflect.TypeOf((*elf.Type)(nil)).Elem())
	registerType("debug/elf", "Version", reflect.TypeOf((*elf.Version)(nil)).Elem())
}

