// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/x509/pkix

package microlisp

import (
	pkix "crypto/x509/pkix"
	"reflect"
)

func register_crypto_x509_pkix() {
	registerType("crypto/x509/pkix", "AlgorithmIdentifier", reflect.TypeOf((*pkix.AlgorithmIdentifier)(nil)).Elem())
	registerType("crypto/x509/pkix", "AttributeTypeAndValue", reflect.TypeOf((*pkix.AttributeTypeAndValue)(nil)).Elem())
	registerType("crypto/x509/pkix", "AttributeTypeAndValueSET", reflect.TypeOf((*pkix.AttributeTypeAndValueSET)(nil)).Elem())
	registerType("crypto/x509/pkix", "CertificateList", reflect.TypeOf((*pkix.CertificateList)(nil)).Elem())
	registerType("crypto/x509/pkix", "Extension", reflect.TypeOf((*pkix.Extension)(nil)).Elem())
	registerType("crypto/x509/pkix", "Name", reflect.TypeOf((*pkix.Name)(nil)).Elem())
	registerType("crypto/x509/pkix", "RDNSequence", reflect.TypeOf((*pkix.RDNSequence)(nil)).Elem())
	registerType("crypto/x509/pkix", "RelativeDistinguishedNameSET", reflect.TypeOf((*pkix.RelativeDistinguishedNameSET)(nil)).Elem())
	registerType("crypto/x509/pkix", "RevokedCertificate", reflect.TypeOf((*pkix.RevokedCertificate)(nil)).Elem())
	registerType("crypto/x509/pkix", "TBSCertificateList", reflect.TypeOf((*pkix.TBSCertificateList)(nil)).Elem())
}

