// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/des

package microlisp

import (
	des "crypto/des"
	"reflect"
)

func register_crypto_des() {
	registerPackage(
		"crypto/des",
		map[string]interface{}{
			"NewCipher": des.NewCipher,
			"NewTripleDESCipher": des.NewTripleDESCipher,
			"BlockSize": des.BlockSize,
		},
	)
	registerType("crypto/des", "KeySizeError", reflect.TypeOf((*des.KeySizeError)(nil)).Elem())
}

