// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: math/rand

package microlisp

import (
	rand "math/rand"
	"reflect"
)

func register_math_rand() {
	registerPackage(
		"math/rand",
		map[string]interface{}{
			"ExpFloat64": rand.ExpFloat64,
			"Float32": rand.Float32,
			"Float64": rand.Float64,
			"Int": rand.Int,
			"Int31": rand.Int31,
			"Int31n": rand.Int31n,
			"Int63": rand.Int63,
			"Int63n": rand.Int63n,
			"Intn": rand.Intn,
			"New": rand.New,
			"NewSource": rand.NewSource,
			"NewZipf": rand.NewZipf,
			"NormFloat64": rand.NormFloat64,
			"Perm": rand.Perm,
			"Read": rand.Read,
			"Seed": rand.Seed,
			"Shuffle": rand.Shuffle,
			"Uint32": rand.Uint32,
			"Uint64": rand.Uint64,
		},
	)
	registerType("math/rand", "Rand", reflect.TypeOf((*rand.Rand)(nil)).Elem())
	registerType("math/rand", "Source", reflect.TypeOf((*rand.Source)(nil)).Elem())
	registerType("math/rand", "Source64", reflect.TypeOf((*rand.Source64)(nil)).Elem())
	registerType("math/rand", "Zipf", reflect.TypeOf((*rand.Zipf)(nil)).Elem())
}

