// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: io/ioutil

package microlisp

import (
	ioutil "io/ioutil"
)

func register_io_ioutil() {
	registerPackage(
		"io/ioutil",
		map[string]interface{}{
			"NopCloser": ioutil.NopCloser,
			"ReadAll": ioutil.ReadAll,
			"ReadDir": ioutil.ReadDir,
			"ReadFile": ioutil.ReadFile,
			"TempDir": ioutil.TempDir,
			"TempFile": ioutil.TempFile,
			"WriteFile": ioutil.WriteFile,
			"Discard": ioutil.Discard,
		},
	)
}

