// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: errors

package microlisp

import (
	errors "errors"
)

func register_errors() {
	registerPackage(
		"errors",
		map[string]interface{}{
			"As": errors.As,
			"Is": errors.Is,
			"Join": errors.Join,
			"New": errors.New,
			"Unwrap": errors.Unwrap,
			"ErrUnsupported": errors.ErrUnsupported,
		},
	)
}

