// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: expvar

package microlisp

import (
	expvar "expvar"
	"reflect"
)

func register_expvar() {
	registerPackage(
		"expvar",
		map[string]interface{}{
			"Do": expvar.Do,
			"Get": expvar.Get,
			"Handler": expvar.Handler,
			"NewFloat": expvar.NewFloat,
			"NewInt": expvar.NewInt,
			"NewMap": expvar.NewMap,
			"NewString": expvar.NewString,
			"Publish": expvar.Publish,
		},
	)
	registerType("expvar", "Float", reflect.TypeOf((*expvar.Float)(nil)).Elem())
	registerType("expvar", "Func", reflect.TypeOf((*expvar.Func)(nil)).Elem())
	registerType("expvar", "Int", reflect.TypeOf((*expvar.Int)(nil)).Elem())
	registerType("expvar", "KeyValue", reflect.TypeOf((*expvar.KeyValue)(nil)).Elem())
	registerType("expvar", "Map", reflect.TypeOf((*expvar.Map)(nil)).Elem())
	registerType("expvar", "String", reflect.TypeOf((*expvar.String)(nil)).Elem())
	registerType("expvar", "Var", reflect.TypeOf((*expvar.Var)(nil)).Elem())
}

