// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/rsa

package microlisp

import (
	rsa "crypto/rsa"
	"reflect"
)

func register_crypto_rsa() {
	registerPackage(
		"crypto/rsa",
		map[string]interface{}{
			"DecryptOAEP": rsa.DecryptOAEP,
			"DecryptPKCS1v15": rsa.DecryptPKCS1v15,
			"DecryptPKCS1v15SessionKey": rsa.DecryptPKCS1v15SessionKey,
			"EncryptOAEP": rsa.EncryptOAEP,
			"EncryptPKCS1v15": rsa.EncryptPKCS1v15,
			"GenerateKey": rsa.GenerateKey,
			"GenerateMultiPrimeKey": rsa.GenerateMultiPrimeKey,
			"SignPKCS1v15": rsa.SignPKCS1v15,
			"SignPSS": rsa.SignPSS,
			"VerifyPKCS1v15": rsa.VerifyPKCS1v15,
			"VerifyPSS": rsa.VerifyPSS,
			"ErrDecryption": rsa.ErrDecryption,
			"ErrMessageTooLong": rsa.ErrMessageTooLong,
			"ErrVerification": rsa.ErrVerification,
			"PSSSaltLengthAuto": rsa.PSSSaltLengthAuto,
			"PSSSaltLengthEqualsHash": rsa.PSSSaltLengthEqualsHash,
		},
	)
	registerType("crypto/rsa", "CRTValue", reflect.TypeOf((*rsa.CRTValue)(nil)).Elem())
	registerType("crypto/rsa", "OAEPOptions", reflect.TypeOf((*rsa.OAEPOptions)(nil)).Elem())
	registerType("crypto/rsa", "PKCS1v15DecryptOptions", reflect.TypeOf((*rsa.PKCS1v15DecryptOptions)(nil)).Elem())
	registerType("crypto/rsa", "PSSOptions", reflect.TypeOf((*rsa.PSSOptions)(nil)).Elem())
	registerType("crypto/rsa", "PrecomputedValues", reflect.TypeOf((*rsa.PrecomputedValues)(nil)).Elem())
	registerType("crypto/rsa", "PrivateKey", reflect.TypeOf((*rsa.PrivateKey)(nil)).Elem())
	registerType("crypto/rsa", "PublicKey", reflect.TypeOf((*rsa.PublicKey)(nil)).Elem())
}

