// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/ast

package microlisp

import (
	ast "go/ast"
	"reflect"
)

func register_go_ast() {
	registerPackage(
		"go/ast",
		map[string]interface{}{
			"FileExports": ast.FileExports,
			"FilterDecl": ast.FilterDecl,
			"FilterFile": ast.FilterFile,
			"FilterPackage": ast.FilterPackage,
			"Fprint": ast.Fprint,
			"Inspect": ast.Inspect,
			"IsExported": ast.IsExported,
			"IsGenerated": ast.IsGenerated,
			"MergePackageFiles": ast.MergePackageFiles,
			"NewCommentMap": ast.NewCommentMap,
			"NewIdent": ast.NewIdent,
			"NewObj": ast.NewObj,
			"NewPackage": ast.NewPackage,
			"NewScope": ast.NewScope,
			"NotNilFilter": ast.NotNilFilter,
			"PackageExports": ast.PackageExports,
			"Print": ast.Print,
			"SortImports": ast.SortImports,
			"Walk": ast.Walk,
			"Bad": ast.Bad,
			"Con": ast.Con,
			"FilterFuncDuplicates": ast.FilterFuncDuplicates,
			"FilterImportDuplicates": ast.FilterImportDuplicates,
			"FilterUnassociatedComments": ast.FilterUnassociatedComments,
			"Fun": ast.Fun,
			"Lbl": ast.Lbl,
			"Pkg": ast.Pkg,
			"RECV": ast.RECV,
			"SEND": ast.SEND,
			"Typ": ast.Typ,
			"Var": ast.Var,
		},
	)
	registerType("go/ast", "ArrayType", reflect.TypeOf((*ast.ArrayType)(nil)).Elem())
	registerType("go/ast", "AssignStmt", reflect.TypeOf((*ast.AssignStmt)(nil)).Elem())
	registerType("go/ast", "BadDecl", reflect.TypeOf((*ast.BadDecl)(nil)).Elem())
	registerType("go/ast", "BadExpr", reflect.TypeOf((*ast.BadExpr)(nil)).Elem())
	registerType("go/ast", "BadStmt", reflect.TypeOf((*ast.BadStmt)(nil)).Elem())
	registerType("go/ast", "BasicLit", reflect.TypeOf((*ast.BasicLit)(nil)).Elem())
	registerType("go/ast", "BinaryExpr", reflect.TypeOf((*ast.BinaryExpr)(nil)).Elem())
	registerType("go/ast", "BlockStmt", reflect.TypeOf((*ast.BlockStmt)(nil)).Elem())
	registerType("go/ast", "BranchStmt", reflect.TypeOf((*ast.BranchStmt)(nil)).Elem())
	registerType("go/ast", "CallExpr", reflect.TypeOf((*ast.CallExpr)(nil)).Elem())
	registerType("go/ast", "CaseClause", reflect.TypeOf((*ast.CaseClause)(nil)).Elem())
	registerType("go/ast", "ChanDir", reflect.TypeOf((*ast.ChanDir)(nil)).Elem())
	registerType("go/ast", "ChanType", reflect.TypeOf((*ast.ChanType)(nil)).Elem())
	registerType("go/ast", "CommClause", reflect.TypeOf((*ast.CommClause)(nil)).Elem())
	registerType("go/ast", "Comment", reflect.TypeOf((*ast.Comment)(nil)).Elem())
	registerType("go/ast", "CommentGroup", reflect.TypeOf((*ast.CommentGroup)(nil)).Elem())
	registerType("go/ast", "CommentMap", reflect.TypeOf((*ast.CommentMap)(nil)).Elem())
	registerType("go/ast", "CompositeLit", reflect.TypeOf((*ast.CompositeLit)(nil)).Elem())
	registerType("go/ast", "Decl", reflect.TypeOf((*ast.Decl)(nil)).Elem())
	registerType("go/ast", "DeclStmt", reflect.TypeOf((*ast.DeclStmt)(nil)).Elem())
	registerType("go/ast", "DeferStmt", reflect.TypeOf((*ast.DeferStmt)(nil)).Elem())
	registerType("go/ast", "Ellipsis", reflect.TypeOf((*ast.Ellipsis)(nil)).Elem())
	registerType("go/ast", "EmptyStmt", reflect.TypeOf((*ast.EmptyStmt)(nil)).Elem())
	registerType("go/ast", "Expr", reflect.TypeOf((*ast.Expr)(nil)).Elem())
	registerType("go/ast", "ExprStmt", reflect.TypeOf((*ast.ExprStmt)(nil)).Elem())
	registerType("go/ast", "Field", reflect.TypeOf((*ast.Field)(nil)).Elem())
	registerType("go/ast", "FieldFilter", reflect.TypeOf((*ast.FieldFilter)(nil)).Elem())
	registerType("go/ast", "FieldList", reflect.TypeOf((*ast.FieldList)(nil)).Elem())
	registerType("go/ast", "File", reflect.TypeOf((*ast.File)(nil)).Elem())
	registerType("go/ast", "Filter", reflect.TypeOf((*ast.Filter)(nil)).Elem())
	registerType("go/ast", "ForStmt", reflect.TypeOf((*ast.ForStmt)(nil)).Elem())
	registerType("go/ast", "FuncDecl", reflect.TypeOf((*ast.FuncDecl)(nil)).Elem())
	registerType("go/ast", "FuncLit", reflect.TypeOf((*ast.FuncLit)(nil)).Elem())
	registerType("go/ast", "FuncType", reflect.TypeOf((*ast.FuncType)(nil)).Elem())
	registerType("go/ast", "GenDecl", reflect.TypeOf((*ast.GenDecl)(nil)).Elem())
	registerType("go/ast", "GoStmt", reflect.TypeOf((*ast.GoStmt)(nil)).Elem())
	registerType("go/ast", "Ident", reflect.TypeOf((*ast.Ident)(nil)).Elem())
	registerType("go/ast", "IfStmt", reflect.TypeOf((*ast.IfStmt)(nil)).Elem())
	registerType("go/ast", "ImportSpec", reflect.TypeOf((*ast.ImportSpec)(nil)).Elem())
	registerType("go/ast", "Importer", reflect.TypeOf((*ast.Importer)(nil)).Elem())
	registerType("go/ast", "IncDecStmt", reflect.TypeOf((*ast.IncDecStmt)(nil)).Elem())
	registerType("go/ast", "IndexExpr", reflect.TypeOf((*ast.IndexExpr)(nil)).Elem())
	registerType("go/ast", "IndexListExpr", reflect.TypeOf((*ast.IndexListExpr)(nil)).Elem())
	registerType("go/ast", "InterfaceType", reflect.TypeOf((*ast.InterfaceType)(nil)).Elem())
	registerType("go/ast", "KeyValueExpr", reflect.TypeOf((*ast.KeyValueExpr)(nil)).Elem())
	registerType("go/ast", "LabeledStmt", reflect.TypeOf((*ast.LabeledStmt)(nil)).Elem())
	registerType("go/ast", "MapType", reflect.TypeOf((*ast.MapType)(nil)).Elem())
	registerType("go/ast", "MergeMode", reflect.TypeOf((*ast.MergeMode)(nil)).Elem())
	registerType("go/ast", "Node", reflect.TypeOf((*ast.Node)(nil)).Elem())
	registerType("go/ast", "ObjKind", reflect.TypeOf((*ast.ObjKind)(nil)).Elem())
	registerType("go/ast", "Object", reflect.TypeOf((*ast.Object)(nil)).Elem())
	registerType("go/ast", "Package", reflect.TypeOf((*ast.Package)(nil)).Elem())
	registerType("go/ast", "ParenExpr", reflect.TypeOf((*ast.ParenExpr)(nil)).Elem())
	registerType("go/ast", "RangeStmt", reflect.TypeOf((*ast.RangeStmt)(nil)).Elem())
	registerType("go/ast", "ReturnStmt", reflect.TypeOf((*ast.ReturnStmt)(nil)).Elem())
	registerType("go/ast", "Scope", reflect.TypeOf((*ast.Scope)(nil)).Elem())
	registerType("go/ast", "SelectStmt", reflect.TypeOf((*ast.SelectStmt)(nil)).Elem())
	registerType("go/ast", "SelectorExpr", reflect.TypeOf((*ast.SelectorExpr)(nil)).Elem())
	registerType("go/ast", "SendStmt", reflect.TypeOf((*ast.SendStmt)(nil)).Elem())
	registerType("go/ast", "SliceExpr", reflect.TypeOf((*ast.SliceExpr)(nil)).Elem())
	registerType("go/ast", "Spec", reflect.TypeOf((*ast.Spec)(nil)).Elem())
	registerType("go/ast", "StarExpr", reflect.TypeOf((*ast.StarExpr)(nil)).Elem())
	registerType("go/ast", "Stmt", reflect.TypeOf((*ast.Stmt)(nil)).Elem())
	registerType("go/ast", "StructType", reflect.TypeOf((*ast.StructType)(nil)).Elem())
	registerType("go/ast", "SwitchStmt", reflect.TypeOf((*ast.SwitchStmt)(nil)).Elem())
	registerType("go/ast", "TypeAssertExpr", reflect.TypeOf((*ast.TypeAssertExpr)(nil)).Elem())
	registerType("go/ast", "TypeSpec", reflect.TypeOf((*ast.TypeSpec)(nil)).Elem())
	registerType("go/ast", "TypeSwitchStmt", reflect.TypeOf((*ast.TypeSwitchStmt)(nil)).Elem())
	registerType("go/ast", "UnaryExpr", reflect.TypeOf((*ast.UnaryExpr)(nil)).Elem())
	registerType("go/ast", "ValueSpec", reflect.TypeOf((*ast.ValueSpec)(nil)).Elem())
	registerType("go/ast", "Visitor", reflect.TypeOf((*ast.Visitor)(nil)).Elem())
}

