// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: debug/macho

package microlisp

import (
	macho "debug/macho"
	"reflect"
)

func register_debug_macho() {
	registerPackage(
		"debug/macho",
		map[string]interface{}{
			"NewFatFile": macho.NewFatFile,
			"NewFile": macho.NewFile,
			"Open": macho.Open,
			"OpenFat": macho.OpenFat,
			"ErrNotFat": macho.ErrNotFat,
			"FlagAllModsBound": macho.FlagAllModsBound,
			"FlagAllowStackExecution": macho.FlagAllowStackExecution,
			"FlagAppExtensionSafe": macho.FlagAppExtensionSafe,
			"FlagBindAtLoad": macho.FlagBindAtLoad,
			"FlagBindsToWeak": macho.FlagBindsToWeak,
			"FlagCanonical": macho.FlagCanonical,
			"FlagDeadStrippableDylib": macho.FlagDeadStrippableDylib,
			"FlagDyldLink": macho.FlagDyldLink,
			"FlagForceFlat": macho.FlagForceFlat,
			"FlagHasTLVDescriptors": macho.FlagHasTLVDescriptors,
			"FlagIncrLink": macho.FlagIncrLink,
			"FlagLazyInit": macho.FlagLazyInit,
			"FlagNoFixPrebinding": macho.FlagNoFixPrebinding,
			"FlagNoHeapExecution": macho.FlagNoHeapExecution,
			"FlagNoMultiDefs": macho.FlagNoMultiDefs,
			"FlagNoReexportedDylibs": macho.FlagNoReexportedDylibs,
			"FlagNoUndefs": macho.FlagNoUndefs,
			"FlagPIE": macho.FlagPIE,
			"FlagPrebindable": macho.FlagPrebindable,
			"FlagPrebound": macho.FlagPrebound,
			"FlagRootSafe": macho.FlagRootSafe,
			"FlagSetuidSafe": macho.FlagSetuidSafe,
			"FlagSplitSegs": macho.FlagSplitSegs,
			"FlagSubsectionsViaSymbols": macho.FlagSubsectionsViaSymbols,
			"FlagTwoLevel": macho.FlagTwoLevel,
			"FlagWeakDefines": macho.FlagWeakDefines,
			"Magic32": macho.Magic32,
			"Magic64": macho.Magic64,
			"MagicFat": macho.MagicFat,
		},
	)
	registerType("debug/macho", "Cpu", reflect.TypeOf((*macho.Cpu)(nil)).Elem())
	registerType("debug/macho", "Dylib", reflect.TypeOf((*macho.Dylib)(nil)).Elem())
	registerType("debug/macho", "DylibCmd", reflect.TypeOf((*macho.DylibCmd)(nil)).Elem())
	registerType("debug/macho", "Dysymtab", reflect.TypeOf((*macho.Dysymtab)(nil)).Elem())
	registerType("debug/macho", "DysymtabCmd", reflect.TypeOf((*macho.DysymtabCmd)(nil)).Elem())
	registerType("debug/macho", "FatArch", reflect.TypeOf((*macho.FatArch)(nil)).Elem())
	registerType("debug/macho", "FatArchHeader", reflect.TypeOf((*macho.FatArchHeader)(nil)).Elem())
	registerType("debug/macho", "FatFile", reflect.TypeOf((*macho.FatFile)(nil)).Elem())
	registerType("debug/macho", "File", reflect.TypeOf((*macho.File)(nil)).Elem())
	registerType("debug/macho", "FileHeader", reflect.TypeOf((*macho.FileHeader)(nil)).Elem())
	registerType("debug/macho", "FormatError", reflect.TypeOf((*macho.FormatError)(nil)).Elem())
	registerType("debug/macho", "Load", reflect.TypeOf((*macho.Load)(nil)).Elem())
	registerType("debug/macho", "LoadBytes", reflect.TypeOf((*macho.LoadBytes)(nil)).Elem())
	registerType("debug/macho", "LoadCmd", reflect.TypeOf((*macho.LoadCmd)(nil)).Elem())
	registerType("debug/macho", "Nlist32", reflect.TypeOf((*macho.Nlist32)(nil)).Elem())
	registerType("debug/macho", "Nlist64", reflect.TypeOf((*macho.Nlist64)(nil)).Elem())
	registerType("debug/macho", "Regs386", reflect.TypeOf((*macho.Regs386)(nil)).Elem())
	registerType("debug/macho", "RegsAMD64", reflect.TypeOf((*macho.RegsAMD64)(nil)).Elem())
	registerType("debug/macho", "Reloc", reflect.TypeOf((*macho.Reloc)(nil)).Elem())
	registerType("debug/macho", "RelocTypeARM", reflect.TypeOf((*macho.RelocTypeARM)(nil)).Elem())
	registerType("debug/macho", "RelocTypeARM64", reflect.TypeOf((*macho.RelocTypeARM64)(nil)).Elem())
	registerType("debug/macho", "RelocTypeGeneric", reflect.TypeOf((*macho.RelocTypeGeneric)(nil)).Elem())
	registerType("debug/macho", "RelocTypeX86_64", reflect.TypeOf((*macho.RelocTypeX86_64)(nil)).Elem())
	registerType("debug/macho", "Rpath", reflect.TypeOf((*macho.Rpath)(nil)).Elem())
	registerType("debug/macho", "RpathCmd", reflect.TypeOf((*macho.RpathCmd)(nil)).Elem())
	registerType("debug/macho", "Section", reflect.TypeOf((*macho.Section)(nil)).Elem())
	registerType("debug/macho", "Section32", reflect.TypeOf((*macho.Section32)(nil)).Elem())
	registerType("debug/macho", "Section64", reflect.TypeOf((*macho.Section64)(nil)).Elem())
	registerType("debug/macho", "SectionHeader", reflect.TypeOf((*macho.SectionHeader)(nil)).Elem())
	registerType("debug/macho", "Segment", reflect.TypeOf((*macho.Segment)(nil)).Elem())
	registerType("debug/macho", "Segment32", reflect.TypeOf((*macho.Segment32)(nil)).Elem())
	registerType("debug/macho", "Segment64", reflect.TypeOf((*macho.Segment64)(nil)).Elem())
	registerType("debug/macho", "SegmentHeader", reflect.TypeOf((*macho.SegmentHeader)(nil)).Elem())
	registerType("debug/macho", "Symbol", reflect.TypeOf((*macho.Symbol)(nil)).Elem())
	registerType("debug/macho", "Symtab", reflect.TypeOf((*macho.Symtab)(nil)).Elem())
	registerType("debug/macho", "SymtabCmd", reflect.TypeOf((*macho.SymtabCmd)(nil)).Elem())
	registerType("debug/macho", "Thread", reflect.TypeOf((*macho.Thread)(nil)).Elem())
	registerType("debug/macho", "Type", reflect.TypeOf((*macho.Type)(nil)).Elem())
}

