// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: image/draw

package microlisp

import (
	draw "image/draw"
	"reflect"
)

func register_image_draw() {
	registerPackage(
		"image/draw",
		map[string]interface{}{
			"Draw": draw.Draw,
			"DrawMask": draw.DrawMask,
			"FloydSteinberg": draw.FloydSteinberg,
		},
	)
	registerType("image/draw", "Drawer", reflect.TypeOf((*draw.Drawer)(nil)).Elem())
	registerType("image/draw", "Image", reflect.TypeOf((*draw.Image)(nil)).Elem())
	registerType("image/draw", "Op", reflect.TypeOf((*draw.Op)(nil)).Elem())
	registerType("image/draw", "Quantizer", reflect.TypeOf((*draw.Quantizer)(nil)).Elem())
	registerType("image/draw", "RGBA64Image", reflect.TypeOf((*draw.RGBA64Image)(nil)).Elem())
}

