// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto

package microlisp

import (
	crypto "crypto"
	"reflect"
)

func register_crypto() {
	registerPackage(
		"crypto",
		map[string]interface{}{
			"RegisterHash": crypto.RegisterHash,
		},
	)
	registerType("crypto", "Decrypter", reflect.TypeOf((*crypto.Decrypter)(nil)).Elem())
	registerType("crypto", "DecrypterOpts", reflect.TypeOf((*crypto.DecrypterOpts)(nil)).Elem())
	registerType("crypto", "Hash", reflect.TypeOf((*crypto.Hash)(nil)).Elem())
	registerType("crypto", "PrivateKey", reflect.TypeOf((*crypto.PrivateKey)(nil)).Elem())
	registerType("crypto", "PublicKey", reflect.TypeOf((*crypto.PublicKey)(nil)).Elem())
	registerType("crypto", "Signer", reflect.TypeOf((*crypto.Signer)(nil)).Elem())
	registerType("crypto", "SignerOpts", reflect.TypeOf((*crypto.SignerOpts)(nil)).Elem())
}

