// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: net/http/cookiejar

package microlisp

import (
	cookiejar "net/http/cookiejar"
	"reflect"
)

func register_net_http_cookiejar() {
	registerPackage(
		"net/http/cookiejar",
		map[string]interface{}{
			"New": cookiejar.New,
		},
	)
	registerType("net/http/cookiejar", "Jar", reflect.TypeOf((*cookiejar.Jar)(nil)).Elem())
	registerType("net/http/cookiejar", "Options", reflect.TypeOf((*cookiejar.Options)(nil)).Elem())
	registerType("net/http/cookiejar", "PublicSuffixList", reflect.TypeOf((*cookiejar.PublicSuffixList)(nil)).Elem())
}

