// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/json

package microlisp

import (
	json "encoding/json"
	"reflect"
)

func register_encoding_json() {
	registerPackage(
		"encoding/json",
		map[string]interface{}{
			"Compact": json.Compact,
			"HTMLEscape": json.HTMLEscape,
			"Indent": json.Indent,
			"Marshal": json.Marshal,
			"MarshalIndent": json.MarshalIndent,
			"NewDecoder": json.NewDecoder,
			"NewEncoder": json.NewEncoder,
			"Unmarshal": json.Unmarshal,
			"Valid": json.Valid,
		},
	)
	registerType("encoding/json", "Decoder", reflect.TypeOf((*json.Decoder)(nil)).Elem())
	registerType("encoding/json", "Delim", reflect.TypeOf((*json.Delim)(nil)).Elem())
	registerType("encoding/json", "Encoder", reflect.TypeOf((*json.Encoder)(nil)).Elem())
	registerType("encoding/json", "InvalidUTF8Error", reflect.TypeOf((*json.InvalidUTF8Error)(nil)).Elem())
	registerType("encoding/json", "InvalidUnmarshalError", reflect.TypeOf((*json.InvalidUnmarshalError)(nil)).Elem())
	registerType("encoding/json", "Marshaler", reflect.TypeOf((*json.Marshaler)(nil)).Elem())
	registerType("encoding/json", "MarshalerError", reflect.TypeOf((*json.MarshalerError)(nil)).Elem())
	registerType("encoding/json", "Number", reflect.TypeOf((*json.Number)(nil)).Elem())
	registerType("encoding/json", "RawMessage", reflect.TypeOf((*json.RawMessage)(nil)).Elem())
	registerType("encoding/json", "SyntaxError", reflect.TypeOf((*json.SyntaxError)(nil)).Elem())
	registerType("encoding/json", "Token", reflect.TypeOf((*json.Token)(nil)).Elem())
	registerType("encoding/json", "UnmarshalFieldError", reflect.TypeOf((*json.UnmarshalFieldError)(nil)).Elem())
	registerType("encoding/json", "UnmarshalTypeError", reflect.TypeOf((*json.UnmarshalTypeError)(nil)).Elem())
	registerType("encoding/json", "Unmarshaler", reflect.TypeOf((*json.Unmarshaler)(nil)).Elem())
	registerType("encoding/json", "UnsupportedTypeError", reflect.TypeOf((*json.UnsupportedTypeError)(nil)).Elem())
	registerType("encoding/json", "UnsupportedValueError", reflect.TypeOf((*json.UnsupportedValueError)(nil)).Elem())
}

