// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/xml

package microlisp

import (
	xml "encoding/xml"
	"reflect"
)

func register_encoding_xml() {
	registerPackage(
		"encoding/xml",
		map[string]interface{}{
			"CopyToken": xml.CopyToken,
			"Escape": xml.Escape,
			"EscapeText": xml.EscapeText,
			"Marshal": xml.Marshal,
			"MarshalIndent": xml.MarshalIndent,
			"NewDecoder": xml.NewDecoder,
			"NewEncoder": xml.NewEncoder,
			"NewTokenDecoder": xml.NewTokenDecoder,
			"Unmarshal": xml.Unmarshal,
			"HTMLAutoClose": xml.HTMLAutoClose,
			"HTMLEntity": xml.HTMLEntity,
			"Header": xml.Header,
		},
	)
	registerType("encoding/xml", "Attr", reflect.TypeOf((*xml.Attr)(nil)).Elem())
	registerType("encoding/xml", "CharData", reflect.TypeOf((*xml.CharData)(nil)).Elem())
	registerType("encoding/xml", "Comment", reflect.TypeOf((*xml.Comment)(nil)).Elem())
	registerType("encoding/xml", "Decoder", reflect.TypeOf((*xml.Decoder)(nil)).Elem())
	registerType("encoding/xml", "Directive", reflect.TypeOf((*xml.Directive)(nil)).Elem())
	registerType("encoding/xml", "Encoder", reflect.TypeOf((*xml.Encoder)(nil)).Elem())
	registerType("encoding/xml", "EndElement", reflect.TypeOf((*xml.EndElement)(nil)).Elem())
	registerType("encoding/xml", "Marshaler", reflect.TypeOf((*xml.Marshaler)(nil)).Elem())
	registerType("encoding/xml", "MarshalerAttr", reflect.TypeOf((*xml.MarshalerAttr)(nil)).Elem())
	registerType("encoding/xml", "Name", reflect.TypeOf((*xml.Name)(nil)).Elem())
	registerType("encoding/xml", "ProcInst", reflect.TypeOf((*xml.ProcInst)(nil)).Elem())
	registerType("encoding/xml", "StartElement", reflect.TypeOf((*xml.StartElement)(nil)).Elem())
	registerType("encoding/xml", "SyntaxError", reflect.TypeOf((*xml.SyntaxError)(nil)).Elem())
	registerType("encoding/xml", "TagPathError", reflect.TypeOf((*xml.TagPathError)(nil)).Elem())
	registerType("encoding/xml", "Token", reflect.TypeOf((*xml.Token)(nil)).Elem())
	registerType("encoding/xml", "TokenReader", reflect.TypeOf((*xml.TokenReader)(nil)).Elem())
	registerType("encoding/xml", "UnmarshalError", reflect.TypeOf((*xml.UnmarshalError)(nil)).Elem())
	registerType("encoding/xml", "Unmarshaler", reflect.TypeOf((*xml.Unmarshaler)(nil)).Elem())
	registerType("encoding/xml", "UnmarshalerAttr", reflect.TypeOf((*xml.UnmarshalerAttr)(nil)).Elem())
	registerType("encoding/xml", "UnsupportedTypeError", reflect.TypeOf((*xml.UnsupportedTypeError)(nil)).Elem())
}

