// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/rand

package microlisp

import (
	rand "crypto/rand"
)

func register_crypto_rand() {
	registerPackage(
		"crypto/rand",
		map[string]interface{}{
			"Int": rand.Int,
			"Prime": rand.Prime,
			"Read": rand.Read,
			"Reader": rand.Reader,
		},
	)
}

