// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: html/template

package microlisp

import (
	template "html/template"
	"reflect"
)

func register_html_template() {
	registerPackage(
		"html/template",
		map[string]interface{}{
			"HTMLEscape": template.HTMLEscape,
			"HTMLEscapeString": template.HTMLEscapeString,
			"HTMLEscaper": template.HTMLEscaper,
			"IsTrue": template.IsTrue,
			"JSEscape": template.JSEscape,
			"JSEscapeString": template.JSEscapeString,
			"JSEscaper": template.JSEscaper,
			"Must": template.Must,
			"New": template.New,
			"ParseFS": template.ParseFS,
			"ParseFiles": template.ParseFiles,
			"ParseGlob": template.ParseGlob,
			"URLQueryEscaper": template.URLQueryEscaper,
			"ErrAmbigContext": template.ErrAmbigContext,
			"ErrBadHTML": template.ErrBadHTML,
			"ErrBranchEnd": template.ErrBranchEnd,
			"ErrEndContext": template.ErrEndContext,
			"ErrJSTemplate": template.ErrJSTemplate,
			"ErrNoSuchTemplate": template.ErrNoSuchTemplate,
			"ErrOutputContext": template.ErrOutputContext,
			"ErrPartialCharset": template.ErrPartialCharset,
			"ErrPartialEscape": template.ErrPartialEscape,
			"ErrPredefinedEscaper": template.ErrPredefinedEscaper,
			"ErrRangeLoopReentry": template.ErrRangeLoopReentry,
			"ErrSlashAmbig": template.ErrSlashAmbig,
			"OK": template.OK,
		},
	)
	registerType("html/template", "CSS", reflect.TypeOf((*template.CSS)(nil)).Elem())
	registerType("html/template", "Error", reflect.TypeOf((*template.Error)(nil)).Elem())
	registerType("html/template", "ErrorCode", reflect.TypeOf((*template.ErrorCode)(nil)).Elem())
	registerType("html/template", "FuncMap", reflect.TypeOf((*template.FuncMap)(nil)).Elem())
	registerType("html/template", "HTML", reflect.TypeOf((*template.HTML)(nil)).Elem())
	registerType("html/template", "HTMLAttr", reflect.TypeOf((*template.HTMLAttr)(nil)).Elem())
	registerType("html/template", "JS", reflect.TypeOf((*template.JS)(nil)).Elem())
	registerType("html/template", "JSStr", reflect.TypeOf((*template.JSStr)(nil)).Elem())
	registerType("html/template", "Srcset", reflect.TypeOf((*template.Srcset)(nil)).Elem())
	registerType("html/template", "Template", reflect.TypeOf((*template.Template)(nil)).Elem())
	registerType("html/template", "URL", reflect.TypeOf((*template.URL)(nil)).Elem())
}

