// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: path

package microlisp

import (
	path "path"
)

func register_path() {
	registerPackage(
		"path",
		map[string]interface{}{
			"Base": path.Base,
			"Clean": path.Clean,
			"Dir": path.Dir,
			"Ext": path.Ext,
			"IsAbs": path.IsAbs,
			"Join": path.Join,
			"Match": path.Match,
			"Split": path.Split,
			"ErrBadPattern": path.ErrBadPattern,
		},
	)
}

