// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: testing/fstest

package microlisp

import (
	fstest "testing/fstest"
	"reflect"
)

func register_testing_fstest() {
	registerPackage(
		"testing/fstest",
		map[string]interface{}{
			"TestFS": fstest.TestFS,
		},
	)
	registerType("testing/fstest", "MapFS", reflect.TypeOf((*fstest.MapFS)(nil)).Elem())
	registerType("testing/fstest", "MapFile", reflect.TypeOf((*fstest.MapFile)(nil)).Elem())
}

