// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: unicode/utf8

package microlisp

import (
	utf8 "unicode/utf8"
)

func register_unicode_utf8() {
	registerPackage(
		"unicode/utf8",
		map[string]interface{}{
			"AppendRune": utf8.AppendRune,
			"DecodeLastRune": utf8.DecodeLastRune,
			"DecodeLastRuneInString": utf8.DecodeLastRuneInString,
			"DecodeRune": utf8.DecodeRune,
			"DecodeRuneInString": utf8.DecodeRuneInString,
			"EncodeRune": utf8.EncodeRune,
			"FullRune": utf8.FullRune,
			"FullRuneInString": utf8.FullRuneInString,
			"RuneCount": utf8.RuneCount,
			"RuneCountInString": utf8.RuneCountInString,
			"RuneLen": utf8.RuneLen,
			"RuneStart": utf8.RuneStart,
			"Valid": utf8.Valid,
			"ValidRune": utf8.ValidRune,
			"ValidString": utf8.ValidString,
			"MaxRune": utf8.MaxRune,
			"RuneError": utf8.RuneError,
			"RuneSelf": utf8.RuneSelf,
			"UTFMax": utf8.UTFMax,
		},
	)
}

