// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: mime

package microlisp

import (
	mime "mime"
	"reflect"
)

func register_mime() {
	registerPackage(
		"mime",
		map[string]interface{}{
			"AddExtensionType": mime.AddExtensionType,
			"ExtensionsByType": mime.ExtensionsByType,
			"FormatMediaType": mime.FormatMediaType,
			"ParseMediaType": mime.ParseMediaType,
			"TypeByExtension": mime.TypeByExtension,
			"ErrInvalidMediaParameter": mime.ErrInvalidMediaParameter,
		},
	)
	registerType("mime", "WordDecoder", reflect.TypeOf((*mime.WordDecoder)(nil)).Elem())
	registerType("mime", "WordEncoder", reflect.TypeOf((*mime.WordEncoder)(nil)).Elem())
}

