// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: testing/iotest

package microlisp

import (
	iotest "testing/iotest"
)

func register_testing_iotest() {
	registerPackage(
		"testing/iotest",
		map[string]interface{}{
			"DataErrReader": iotest.DataErrReader,
			"ErrReader": iotest.ErrReader,
			"HalfReader": iotest.HalfReader,
			"NewReadLogger": iotest.NewReadLogger,
			"NewWriteLogger": iotest.NewWriteLogger,
			"OneByteReader": iotest.OneByteReader,
			"TestReader": iotest.TestReader,
			"TimeoutReader": iotest.TimeoutReader,
			"TruncateWriter": iotest.TruncateWriter,
			"ErrTimeout": iotest.ErrTimeout,
		},
	)
}

