// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: archive/zip

package microlisp

import (
	zip "archive/zip"
	"reflect"
)

func register_archive_zip() {
	registerPackage(
		"archive/zip",
		map[string]interface{}{
			"FileInfoHeader": zip.FileInfoHeader,
			"NewReader": zip.NewReader,
			"NewWriter": zip.NewWriter,
			"OpenReader": zip.OpenReader,
			"RegisterCompressor": zip.RegisterCompressor,
			"RegisterDecompressor": zip.RegisterDecompressor,
			"ErrAlgorithm": zip.ErrAlgorithm,
			"ErrChecksum": zip.ErrChecksum,
			"ErrFormat": zip.ErrFormat,
			"ErrInsecurePath": zip.ErrInsecurePath,
			"Deflate": zip.Deflate,
			"Store": zip.Store,
		},
	)
	registerType("archive/zip", "Compressor", reflect.TypeOf((*zip.Compressor)(nil)).Elem())
	registerType("archive/zip", "Decompressor", reflect.TypeOf((*zip.Decompressor)(nil)).Elem())
	registerType("archive/zip", "File", reflect.TypeOf((*zip.File)(nil)).Elem())
	registerType("archive/zip", "FileHeader", reflect.TypeOf((*zip.FileHeader)(nil)).Elem())
	registerType("archive/zip", "ReadCloser", reflect.TypeOf((*zip.ReadCloser)(nil)).Elem())
	registerType("archive/zip", "Reader", reflect.TypeOf((*zip.Reader)(nil)).Elem())
	registerType("archive/zip", "Writer", reflect.TypeOf((*zip.Writer)(nil)).Elem())
}

