// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: path/filepath

package microlisp

import (
	filepath "path/filepath"
	"reflect"
)

func register_path_filepath() {
	registerPackage(
		"path/filepath",
		map[string]interface{}{
			"Abs": filepath.Abs,
			"Base": filepath.Base,
			"Clean": filepath.Clean,
			"Dir": filepath.Dir,
			"EvalSymlinks": filepath.EvalSymlinks,
			"Ext": filepath.Ext,
			"FromSlash": filepath.FromSlash,
			"Glob": filepath.Glob,
			"HasPrefix": filepath.HasPrefix,
			"IsAbs": filepath.IsAbs,
			"IsLocal": filepath.IsLocal,
			"Join": filepath.Join,
			"Match": filepath.Match,
			"Rel": filepath.Rel,
			"Split": filepath.Split,
			"SplitList": filepath.SplitList,
			"ToSlash": filepath.ToSlash,
			"VolumeName": filepath.VolumeName,
			"Walk": filepath.Walk,
			"WalkDir": filepath.WalkDir,
			"ErrBadPattern": filepath.ErrBadPattern,
			"SkipAll": filepath.SkipAll,
			"SkipDir": filepath.SkipDir,
			"ListSeparator": filepath.ListSeparator,
			"Separator": filepath.Separator,
		},
	)
	registerType("path/filepath", "WalkFunc", reflect.TypeOf((*filepath.WalkFunc)(nil)).Elem())
}

