// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: index/suffixarray

package microlisp

import (
	suffixarray "index/suffixarray"
	"reflect"
)

func register_index_suffixarray() {
	registerPackage(
		"index/suffixarray",
		map[string]interface{}{
			"New": suffixarray.New,
		},
	)
	registerType("index/suffixarray", "Index", reflect.TypeOf((*suffixarray.Index)(nil)).Elem())
}

