// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: container/list

package microlisp

import (
	listPkg "container/list"
	"reflect"
)

func register_container_list() {
	registerPackage(
		"container/list",
		map[string]interface{}{
			"New": listPkg.New,
		},
	)
	registerType("container/list", "Element", reflect.TypeOf((*listPkg.Element)(nil)).Elem())
	registerType("container/list", "List", reflect.TypeOf((*listPkg.List)(nil)).Elem())
}

