// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: html

package microlisp

import (
	html "html"
)

func register_html() {
	registerPackage(
		"html",
		map[string]interface{}{
			"EscapeString": html.EscapeString,
			"UnescapeString": html.UnescapeString,
		},
	)
}

