// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: compress/gzip

package microlisp

import (
	gzip "compress/gzip"
	"reflect"
)

func register_compress_gzip() {
	registerPackage(
		"compress/gzip",
		map[string]interface{}{
			"NewReader": gzip.NewReader,
			"NewWriter": gzip.NewWriter,
			"NewWriterLevel": gzip.NewWriterLevel,
			"ErrChecksum": gzip.ErrChecksum,
			"ErrHeader": gzip.ErrHeader,
			"BestCompression": gzip.BestCompression,
			"BestSpeed": gzip.BestSpeed,
			"DefaultCompression": gzip.DefaultCompression,
			"HuffmanOnly": gzip.HuffmanOnly,
			"NoCompression": gzip.NoCompression,
		},
	)
	registerType("compress/gzip", "Header", reflect.TypeOf((*gzip.Header)(nil)).Elem())
	registerType("compress/gzip", "Reader", reflect.TypeOf((*gzip.Reader)(nil)).Elem())
	registerType("compress/gzip", "Writer", reflect.TypeOf((*gzip.Writer)(nil)).Elem())
}

