// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: hash/crc64

package microlisp

import (
	crc64 "hash/crc64"
	"reflect"
)

func register_hash_crc64() {
	registerPackage(
		"hash/crc64",
		map[string]interface{}{
			"Checksum": crc64.Checksum,
			"MakeTable": crc64.MakeTable,
			"New": crc64.New,
			"Update": crc64.Update,
			"Size": crc64.Size,
		},
	)
	registerType("hash/crc64", "Table", reflect.TypeOf((*crc64.Table)(nil)).Elem())
}

