// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: flag

package microlisp

import (
	flag "flag"
	"reflect"
)

func register_flag() {
	registerPackage(
		"flag",
		map[string]interface{}{
			"Arg": flag.Arg,
			"Args": flag.Args,
			"Bool": flag.Bool,
			"BoolFunc": flag.BoolFunc,
			"BoolVar": flag.BoolVar,
			"Duration": flag.Duration,
			"DurationVar": flag.DurationVar,
			"Float64": flag.Float64,
			"Float64Var": flag.Float64Var,
			"Func": flag.Func,
			"Int": flag.Int,
			"Int64": flag.Int64,
			"Int64Var": flag.Int64Var,
			"IntVar": flag.IntVar,
			"Lookup": flag.Lookup,
			"NArg": flag.NArg,
			"NFlag": flag.NFlag,
			"NewFlagSet": flag.NewFlagSet,
			"Parse": flag.Parse,
			"Parsed": flag.Parsed,
			"PrintDefaults": flag.PrintDefaults,
			"Set": flag.Set,
			"String": flag.String,
			"StringVar": flag.StringVar,
			"TextVar": flag.TextVar,
			"Uint": flag.Uint,
			"Uint64": flag.Uint64,
			"Uint64Var": flag.Uint64Var,
			"UintVar": flag.UintVar,
			"UnquoteUsage": flag.UnquoteUsage,
			"Var": flag.Var,
			"Visit": flag.Visit,
			"VisitAll": flag.VisitAll,
			"CommandLine": flag.CommandLine,
			"ErrHelp": flag.ErrHelp,
			"Usage": flag.Usage,
			"ContinueOnError": flag.ContinueOnError,
			"ExitOnError": flag.ExitOnError,
			"PanicOnError": flag.PanicOnError,
		},
	)
	registerType("flag", "ErrorHandling", reflect.TypeOf((*flag.ErrorHandling)(nil)).Elem())
	registerType("flag", "Flag", reflect.TypeOf((*flag.Flag)(nil)).Elem())
	registerType("flag", "FlagSet", reflect.TypeOf((*flag.FlagSet)(nil)).Elem())
	registerType("flag", "Getter", reflect.TypeOf((*flag.Getter)(nil)).Elem())
	registerType("flag", "Value", reflect.TypeOf((*flag.Value)(nil)).Elem())
}

