// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/csv

package microlisp

import (
	csv "encoding/csv"
	"reflect"
)

func register_encoding_csv() {
	registerPackage(
		"encoding/csv",
		map[string]interface{}{
			"NewReader": csv.NewReader,
			"NewWriter": csv.NewWriter,
			"ErrBareQuote": csv.ErrBareQuote,
			"ErrFieldCount": csv.ErrFieldCount,
			"ErrQuote": csv.ErrQuote,
			"ErrTrailingComma": csv.ErrTrailingComma,
		},
	)
	registerType("encoding/csv", "ParseError", reflect.TypeOf((*csv.ParseError)(nil)).Elem())
	registerType("encoding/csv", "Reader", reflect.TypeOf((*csv.Reader)(nil)).Elem())
	registerType("encoding/csv", "Writer", reflect.TypeOf((*csv.Writer)(nil)).Elem())
}

