// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: crypto/aes

package microlisp

import (
	aes "crypto/aes"
	"reflect"
)

func register_crypto_aes() {
	registerPackage(
		"crypto/aes",
		map[string]interface{}{
			"NewCipher": aes.NewCipher,
			"BlockSize": aes.BlockSize,
		},
	)
	registerType("crypto/aes", "KeySizeError", reflect.TypeOf((*aes.KeySizeError)(nil)).Elem())
}

