// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: fmt

package microlisp

import (
	fmt "fmt"
	"reflect"
)

func register_fmt() {
	registerPackage(
		"fmt",
		map[string]interface{}{
			"Append": fmt.Append,
			"Appendf": fmt.Appendf,
			"Appendln": fmt.Appendln,
			"Errorf": fmt.Errorf,
			"FormatString": fmt.FormatString,
			"Fprint": fmt.Fprint,
			"Fprintf": fmt.Fprintf,
			"Fprintln": fmt.Fprintln,
			"Fscan": fmt.Fscan,
			"Fscanf": fmt.Fscanf,
			"Fscanln": fmt.Fscanln,
			"Print": fmt.Print,
			"Printf": fmt.Printf,
			"Println": fmt.Println,
			"Scan": fmt.Scan,
			"Scanf": fmt.Scanf,
			"Scanln": fmt.Scanln,
			"Sprint": fmt.Sprint,
			"Sprintf": fmt.Sprintf,
			"Sprintln": fmt.Sprintln,
			"Sscan": fmt.Sscan,
			"Sscanf": fmt.Sscanf,
			"Sscanln": fmt.Sscanln,
		},
	)
	registerType("fmt", "Formatter", reflect.TypeOf((*fmt.Formatter)(nil)).Elem())
	registerType("fmt", "GoStringer", reflect.TypeOf((*fmt.GoStringer)(nil)).Elem())
	registerType("fmt", "ScanState", reflect.TypeOf((*fmt.ScanState)(nil)).Elem())
	registerType("fmt", "Scanner", reflect.TypeOf((*fmt.Scanner)(nil)).Elem())
	registerType("fmt", "State", reflect.TypeOf((*fmt.State)(nil)).Elem())
	registerType("fmt", "Stringer", reflect.TypeOf((*fmt.Stringer)(nil)).Elem())
}

