// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/gob

package microlisp

import (
	gob "encoding/gob"
	"reflect"
)

func register_encoding_gob() {
	registerPackage(
		"encoding/gob",
		map[string]interface{}{
			"NewDecoder": gob.NewDecoder,
			"NewEncoder": gob.NewEncoder,
			"Register": gob.Register,
			"RegisterName": gob.RegisterName,
		},
	)
	registerType("encoding/gob", "CommonType", reflect.TypeOf((*gob.CommonType)(nil)).Elem())
	registerType("encoding/gob", "Decoder", reflect.TypeOf((*gob.Decoder)(nil)).Elem())
	registerType("encoding/gob", "Encoder", reflect.TypeOf((*gob.Encoder)(nil)).Elem())
	registerType("encoding/gob", "GobDecoder", reflect.TypeOf((*gob.GobDecoder)(nil)).Elem())
	registerType("encoding/gob", "GobEncoder", reflect.TypeOf((*gob.GobEncoder)(nil)).Elem())
}

