// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: image

package microlisp

import (
	image "image"
	"reflect"
)

func register_image() {
	registerPackage(
		"image",
		map[string]interface{}{
			"Decode": image.Decode,
			"DecodeConfig": image.DecodeConfig,
			"NewAlpha": image.NewAlpha,
			"NewAlpha16": image.NewAlpha16,
			"NewCMYK": image.NewCMYK,
			"NewGray": image.NewGray,
			"NewGray16": image.NewGray16,
			"NewNRGBA": image.NewNRGBA,
			"NewNRGBA64": image.NewNRGBA64,
			"NewNYCbCrA": image.NewNYCbCrA,
			"NewPaletted": image.NewPaletted,
			"NewRGBA": image.NewRGBA,
			"NewRGBA64": image.NewRGBA64,
			"NewUniform": image.NewUniform,
			"NewYCbCr": image.NewYCbCr,
			"Pt": image.Pt,
			"Rect": image.Rect,
			"RegisterFormat": image.RegisterFormat,
			"Black": image.Black,
			"ErrFormat": image.ErrFormat,
			"Opaque": image.Opaque,
			"Transparent": image.Transparent,
			"White": image.White,
			"ZP": image.ZP,
			"ZR": image.ZR,
		},
	)
	registerType("image", "Alpha", reflect.TypeOf((*image.Alpha)(nil)).Elem())
	registerType("image", "Alpha16", reflect.TypeOf((*image.Alpha16)(nil)).Elem())
	registerType("image", "CMYK", reflect.TypeOf((*image.CMYK)(nil)).Elem())
	registerType("image", "Config", reflect.TypeOf((*image.Config)(nil)).Elem())
	registerType("image", "Gray", reflect.TypeOf((*image.Gray)(nil)).Elem())
	registerType("image", "Gray16", reflect.TypeOf((*image.Gray16)(nil)).Elem())
	registerType("image", "Image", reflect.TypeOf((*image.Image)(nil)).Elem())
	registerType("image", "NRGBA", reflect.TypeOf((*image.NRGBA)(nil)).Elem())
	registerType("image", "NRGBA64", reflect.TypeOf((*image.NRGBA64)(nil)).Elem())
	registerType("image", "NYCbCrA", reflect.TypeOf((*image.NYCbCrA)(nil)).Elem())
	registerType("image", "Paletted", reflect.TypeOf((*image.Paletted)(nil)).Elem())
	registerType("image", "PalettedImage", reflect.TypeOf((*image.PalettedImage)(nil)).Elem())
	registerType("image", "Point", reflect.TypeOf((*image.Point)(nil)).Elem())
	registerType("image", "RGBA", reflect.TypeOf((*image.RGBA)(nil)).Elem())
	registerType("image", "RGBA64", reflect.TypeOf((*image.RGBA64)(nil)).Elem())
	registerType("image", "RGBA64Image", reflect.TypeOf((*image.RGBA64Image)(nil)).Elem())
	registerType("image", "Rectangle", reflect.TypeOf((*image.Rectangle)(nil)).Elem())
	registerType("image", "Uniform", reflect.TypeOf((*image.Uniform)(nil)).Elem())
	registerType("image", "YCbCr", reflect.TypeOf((*image.YCbCr)(nil)).Elem())
	registerType("image", "YCbCrSubsampleRatio", reflect.TypeOf((*image.YCbCrSubsampleRatio)(nil)).Elem())
}

