// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: hash/maphash

package microlisp

import (
	maphash "hash/maphash"
	"reflect"
)

func register_hash_maphash() {
	registerPackage(
		"hash/maphash",
		map[string]interface{}{
			"Bytes": maphash.Bytes,
			"MakeSeed": maphash.MakeSeed,
			"String": maphash.String,
		},
	)
	registerType("hash/maphash", "Hash", reflect.TypeOf((*maphash.Hash)(nil)).Elem())
	registerType("hash/maphash", "Seed", reflect.TypeOf((*maphash.Seed)(nil)).Elem())
}

