// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: go/parser

package microlisp

import (
	parser "go/parser"
	"reflect"
)

func register_go_parser() {
	registerPackage(
		"go/parser",
		map[string]interface{}{
			"ParseDir": parser.ParseDir,
			"ParseExpr": parser.ParseExpr,
			"ParseExprFrom": parser.ParseExprFrom,
			"ParseFile": parser.ParseFile,
		},
	)
	registerType("go/parser", "Mode", reflect.TypeOf((*parser.Mode)(nil)).Elem())
}

