// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding

package microlisp

import (
	encoding "encoding"
	"reflect"
)

func register_encoding() {
	registerType("encoding", "BinaryMarshaler", reflect.TypeOf((*encoding.BinaryMarshaler)(nil)).Elem())
	registerType("encoding", "BinaryUnmarshaler", reflect.TypeOf((*encoding.BinaryUnmarshaler)(nil)).Elem())
	registerType("encoding", "TextMarshaler", reflect.TypeOf((*encoding.TextMarshaler)(nil)).Elem())
	registerType("encoding", "TextUnmarshaler", reflect.TypeOf((*encoding.TextUnmarshaler)(nil)).Elem())
}

