// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: regexp/syntax

package microlisp

import (
	syntax "regexp/syntax"
	"reflect"
)

func register_regexp_syntax() {
	registerPackage(
		"regexp/syntax",
		map[string]interface{}{
			"Compile": syntax.Compile,
			"EmptyOpContext": syntax.EmptyOpContext,
			"IsWordChar": syntax.IsWordChar,
			"Parse": syntax.Parse,
		},
	)
	registerType("regexp/syntax", "EmptyOp", reflect.TypeOf((*syntax.EmptyOp)(nil)).Elem())
	registerType("regexp/syntax", "Error", reflect.TypeOf((*syntax.Error)(nil)).Elem())
	registerType("regexp/syntax", "ErrorCode", reflect.TypeOf((*syntax.ErrorCode)(nil)).Elem())
	registerType("regexp/syntax", "Flags", reflect.TypeOf((*syntax.Flags)(nil)).Elem())
	registerType("regexp/syntax", "Inst", reflect.TypeOf((*syntax.Inst)(nil)).Elem())
	registerType("regexp/syntax", "InstOp", reflect.TypeOf((*syntax.InstOp)(nil)).Elem())
	registerType("regexp/syntax", "Op", reflect.TypeOf((*syntax.Op)(nil)).Elem())
	registerType("regexp/syntax", "Prog", reflect.TypeOf((*syntax.Prog)(nil)).Elem())
	registerType("regexp/syntax", "Regexp", reflect.TypeOf((*syntax.Regexp)(nil)).Elem())
}

