// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: bufio

package microlisp

import (
	bufio "bufio"
	"reflect"
)

func register_bufio() {
	registerPackage(
		"bufio",
		map[string]interface{}{
			"NewReadWriter": bufio.NewReadWriter,
			"NewReader": bufio.NewReader,
			"NewReaderSize": bufio.NewReaderSize,
			"NewScanner": bufio.NewScanner,
			"NewWriter": bufio.NewWriter,
			"NewWriterSize": bufio.NewWriterSize,
			"ScanBytes": bufio.ScanBytes,
			"ScanLines": bufio.ScanLines,
			"ScanRunes": bufio.ScanRunes,
			"ScanWords": bufio.ScanWords,
			"ErrAdvanceTooFar": bufio.ErrAdvanceTooFar,
			"ErrBadReadCount": bufio.ErrBadReadCount,
			"ErrBufferFull": bufio.ErrBufferFull,
			"ErrFinalToken": bufio.ErrFinalToken,
			"ErrInvalidUnreadByte": bufio.ErrInvalidUnreadByte,
			"ErrInvalidUnreadRune": bufio.ErrInvalidUnreadRune,
			"ErrNegativeAdvance": bufio.ErrNegativeAdvance,
			"ErrNegativeCount": bufio.ErrNegativeCount,
			"ErrTooLong": bufio.ErrTooLong,
			"MaxScanTokenSize": bufio.MaxScanTokenSize,
		},
	)
	registerType("bufio", "ReadWriter", reflect.TypeOf((*bufio.ReadWriter)(nil)).Elem())
	registerType("bufio", "Reader", reflect.TypeOf((*bufio.Reader)(nil)).Elem())
	registerType("bufio", "Scanner", reflect.TypeOf((*bufio.Scanner)(nil)).Elem())
	registerType("bufio", "SplitFunc", reflect.TypeOf((*bufio.SplitFunc)(nil)).Elem())
	registerType("bufio", "Writer", reflect.TypeOf((*bufio.Writer)(nil)).Elem())
}

