// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: container/ring

package microlisp

import (
	ring "container/ring"
	"reflect"
)

func register_container_ring() {
	registerPackage(
		"container/ring",
		map[string]interface{}{
			"New": ring.New,
		},
	)
	registerType("container/ring", "Ring", reflect.TypeOf((*ring.Ring)(nil)).Elem())
}

