// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: os/exec

package microlisp

import (
	exec "os/exec"
	"reflect"
)

func register_os_exec() {
	registerPackage(
		"os/exec",
		map[string]interface{}{
			"Command": exec.Command,
			"CommandContext": exec.CommandContext,
			"LookPath": exec.LookPath,
			"ErrDot": exec.ErrDot,
			"ErrNotFound": exec.ErrNotFound,
			"ErrWaitDelay": exec.ErrWaitDelay,
		},
	)
	registerType("os/exec", "Cmd", reflect.TypeOf((*exec.Cmd)(nil)).Elem())
	registerType("os/exec", "Error", reflect.TypeOf((*exec.Error)(nil)).Elem())
	registerType("os/exec", "ExitError", reflect.TypeOf((*exec.ExitError)(nil)).Elem())
}

