// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: os/signal

package microlisp

import (
	signal "os/signal"
)

func register_os_signal() {
	registerPackage(
		"os/signal",
		map[string]interface{}{
			"Ignore": signal.Ignore,
			"Ignored": signal.Ignored,
			"Notify": signal.Notify,
			"NotifyContext": signal.NotifyContext,
			"Reset": signal.Reset,
			"Stop": signal.Stop,
		},
	)
}

