// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: strings

package microlisp

import (
	strings "strings"
	"reflect"
)

func register_strings() {
	registerPackage(
		"strings",
		map[string]interface{}{
			"Clone": strings.Clone,
			"Compare": strings.Compare,
			"Contains": strings.Contains,
			"ContainsAny": strings.ContainsAny,
			"ContainsFunc": strings.ContainsFunc,
			"ContainsRune": strings.ContainsRune,
			"Count": strings.Count,
			"Cut": strings.Cut,
			"CutPrefix": strings.CutPrefix,
			"CutSuffix": strings.CutSuffix,
			"EqualFold": strings.EqualFold,
			"Fields": strings.Fields,
			"FieldsFunc": strings.FieldsFunc,
			"HasPrefix": strings.HasPrefix,
			"HasSuffix": strings.HasSuffix,
			"Index": strings.Index,
			"IndexAny": strings.IndexAny,
			"IndexByte": strings.IndexByte,
			"IndexFunc": strings.IndexFunc,
			"IndexRune": strings.IndexRune,
			"Join": strings.Join,
			"LastIndex": strings.LastIndex,
			"LastIndexAny": strings.LastIndexAny,
			"LastIndexByte": strings.LastIndexByte,
			"LastIndexFunc": strings.LastIndexFunc,
			"Map": strings.Map,
			"NewReader": strings.NewReader,
			"NewReplacer": strings.NewReplacer,
			"Repeat": strings.Repeat,
			"Replace": strings.Replace,
			"ReplaceAll": strings.ReplaceAll,
			"Split": strings.Split,
			"SplitAfter": strings.SplitAfter,
			"SplitAfterN": strings.SplitAfterN,
			"SplitN": strings.SplitN,
			"Title": strings.Title,
			"ToLower": strings.ToLower,
			"ToLowerSpecial": strings.ToLowerSpecial,
			"ToTitle": strings.ToTitle,
			"ToTitleSpecial": strings.ToTitleSpecial,
			"ToUpper": strings.ToUpper,
			"ToUpperSpecial": strings.ToUpperSpecial,
			"ToValidUTF8": strings.ToValidUTF8,
			"Trim": strings.Trim,
			"TrimFunc": strings.TrimFunc,
			"TrimLeft": strings.TrimLeft,
			"TrimLeftFunc": strings.TrimLeftFunc,
			"TrimPrefix": strings.TrimPrefix,
			"TrimRight": strings.TrimRight,
			"TrimRightFunc": strings.TrimRightFunc,
			"TrimSpace": strings.TrimSpace,
			"TrimSuffix": strings.TrimSuffix,
		},
	)
	registerType("strings", "Builder", reflect.TypeOf((*strings.Builder)(nil)).Elem())
	registerType("strings", "Reader", reflect.TypeOf((*strings.Reader)(nil)).Elem())
	registerType("strings", "Replacer", reflect.TypeOf((*strings.Replacer)(nil)).Elem())
}

