// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: encoding/binary

package microlisp

import (
	binary "encoding/binary"
	"reflect"
)

func register_encoding_binary() {
	registerPackage(
		"encoding/binary",
		map[string]interface{}{
			"AppendUvarint": binary.AppendUvarint,
			"AppendVarint": binary.AppendVarint,
			"PutUvarint": binary.PutUvarint,
			"PutVarint": binary.PutVarint,
			"Read": binary.Read,
			"ReadUvarint": binary.ReadUvarint,
			"ReadVarint": binary.ReadVarint,
			"Size": binary.Size,
			"Uvarint": binary.Uvarint,
			"Varint": binary.Varint,
			"Write": binary.Write,
			"BigEndian": binary.BigEndian,
			"LittleEndian": binary.LittleEndian,
			"NativeEndian": binary.NativeEndian,
			"MaxVarintLen16": binary.MaxVarintLen16,
			"MaxVarintLen32": binary.MaxVarintLen32,
			"MaxVarintLen64": binary.MaxVarintLen64,
		},
	)
	registerType("encoding/binary", "AppendByteOrder", reflect.TypeOf((*binary.AppendByteOrder)(nil)).Elem())
	registerType("encoding/binary", "ByteOrder", reflect.TypeOf((*binary.ByteOrder)(nil)).Elem())
}

