// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.
// Auto-registered Go stdlib package: testing/quick

package microlisp

import (
	quick "testing/quick"
	"reflect"
)

func register_testing_quick() {
	registerPackage(
		"testing/quick",
		map[string]interface{}{
			"Check": quick.Check,
			"CheckEqual": quick.CheckEqual,
			"Value": quick.Value,
		},
	)
	registerType("testing/quick", "CheckEqualError", reflect.TypeOf((*quick.CheckEqualError)(nil)).Elem())
	registerType("testing/quick", "CheckError", reflect.TypeOf((*quick.CheckError)(nil)).Elem())
	registerType("testing/quick", "Config", reflect.TypeOf((*quick.Config)(nil)).Elem())
	registerType("testing/quick", "Generator", reflect.TypeOf((*quick.Generator)(nil)).Elem())
	registerType("testing/quick", "SetupError", reflect.TypeOf((*quick.SetupError)(nil)).Elem())
}

