package main

import (
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
)

// generateGoLookupFile creates a Go source file with a lazy-load lookup table
// mapping Lisp function names to Go import paths. This avoids loading all
// wrappers at startup — instead, the eval loop auto-imports on first use.
func generateGoLookupFile(infos []PkgInfo) error {
	var b strings.Builder
	b.WriteString("// Code generated by microlisp/ffi_gen/main.go - DO NOT EDIT.\n")
	b.WriteString("// Lazy-load lookup table: Lisp name -> Go import path.\n")
	b.WriteString("// When a symbol is not found in the environment, the eval loop\n")
	b.WriteString("// checks this table and auto-imports the Go function on first use.\n\n")
	b.WriteString("package microlisp\n\n")

	totalEntries := 0
	totalSkipped := 0

	// Collect all entries - deduplicate Lisp names
	type entry struct {
		lispName string
		goPath   string
	}
	var entries []entry
	seenLispNames := map[string]bool{}

	for _, info := range infos {
		pkgSkipped := 0
		for _, fn := range info.Functions {
			sig := fn.Signature
			wrapper, skipReason := generateWrapperForFn(info.ImportPath, info.Name, sig)
			if skipReason != "" {
				pkgSkipped++
				continue
			}
			if wrapper == "" {
				continue
			}
			// Extract lisp name from the generated wrapper
			// Format: (define (lisp-name ...) ...)
			lispName := extractLispName(wrapper)
			if lispName == "" {
				continue
			}
			goPath := info.ImportPath + "." + sig.Name
			if seenLispNames[lispName] {
				// Duplicate Lisp name — disambiguate with package prefix
				parts := strings.SplitN(info.ImportPath, "/", 2)
				pkgSuffix := parts[len(parts)-1]
				lispName = strings.ReplaceAll(pkgSuffix, "/", "-") + "-" + lispName
				if seenLispNames[lispName] {
					pkgSkipped++
					continue
				}
			}
			seenLispNames[lispName] = true
			entries = append(entries, entry{lispName, goPath})
		}
		totalSkipped += pkgSkipped
	}

	// Sort by Lisp name for deterministic output
	sort.Slice(entries, func(i, j int) bool { return entries[i].lispName < entries[j].lispName })

	b.WriteString("// GoFFILazyTable maps Lisp function names to Go import paths.\n")
	b.WriteString("// When a symbol lookup fails, the evaluator checks this table\n")
	b.WriteString("// and auto-imports the Go function, then caches it in the environment.\n")
	b.WriteString("var GoFFILazyTable = map[string]string{\n")

	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\t%q: %q,\n", e.lispName, e.goPath))
		totalEntries++
	}

	b.WriteString("}\n\n")

	// Also generate a reverse lookup for go:apropos / help
	b.WriteString("// GoFFILazyTableByPkg groups Lisp names by Go package for apropos/help.\n")
	b.WriteString("var GoFFILazyTableByPkg = map[string][]string{\n")
	byPkg := map[string][]string{}
	for _, e := range entries {
		parts := strings.SplitN(e.goPath, ".", 2)
		pkg := parts[0]
		byPkg[pkg] = append(byPkg[pkg], e.lispName)
	}
	pkgs := make([]string, 0, len(byPkg))
	for p := range byPkg {
		pkgs = append(pkgs, p)
	}
	sort.Strings(pkgs)
	for _, p := range pkgs {
		names := byPkg[p]
		sort.Strings(names)
		b.WriteString(fmt.Sprintf("\t%q: {\n", p))
		for _, n := range names {
			b.WriteString(fmt.Sprintf("\t\t%q,\n", n))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	log.Printf("Generated Go lazy-load table: %d entries (%d skipped)", totalEntries, totalSkipped)

	outPath := "go_auto_wrapper_table.go"
	return os.WriteFile(outPath, []byte(b.String()), 0644)
}

// extractLispName extracts the function name from a (define (name ...) ...) form.
func extractLispName(wrapper string) string {
	// Format: (define (lisp-name ...) ...)
	i := strings.Index(wrapper, "(define (")
	if i < 0 {
		return ""
	}
	rest := wrapper[i+len("(define ("):]
	j := strings.IndexByte(rest, ' ')
	k := strings.IndexByte(rest, ')')
	end := len(rest)
	if j > 0 && j < end {
		end = j
	}
	if k > 0 && k < end {
		end = k
	}
	return rest[:end]
}

// generateLispFile creates a .lisp file with (define) wrappers for all
// Go stdlib functions whose signatures are compatible with Lisp type system.
// NOTE: This is kept for reference/debugging but is NOT loaded at runtime.
// The Go lookup table (go_auto_wrapper_table.go) is used instead for lazy loading.
func generateLispFile(infos []PkgInfo) error {
	var b strings.Builder
	b.WriteString(";;; Auto-generated by microlisp/ffi_gen/main.go - DO NOT EDIT.\n")
	b.WriteString(";;; Lisp wrappers for Go stdlib functions.\n")
	b.WriteString(";;; Each wrapper hides Go type system behind (funcall (go:import ...)) pattern.\n\n")

	totalWrappers := 0
	totalSkipped := 0

	for _, info := range infos {
		pkgWrappers := []string{}
		pkgSkipped := 0

		for _, fn := range info.Functions {
			sig := fn.Signature
			wrapper, skipReason := generateWrapperForFn(info.ImportPath, info.Name, sig)
			if wrapper != "" {
				pkgWrappers = append(pkgWrappers, wrapper)
			}
			if skipReason != "" {
				pkgSkipped++
			}
		}

		if len(pkgWrappers) > 0 {
			b.WriteString(fmt.Sprintf(";;;;; Package: %s (%d wrappers", info.ImportPath, len(pkgWrappers)))
			if pkgSkipped > 0 {
				b.WriteString(fmt.Sprintf(", %d skipped", pkgSkipped))
			}
			b.WriteString(")\n")
			for _, w := range pkgWrappers {
				b.WriteString(w)
				b.WriteString("\n")
			}
			b.WriteString("\n")
		}

		totalWrappers += len(pkgWrappers)
		totalSkipped += pkgSkipped
	}

	log.Printf("Generated %d Lisp wrappers (%d skipped)", totalWrappers, totalSkipped)

	outPath := "go_auto_wrapper.lisp"
	return os.WriteFile(outPath, []byte(b.String()), 0644)
}

// lispPkgPrefix maps Go package names to Lisp name prefixes.
var lispPkgPrefix = map[string]string{
	"strings":           "string-",
	"strconv":           "string-",
	"path/filepath":     "path-",
	"path":              "path-",
	"net/http":          "http-",
	"net/url":           "url-",
	"net/mail":          "mail-",
	"net/smtp":          "smtp-",
	"net/textproto":     "textproto-",
	"net/rpc":           "rpc-",
	"os/exec":           "exec-",
	"os/user":           "user-",
	"os/signal":         "signal-",
	"encoding/json":     "json-",
	"encoding/csv":      "csv-",
	"encoding/xml":      "xml-",
	"encoding/hex":      "hex-",
	"encoding/pem":      "pem-",
	"encoding/base64":   "base64-",
	"encoding/base32":   "base32-",
	"encoding/gob":      "gob-",
	"encoding/asn1":     "asn1-",
	"encoding/binary":   "binary-",
	"crypto/tls":        "tls-",
	"crypto/x509":       "x509-",
	"crypto/sha256":     "sha256-",
	"crypto/sha512":     "sha512-",
	"crypto/sha1":       "sha1-",
	"crypto/md5":        "md5-",
	"crypto/rsa":        "rsa-",
	"crypto/ecdsa":      "ecdsa-",
	"crypto/ed25519":    "ed25519-",
	"crypto/aes":        "aes-",
	"crypto/cipher":     "cipher-",
	"crypto/hmac":       "hmac-",
	"crypto/dsa":        "dsa-",
	"crypto/elliptic":   "elliptic-",
	"database/sql":      "sql-",
	"html":              "html-",
	"html/template":     "html-template-",
	"text/template":     "template-",
	"text/scanner":      "scanner-",
	"archive/tar":       "tar-",
	"archive/zip":       "zip-",
	"compress/gzip":     "gzip-",
	"compress/zlib":     "zlib-",
	"compress/flate":    "flate-",
	"compress/bzip2":    "bzip2-",
	"compress/lzw":      "lzw-",
	"hash/crc32":        "crc32-",
	"hash/crc64":        "crc64-",
	"hash/adler32":      "adler32-",
	"hash/fnv":          "fnv-",
	"hash/maphash":      "maphash-",
	"image":             "image-",
	"image/jpeg":        "jpeg-",
	"image/png":         "png-",
	"image/gif":         "gif-",
	"image/color":       "color-",
	"image/draw":        "draw-",
	"mime":              "mime-",
	"mime/multipart":    "multipart-",
	"log/slog":          "slog-",
	"runtime/debug":     "rdebug-",
	"runtime/pprof":     "pprof-",
	"runtime/metrics":   "rmetrics-",
	"runtime/trace":     "rtrace-",
	"go/ast":            "ast-",
	"go/parser":         "parser-",
	"go/token":          "token-",
	"go/format":         "gofmt-",
	"go/doc":            "godoc-",
	"go/build":          "gobuild-",
	"go/printer":        "goprint-",
	"go/scanner":        "goscanner-",
	"go/types":          "gotypes-",
	"go/constant":       "goconst-",
	"debug/elf":         "elf-",
	"debug/macho":       "macho-",
	"debug/pe":          "pe-",
	"debug/dwarf":       "dwarf-",
	"debug/gosym":       "gosym-",
	"debug/buildinfo":   "buildinfo-",
	"sync":              "sync-",
	"sync/atomic":       "atomic-",
	"container/heap":    "heap-",
	"container/list":    "list-",
	"container/ring":    "ring-",
	"index/suffixarray": "suffixarray-",
	"unicode":           "unicode-",
	"unicode/utf8":      "utf8-",
	"unicode/utf16":     "utf16-",
	"math/bits":         "bits-",
	"math/big":          "big-",
	"math/cmplx":        "cmplx-",
	"math/rand":         "rand-",
	"regexp":            "regexp-",
	"regexp/syntax":     "regexpsyn-",
	"bufio":             "bufio-",
	"fmt":               "fmt-",
	"log":               "log-",
	"flag":              "flag-",
	"sort":              "sort-",
	"testing":           "testing-",
	"reflect":           "reflect-",
	"plugin":            "plugin-",
	"context":           "context-",
	"expvar":            "expvar-",
	"io/fs":             "fs-",
	"io/ioutil":         "ioutil-",
	"net":               "net-",
	"net/netip":         "netip-",
	"net/rpc/jsonrpc":   "jsonrpc-",
	"net/http/cgi":      "cgi-",
	"net/http/fcgi":     "fcgi-",
	"net/http/httptest": "httptest-",
	"net/http/httputil": "httputil-",
	"net/http/httptrace": "httptrace-",
	"net/http/cookiejar": "cookiejar-",
	"net/http/pprof":    "hpprof-",
	"os":                "",
	"io":                "io-",
	"time":              "time-",
	"math":              "math-",
	"errors":            "errors-",
	"runtime":           "runtime-",
}

// skipFuncs are functions that should NOT get auto-generated wrappers.
var skipFuncs = map[string]bool{
	"strings.Contains":       true,
	"strings.HasPrefix":      true,
	"strings.HasSuffix":      true,
	"strings.Split":          true,
	"strings.SplitN":         true,
	"strings.Join":           true,
	"strings.Replace":        true,
	"strings.ReplaceAll":     true,
	"strings.TrimSpace":      true,
	"strings.ToUpper":        true,
	"strings.ToLower":        true,
	"strings.Repeat":         true,
	"os.ReadFile":            true,
	"os.WriteFile":           true,
	"os.OpenFile":            true,
	"os.Stat":                true,
	"os.Remove":              true,
	"os.Rename":              true,
	"os.ReadDir":             true,
	"os.Mkdir":               true,
	"os.MkdirAll":            true,
	"os.CreateTemp":          true,
	"os.Getenv":              true,
	"os.Setenv":              true,
	"os.Unsetenv":            true,
	"os.Environ":             true,
	"os.Getwd":               true,
	"os.Chdir":               true,
	"os.Getpid":              true,
	"os.Hostname":            true,
	"os.ExpandEnv":           true,
	"net/http.Get":           true,
	"net/http.Post":          true,
	"net/http.StatusText":    true,
	"path/filepath.Abs":      true,
	"path/filepath.Base":     true,
	"path/filepath.Dir":      true,
	"path/filepath.Ext":      true,
	"path/filepath.Join":     true,
	"path/filepath.Clean":    true,
	"path/filepath.IsAbs":    true,
	"regexp.MatchString":     true,
	"regexp.Compile":         true,
	"io.ReadAll":             true,
	"time.Now":               true,
	"time.Unix":              true,
	"time.Parse":             true,
	"encoding/json.Valid":    true,
	"encoding/json.Marshal":  true,
	"net/url.QueryEscape":    true,
	"net/url.QueryUnescape":  true,
	"net/url.Parse":          true,
	"os/exec.Command":        true,
	"os/exec.LookPath":       true,
	"runtime.Version":        true,
	"runtime.NumCPU":         true,
	"os.Exit":                true,
	"time.Sleep":             true,
}

// incompatibleParamPatterns contains Go type patterns that can not be passed from Lisp.
var incompatibleParamPatterns = []string{
	"context.Context",
	"io.Writer",
	"io.Reader",
	"io.ReadWriter",
	"io.WriteCloser",
	"io.ReadCloser",
	"io.ReadSeeker",
	"io.Seeker",
	"io.ReaderAt",
	"io.WriterAt",
	"http.ResponseWriter",
	"http.Handler",
	"http.Flusher",
	"http.Hijacker",
	"http.Pusher",
	"func(",
	"chan ",
	"reflect.Type",
	"reflect.Value",
	"testing.T",
	"testing.B",
	"testing.F",
}

// generateWrapperForFn creates a Lisp (define) wrapper for a Go function.
func generateWrapperForFn(importPath, pkgName string, sig FuncSig) (string, string) {
	fullName := importPath + "." + sig.Name

	if skipFuncs[fullName] {
		return "", "explicitly skipped"
	}

	for _, pt := range sig.ParamTypes {
		for _, pattern := range incompatibleParamPatterns {
			if strings.Contains(pt, pattern) {
				return "", "incompatible param: " + pt
			}
		}
	}

	if len(sig.ReturnType) == 1 && sig.ReturnType[0] == "error" {
		return "", "returns only error"
	}

	if sig.Variadic && len(sig.ParamTypes) > 0 {
		lastParam := sig.ParamTypes[len(sig.ParamTypes)-1]
		for _, pattern := range incompatibleParamPatterns {
			if strings.Contains(lastParam, pattern) {
				return "", "variadic with incompatible: " + lastParam
			}
		}
	}

	lispName := lispFuncName(importPath, sig.Name)
	params := lispParamNames(sig.ParamTypes, sig.Variadic)

	if len(params) == 0 {
		return fmt.Sprintf("(define (%s) (funcall (go:import \"%s.%s\")))",
			lispName, importPath, sig.Name), ""
	}

	return fmt.Sprintf("(define (%s %s) (funcall (go:import \"%s.%s\") %s))",
		lispName, params, importPath, sig.Name, params), ""
}

// lispFuncName converts a Go function name to a Lisp-style name.
func lispFuncName(importPath, goName string) string {
	prefix, ok := lispPkgPrefix[importPath]
	if !ok {
		parts := strings.Split(importPath, "/")
		prefix = parts[len(parts)-1] + "-"
	}
	name := camelToKebab(goName)
	return prefix + name
}

// camelToKebab converts CamelCase to kebab-case.
func camelToKebab(s string) string {
	var result []byte
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				prev := s[i-1]
				if prev >= 'a' && prev <= 'z' {
					result = append(result, '-')
				} else if i+1 < len(s) && s[i+1] >= 'a' && s[i+1] <= 'z' {
					result = append(result, '-')
				}
			}
			result = append(result, c+32)
		} else {
			result = append(result, c)
		}
	}
	return string(result)
}

// lispParamNames generates Lisp parameter names from Go parameter types.
func lispParamNames(paramTypes []string, variadic bool) string {
	if len(paramTypes) == 0 {
		return ""
	}

	names := make([]string, len(paramTypes))
	used := map[string]int{}

	for i, pt := range paramTypes {
		base := typeToParamName(pt)
		if n, ok := used[base]; ok {
			used[base] = n + 1
			names[i] = fmt.Sprintf("%s%d", base, n+1)
		} else {
			used[base] = 1
			names[i] = base
		}
	}

	if variadic && len(names) > 0 {
		names[len(names)-1] = "." + names[len(names)-1]
	}

	return strings.Join(names, " ")
}

// typeToParamName maps Go type strings to short Lisp parameter names.
func typeToParamName(goType string) string {
	if idx := strings.LastIndex(goType, "."); idx >= 0 {
		goType = goType[idx+1:]
	}
	switch {
	case goType == "string":
		return "s"
	case goType == "int" || goType == "int64" || goType == "int32":
		return "n"
	case goType == "float64" || goType == "float32":
		return "x"
	case goType == "bool":
		return "b"
	case goType == "error":
		return "err"
	case goType == "byte" || goType == "rune":
		return "c"
	case strings.HasPrefix(goType, "[]"):
		return "lst"
	case strings.HasPrefix(goType, "*"):
		return "ptr"
	case strings.HasSuffix(goType, "Reader"):
		return "r"
	case strings.HasSuffix(goType, "Writer"):
		return "w"
	case strings.HasSuffix(goType, "Closer"):
		return "cl"
	case strings.HasSuffix(goType, "Handler"):
		return "h"
	default:
		if len(goType) > 0 {
			return strings.ToLower(goType[:1])
		}
		return "v"
	}
}
